<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Services;

use Contensio\Models\ContentTypeMeta;
use Contensio\Models\Media;
use Contensio\Models\MediaVariant;
use Intervention\Image\Encoders\WebpEncoder;
use Intervention\Image\Laravel\Facades\Image;
use Illuminate\Support\Facades\Storage;

class ImageProcessingService
{
    /**
     * Generate all active variants for a media item.
     * Collects the union of active sizes across all content types.
     */
    public function processMedia(Media $media): void
    {
        if (! $media->isImage()) {
            return;
        }

        foreach ($this->getActiveSizes() as $sizeKey => $config) {
            $this->generateVariant($media, $sizeKey, $config);
        }
    }

    /**
     * Regenerate a specific size variant for a single media item.
     * Used when a content type's image size config changes.
     */
    public function generateVariant(Media $media, string $sizeKey, array $config): ?MediaVariant
    {
        if (! $media->isImage()) {
            return null;
        }

        $disk       = $media->disk;
        $sourcePath = Storage::disk($disk)->path($media->file_path);

        if (! file_exists($sourcePath)) {
            return null;
        }

        $width      = (int) $config['width'];
        $height     = (int) $config['height'];
        $fit        = $config['fit'] ?? 'cover';
        $quality    = (int) ($config['quality'] ?? 85);
        $background = ltrim($config['background'] ?? '#ffffff', '#');

        $image = Image::decode($sourcePath);

        match ($fit) {
            'contain' => $image->contain($width, $height),
            'scale'   => $image->scale($width, $height),
            'crop'    => $image->crop($width, $height),
            'pad'     => $image->pad($width, $height, $background),
            default   => $image->cover($width, $height),   // 'cover' and fallback
        };

        $dir         = dirname($media->file_path);
        $basename    = pathinfo($media->file_path, PATHINFO_FILENAME);
        $variantPath = "{$dir}/{$basename}_{$sizeKey}.webp";

        $encoded = $image->encode(new WebpEncoder(quality: $quality));

        Storage::disk($disk)->put($variantPath, (string) $encoded);

        $storedPath = Storage::disk($disk)->path($variantPath);
        [$actualW, $actualH] = @getimagesize($storedPath) ?: [null, null];

        return MediaVariant::updateOrCreate(
            ['media_id' => $media->id, 'size_key' => $sizeKey],
            [
                'path'      => $variantPath,
                'width'     => $actualW,
                'height'    => $actualH,
                'file_size' => Storage::disk($disk)->size($variantPath),
            ]
        );
    }

    /**
     * Delete a specific variant file and record for a media item.
     */
    public function deleteVariant(Media $media, string $sizeKey): void
    {
        $variant = MediaVariant::where('media_id', $media->id)
            ->where('size_key', $sizeKey)
            ->first();

        if ($variant) {
            Storage::disk($media->disk)->delete($variant->path);
            $variant->delete();
        }
    }

    /**
     * Delete all variant files and records for a media item.
     */
    public function deleteAllVariants(Media $media): void
    {
        foreach ($media->variants as $variant) {
            Storage::disk($media->disk)->delete($variant->path);
        }

        MediaVariant::where('media_id', $media->id)->delete();
    }

    /**
     * Return the union of all active sizes across every content type,
     * merged with the config defaults. Keyed by size_key.
     */
    public function getActiveSizes(): array
    {
        $presets = config('contensio.image_sizes', []);
        $active  = [];

        $rows = ContentTypeMeta::where('meta_key', 'image_sizes')->get();

        foreach ($rows as $row) {
            $sizes = json_decode($row->meta_value, true) ?? [];

            foreach ($sizes as $size) {
                $key = $size['key'] ?? null;

                if (! $key || empty($size['active'])) {
                    continue;
                }

                // First content type to activate a key wins for the config;
                // subsequent types may differ in dimensions but we store all
                // variants by key so each media item gets one file per key.
                if (! isset($active[$key])) {
                    $active[$key] = array_merge($presets[$key] ?? [], $size);
                }
            }
        }

        // If no content type meta exists yet, fall back to config defaults
        // for presets that are active for '*'.
        if ($rows->isEmpty()) {
            foreach ($presets as $key => $preset) {
                if (in_array('*', $preset['default_for'] ?? [])) {
                    $active[$key] = $preset;
                }
            }
        }

        return $active;
    }
}
