<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Cms\Support;

use Illuminate\Support\Collection;
use Contensio\Cms\Models\Content;
use Contensio\Cms\Models\ContentTranslation;
use Contensio\Cms\Models\Menu;
use Contensio\Cms\Models\MenuLocation;
use Contensio\Cms\Models\Term;
use Contensio\Cms\Models\TermTranslation;

/**
 * Resolves the menu assigned to a theme location and returns a nested tree
 * of items ready for a theme to render.
 *
 * Each tree node looks like:
 *   [
 *       'label'    => 'About',
 *       'url'      => '/about',
 *       'target'   => '_self',
 *       'icon'     => 'bi-house-door' | null,
 *       'active'   => bool,
 *       'children' => [ ...same shape... ],
 *   ]
 */
class MenuRenderer
{
    /** Per-request cache keyed by "{theme}:{location}:{lang}". */
    protected static array $cache = [];

    /**
     * Get the tree for a theme location. Returns [] if nothing is assigned
     * or the assigned menu has no active items.
     */
    public static function forLocation(string $location, ?int $langId = null): array
    {
        $theme   = ThemeRegistry::activeName();
        $langId ??= static::defaultLanguageId();

        $cacheKey = "{$theme}:{$location}:{$langId}";
        if (isset(static::$cache[$cacheKey])) {
            return static::$cache[$cacheKey];
        }

        try {
            $assignment = MenuLocation::where('theme', $theme)
                ->where('location', $location)
                ->whereNotNull('menu_id')
                ->first();

            if (! $assignment) {
                return static::$cache[$cacheKey] = [];
            }

            $menu = Menu::with([
                'allItems' => fn ($q) => $q->where('is_active', true)->orderBy('position'),
                'allItems.translations' => fn ($q) => $q->where('language_id', $langId),
            ])->find($assignment->menu_id);

            if (! $menu) {
                return static::$cache[$cacheKey] = [];
            }

            return static::$cache[$cacheKey] = static::buildTree($menu->allItems, $langId);
        } catch (\Throwable) {
            return static::$cache[$cacheKey] = [];
        }
    }

    // ── Internal ────────────────────────────────────────────────────────────

    protected static function buildTree(Collection $items, int $langId): array
    {
        // Resolve URLs once per request, batched by type
        $pageIds = $items->where('type', 'page')->pluck('reference_id')->filter()->unique()->values();
        $postIds = $items->where('type', 'post')->pluck('reference_id')->filter()->unique()->values();
        $contentIds = $items->where('type', 'content')->pluck('reference_id')->filter()->unique()->values();
        $termIds = $items->where('type', 'term')->pluck('reference_id')->filter()->unique()->values();

        $pageSlugs = static::contentSlugs($pageIds->concat($postIds)->concat($contentIds), $langId);
        $termSlugs = static::termSlugs($termIds, $langId);

        $currentPath = trim(request()->path(), '/');

        // Group items by parent_id
        $byParent = $items->groupBy(fn ($i) => $i->parent_id ?? 0);

        $render = function ($parentId) use (&$render, $byParent, $pageSlugs, $termSlugs, $currentPath, $langId) {
            $children = $byParent->get($parentId, collect());
            $out = [];

            foreach ($children as $item) {
                $tr = $item->translations->first();
                if (! $tr) {
                    continue;
                }

                $url = static::resolveUrl($item, $tr, $pageSlugs, $termSlugs);
                if ($url === null) {
                    continue;
                }

                $urlPath = trim(parse_url($url, PHP_URL_PATH) ?? '', '/');
                $active  = $urlPath !== '' && $urlPath === $currentPath;

                $out[] = [
                    'label'    => $tr->label,
                    'url'      => $url,
                    'target'   => $item->target,
                    'icon'     => $item->icon,
                    'active'   => $active,
                    'children' => $render($item->id),
                ];
            }

            return $out;
        };

        return $render(0);
    }

    protected static function resolveUrl($item, $tr, array $pageSlugs, array $termSlugs): ?string
    {
        switch ($item->type) {
            case 'custom_url':
                return $tr->url ?: null;

            case 'page':
            case 'post':
            case 'content':
                $slug = $pageSlugs[$item->reference_id] ?? null;
                if (! $slug) return null;
                if ($item->type === 'post') {
                    return route('cms.post', $slug);
                }
                return route('cms.page', $slug);

            case 'term':
                $slug = $termSlugs[$item->reference_id] ?? null;
                return $slug ? url('/t/' . $slug) : null;

            default:
                return null;
        }
    }

    /** Map content IDs → slugs in the given language. */
    protected static function contentSlugs(Collection $ids, int $langId): array
    {
        if ($ids->isEmpty()) return [];
        return ContentTranslation::whereIn('content_id', $ids)
            ->where('language_id', $langId)
            ->pluck('slug', 'content_id')
            ->toArray();
    }

    /** Map term IDs → slugs in the given language. */
    protected static function termSlugs(Collection $ids, int $langId): array
    {
        if ($ids->isEmpty()) return [];
        return TermTranslation::whereIn('term_id', $ids)
            ->where('language_id', $langId)
            ->pluck('slug', 'term_id')
            ->toArray();
    }

    protected static function defaultLanguageId(): int
    {
        try {
            return \Contensio\Cms\Models\Language::where('is_default', true)->value('id')
                ?? \Contensio\Cms\Models\Language::orderBy('position')->value('id')
                ?? 0;
        } catch (\Throwable) {
            return 0;
        }
    }
}
