<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Support;

use Contensio\Models\Setting;

/**
 * Per-theme customization values (colors, fonts, layout, etc.).
 *
 * Schema source:   theme.json → "settings.sections[].fields[]"
 * Value storage:   settings table — one row per theme
 *                  module = "theme_options"
 *                  setting_key = vendor/name
 *                  value = JSON blob of all values
 *
 * Each theme keeps its own values, so switching themes doesn't lose anything —
 * re-activate an old theme and its customizations come back.
 */
class ThemeOptions
{
    /** Per-request memoization. */
    protected static array $cache = [];

    /**
     * All values for a theme (or the active theme), with defaults applied.
     */
    public static function all(?string $theme = null): array
    {
        $theme ??= ThemeRegistry::activeName();

        if (isset(static::$cache[$theme])) {
            return static::$cache[$theme];
        }

        $defaults = static::defaults($theme);
        $saved    = [];

        try {
            $raw = Setting::where('module', 'theme_options')
                ->where('setting_key', $theme)
                ->value('value');
            if ($raw) {
                $decoded = json_decode($raw, true);
                if (is_array($decoded)) {
                    $saved = $decoded;
                }
            }
        } catch (\Throwable) {
            // settings table missing / DB unreachable — fall back to defaults
        }

        return static::$cache[$theme] = array_merge($defaults, $saved);
    }

    /**
     * Look up a single option value. Falls back to the provided default
     * if the key isn't defined in the schema and hasn't been saved.
     */
    public static function get(string $key, mixed $default = null, ?string $theme = null): mixed
    {
        $all = static::all($theme);
        return array_key_exists($key, $all) ? $all[$key] : $default;
    }

    /**
     * The schema ("sections" array) declared by a theme in its theme.json.
     */
    public static function schema(?string $theme = null): array
    {
        $theme ??= ThemeRegistry::activeName();
        $data  = ThemeRegistry::get($theme);

        return $data['meta']['settings']['sections'] ?? [];
    }

    /**
     * Flat array of defaults extracted from the schema.
     */
    public static function defaults(?string $theme = null): array
    {
        $defaults = [];
        foreach (static::schema($theme) as $section) {
            foreach ($section['fields'] ?? [] as $field) {
                if (empty($field['key'])) {
                    continue;
                }
                $defaults[$field['key']] = $field['default'] ?? null;
            }
        }
        return $defaults;
    }

    /**
     * Persist values for a theme. Preserves keys that are already stored
     * but no longer in the schema (for forward/backward compatibility).
     */
    public static function save(string $theme, array $values): void
    {
        $existing = static::all($theme);
        $merged   = array_merge($existing, $values);

        Setting::updateOrCreate(
            ['module' => 'theme_options', 'setting_key' => $theme],
            ['plugin' => $theme, 'value' => json_encode($merged, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)]
        );

        unset(static::$cache[$theme]);
    }

    /** Reset a theme to its declared defaults (deletes the saved row). */
    public static function reset(string $theme): void
    {
        Setting::where('plugin', $theme)->delete();
        unset(static::$cache[$theme]);
    }
}
