<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Cms\Support;

use Contensio\Cms\Models\Setting;

/**
 * Central registry for all discovered themes.
 *
 * Themes come from two sources:
 *   1. Local — extracted ZIPs in {project}/themes/{vendor}/{name}/
 *   2. Composer — packages in vendor/ with extra.cms.type = "theme"
 *
 * The active theme is stored in the database (core.active_theme),
 * never in .env — this allows non-technical users to switch themes
 * from the admin UI without server access.
 */
class ThemeRegistry
{
    /** @var array<string, array> Keyed by vendor/name */
    protected static array $themes = [];

    /**
     * Discover all available themes from both sources and seed the registry.
     * Called once in CmsServiceProvider::boot().
     */
    public static function discover(): void
    {
        static::$themes = [];

        // ── Themes installed in packages/themes/{vendor}/{name}/ ──────────
        // This is where ALL themes live — both the default and user-installed ones.
        // packages_path is configured in config/cms.php (default: base_path('packages')).
        $themesRoot = rtrim(config('cms.packages_path', base_path('packages')), '/') . '/themes';

        if (is_dir($themesRoot)) {
            foreach (glob("{$themesRoot}/*/*/theme.json") ?: [] as $manifest) {
                $meta = json_decode(file_get_contents($manifest), true);
                if (empty($meta['name'])) {
                    continue;
                }
                $dir = dirname($manifest);
                static::$themes[$meta['name']] = [
                    'source'   => 'local',
                    'path'     => $dir,
                    'viewPath' => "{$dir}/views",
                    'assetUrl' => 'packages/themes/' . $meta['name'],
                    'meta'     => array_merge(['removable' => true], $meta),
                ];
            }
        }

        // ── Fallback: built-in default shipped inside the CMS core package ─
        // Used only when packages/themes/contensio/default/ does not exist yet
        // (e.g. fresh install before the theme has been copied to packages/).
        if (! isset(static::$themes['contensio/default'])) {
            $builtInPath = dirname(__DIR__, 2) . '/resources/themes/contensio/default';
            if (is_dir($builtInPath)) {
                static::$themes['contensio/default'] = [
                    'source'   => 'builtin',
                    'path'     => $builtInPath,
                    'viewPath' => $builtInPath . '/views',
                    'assetUrl' => 'vendor/contensio/contensio/themes/default',
                    'meta'     => [
                        'name'        => 'contensio/default',
                        'label'       => 'Default',
                        'description' => 'The default theme that ships with Contensio.',
                        'author'      => 'Contensio',
                        'version'     => '1.0.0',
                        'removable'   => false,
                    ],
                ];
            }
        }

        // ── Composer package themes in vendor/ ────────────────────────────
        $installedJson = base_path('vendor/composer/installed.json');
        if (file_exists($installedJson)) {
            $data     = json_decode(file_get_contents($installedJson), true);
            $packages = $data['packages'] ?? $data;

            foreach ($packages as $package) {
                $cms = $package['extra']['cms'] ?? null;
                if (! $cms) {
                    continue;
                }
                $types = (array) ($cms['type'] ?? []);
                if (! in_array('theme', $types)) {
                    continue;
                }

                $name        = $package['name'];
                $installPath = base_path('vendor/' . $name);
                static::$themes[$name] = [
                    'source'   => 'composer',
                    'path'     => $installPath,
                    'viewPath' => $installPath . '/resources/views',
                    'assetUrl' => 'vendor/' . $name,
                    'provider' => $cms['provider'] ?? null,
                    'meta'     => array_merge(['removable' => false], $package),
                ];
            }
        }
    }

    /** Return all discovered themes. */
    public static function all(): array
    {
        return static::$themes;
    }

    /** Return a single theme by vendor/name, or null. */
    public static function get(string $name): ?array
    {
        return static::$themes[$name] ?? null;
    }

    /**
     * The vendor/name string of the currently active theme.
     * Reads from DB; falls back to 'contensio/default'.
     */
    public static function activeName(): string
    {
        try {
            $value = Setting::where('module', 'core')
                ->where('setting_key', 'active_theme')
                ->value('value');

            return $value ?: 'contensio/default';
        } catch (\Throwable) {
            return 'contensio/default';
        }
    }

    /** Return the active theme's metadata array, or null if not found. */
    public static function active(): ?array
    {
        $name = static::activeName();
        return static::$themes[$name] ?? static::$themes['contensio/default'] ?? null;
    }

    /** True if the given vendor/name is the currently active theme. */
    public static function isActive(string $name): bool
    {
        return static::activeName() === $name;
    }

    /**
     * Activate a theme by vendor/name.
     * Writes to the database — no .env or artisan required.
     */
    public static function activate(string $name): void
    {
        Setting::updateOrCreate(
            ['module' => 'core', 'setting_key' => 'active_theme'],
            ['value' => $name]
        );
    }

    /**
     * Register a theme manually (used by Composer package ThemeServiceProviders).
     */
    public static function add(string $name, array $data): void
    {
        static::$themes[$name] = $data;
    }
}
