<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Cms\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Str;
use Contensio\Cms\Models\BlockType;
use Contensio\Cms\Models\Content;
use Contensio\Cms\Models\Language;

class BlockController extends Controller
{
    /**
     * Show the edit form for a new block of the given type.
     */
    public function editNew(int $id, string $type)
    {
        $content = Content::with('contentType')->find($id);

        if (! $content) {
            return redirect()->route('cms.admin.dashboard')->with('error', 'Content not found.');
        }

        $blockType   = BlockType::where('name', $type)->where('is_active', true)->firstOrFail();
        $blockConfig = config("cms.blocks.{$type}", []);

        $block = [
            'id'           => 'blk_' . Str::random(12),
            'type'         => $type,
            'is_active'    => true,
            'data'         => [],
            'settings'     => [],
            'translations' => [],
        ];

        $languages       = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defaultLanguage = Language::where('is_default', true)->first();

        return view('cms::admin.blocks.form', compact(
            'content', 'block', 'blockType', 'blockConfig', 'languages', 'defaultLanguage'
        ));
    }

    /**
     * Store a new block (append to content's blocks JSON).
     */
    public function store(Request $request, int $id)
    {
        $request->validate(['block_type' => ['required', 'string']]);

        $content = Content::find($id);

        if (! $content) {
            return redirect()->route('cms.admin.dashboard')->with('error', 'Content not found.');
        }

        $block    = $this->buildBlockFromRequest($request);
        $blocks   = $content->blocks ?? [];
        $blocks[] = $block;

        $content->update(['blocks' => $blocks]);

        return redirect($this->backUrl($content))->with('success', 'Block added.');
    }

    /**
     * Show the edit form for an existing block.
     */
    public function edit(int $id, string $blockId)
    {
        $content = Content::with('contentType')->find($id);

        if (! $content) {
            return redirect()->route('cms.admin.dashboard')->with('error', 'Content not found.');
        }

        $block = collect($content->blocks ?? [])->firstWhere('id', $blockId);

        if (! $block) {
            return redirect($this->backUrl($content))->with('error', 'Block not found.');
        }

        $type        = $block['type'];
        $blockType   = BlockType::where('name', $type)->firstOrFail();
        $blockConfig = config("cms.blocks.{$type}", []);

        $languages       = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defaultLanguage = Language::where('is_default', true)->first();

        return view('cms::admin.blocks.form', compact(
            'content', 'block', 'blockType', 'blockConfig', 'languages', 'defaultLanguage'
        ));
    }

    /**
     * Update an existing block.
     */
    public function update(Request $request, int $id, string $blockId)
    {
        $request->validate(['block_type' => ['required', 'string']]);

        $content = Content::find($id);

        if (! $content) {
            return redirect()->route('cms.admin.dashboard')->with('error', 'Content not found.');
        }

        $blocks = $content->blocks ?? [];
        $index  = collect($blocks)->search(fn ($b) => ($b['id'] ?? '') === $blockId);

        if ($index === false) {
            return redirect($this->backUrl($content))->with('error', 'Block not found.');
        }

        $blockData       = $this->buildBlockFromRequest($request);
        $blockData['id'] = $blockId;
        $blocks[$index]  = $blockData;

        $content->update(['blocks' => array_values($blocks)]);

        if ($request->boolean('_stay')) {
            return redirect()->route('cms.admin.blocks.edit', [$id, $blockId])
                ->with('success', 'Block saved.');
        }

        return redirect($this->backUrl($content))->with('success', 'Block updated.');
    }

    /**
     * Delete a block.
     */
    public function destroy(Request $request, int $id, string $blockId)
    {
        $content = Content::find($id);

        if (! $content) {
            return redirect()->route('cms.admin.dashboard');
        }

        $blocks = array_values(
            array_filter($content->blocks ?? [], fn ($b) => ($b['id'] ?? '') !== $blockId)
        );

        $content->update(['blocks' => $blocks]);

        return redirect($this->backUrl($content))->with('success', 'Block deleted.');
    }

    /**
     * Reorder blocks via AJAX.
     */
    public function reorder(Request $request, int $id)
    {
        $request->validate(['order' => ['required', 'array'], 'order.*' => ['string']]);

        $content = Content::find($id);

        if (! $content) {
            return response()->json(['success' => false, 'message' => 'Content not found.'], 404);
        }

        $order    = $request->input('order');
        $blockMap = collect($content->blocks ?? [])->keyBy('id')->all();

        $sorted = [];
        foreach ($order as $blockId) {
            if (isset($blockMap[$blockId])) {
                $sorted[] = $blockMap[$blockId];
                unset($blockMap[$blockId]);
            }
        }
        foreach ($blockMap as $block) {
            $sorted[] = $block;
        }

        $content->update(['blocks' => $sorted]);

        return response()->json(['success' => true]);
    }

    /**
     * Toggle block active/inactive via AJAX.
     */
    public function toggle(Request $request, int $id, string $blockId)
    {
        $content = Content::find($id);

        if (! $content) {
            return response()->json(['success' => false, 'message' => 'Content not found.'], 404);
        }

        $blocks  = $content->blocks ?? [];
        $updated = false;

        foreach ($blocks as &$block) {
            if (($block['id'] ?? '') === $blockId) {
                $block['is_active'] = ! ($block['is_active'] ?? true);
                $updated = true;
                break;
            }
        }

        if (! $updated) {
            return response()->json(['success' => false, 'message' => 'Block not found.'], 404);
        }

        $content->update(['blocks' => $blocks]);

        return response()->json(['success' => true]);
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    protected function buildBlockFromRequest(Request $request): array
    {
        return [
            'id'           => $request->input('block_id', 'blk_' . Str::random(12)),
            'type'         => $request->input('block_type'),
            'is_active'    => (bool) $request->input('is_active', true),
            'data'         => $request->input('block_data', []),
            'settings'     => $request->input('block_settings', []),
            'translations' => $request->input('block_translations', []),
        ];
    }

    protected function backUrl(Content $content): string
    {
        return match ($content->contentType?->name) {
            'post'  => route('cms.admin.posts.edit', $content->id),
            default => route('cms.admin.pages.edit', $content->id),
        };
    }
}
