<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Cms\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Str;
use Contensio\Cms\Models\ContentType;
use Contensio\Cms\Models\ContentTypeTranslation;
use Contensio\Cms\Models\Language;

class ContentTypeController extends Controller
{
    public function index()
    {
        $types = ContentType::with(['translations', 'taxonomies.translations'])
            ->orderBy('position')
            ->get();

        return view('cms::admin.content-types.index', compact('types'));
    }

    public function create()
    {
        $languages       = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defaultLanguage = Language::where('is_default', true)->first() ?? $languages->first();

        return view('cms::admin.content-types.form', [
            'type'            => null,
            'languages'       => $languages,
            'defaultLanguage' => $defaultLanguage,
            'existing'        => [],
        ]);
    }

    public function store(Request $request)
    {
        $languages       = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defaultLanguage = Language::where('is_default', true)->first() ?? $languages->first();
        $defaultLangId   = $defaultLanguage?->id ?? 1;

        $request->validate([
            "translations.{$defaultLangId}.singular" => 'required|string|max:100',
            "translations.{$defaultLangId}.plural"   => 'required|string|max:100',
            "translations.{$defaultLangId}.slug"     => 'required|string|max:100|alpha_dash',
        ]);

        $defaultSingular = $request->input("translations.{$defaultLangId}.singular");
        $internalName    = Str::slug($defaultSingular, '_');

        if (ContentType::where('name', $internalName)->exists()) {
            return back()->withInput()
                ->withErrors(["translations.{$defaultLangId}.singular" => 'A content type with this name already exists.']);
        }

        $position = (ContentType::max('position') ?? 0) + 1;

        $type = ContentType::create([
            'name'               => $internalName,
            'icon'               => $request->icon ?: null,
            'has_slug'           => $request->boolean('has_slug', true),
            'has_editor'         => true,
            'has_excerpt'        => $request->boolean('has_excerpt'),
            'has_featured_image' => $request->boolean('has_featured_image'),
            'has_categories'     => $request->boolean('has_categories'),
            'has_tags'           => $request->boolean('has_tags'),
            'has_comments'       => $request->boolean('has_comments'),
            'has_seo'            => $request->boolean('has_seo', true),
            'has_autosave'       => true,
            'is_hierarchical'    => $request->boolean('is_hierarchical'),
            'is_system'          => false,
            'position'           => $position,
        ]);

        foreach ($languages as $lang) {
            $singular = $request->input("translations.{$lang->id}.singular");
            $plural   = $request->input("translations.{$lang->id}.plural");
            $slug     = $request->input("translations.{$lang->id}.slug");

            if (! $singular || ! $plural || ! $slug) {
                continue;
            }

            ContentTypeTranslation::create([
                'content_type_id' => $type->id,
                'language_id'     => $lang->id,
                'slug'            => $slug,
                'labels'          => $this->buildLabels($singular, $plural,
                    $request->input("translations.{$lang->id}.labels", [])),
            ]);
        }

        return redirect()->route('cms.admin.content-types.index')
            ->with('success', "Content type \"{$defaultSingular}\" created.");
    }

    public function edit(int $id)
    {
        $type = ContentType::with(['translations', 'taxonomies.translations'])->find($id);

        if (! $type) {
            return redirect()->route('cms.admin.content-types.index')
                ->with('error', 'Content type not found.');
        }

        $languages       = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defaultLanguage = Language::where('is_default', true)->first() ?? $languages->first();

        // Build existing translations map keyed by language_id
        $existing = [];
        foreach ($type->translations as $trans) {
            $existing[$trans->language_id] = [
                'singular'  => $trans->labels['singular']  ?? '',
                'plural'    => $trans->labels['plural']    ?? '',
                'slug'      => $trans->slug,
                'create'    => $trans->labels['create']    ?? '',
                'edit'      => $trans->labels['edit']      ?? '',
                'delete'    => $trans->labels['delete']    ?? '',
                'all'       => $trans->labels['all']       ?? '',
                'search'    => $trans->labels['search']    ?? '',
                'not_found' => $trans->labels['not_found'] ?? '',
            ];
        }

        return view('cms::admin.content-types.form', [
            'type'            => $type,
            'languages'       => $languages,
            'defaultLanguage' => $defaultLanguage,
            'existing'        => $existing,
        ]);
    }

    public function update(Request $request, int $id)
    {
        $type = ContentType::find($id);

        if (! $type) {
            return redirect()->route('cms.admin.content-types.index')
                ->with('error', 'Content type not found.');
        }

        $languages       = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defaultLanguage = Language::where('is_default', true)->first() ?? $languages->first();
        $defaultLangId   = $defaultLanguage?->id ?? 1;

        $request->validate([
            "translations.{$defaultLangId}.singular" => 'required|string|max:100',
            "translations.{$defaultLangId}.plural"   => 'required|string|max:100',
            "translations.{$defaultLangId}.slug"     => 'required|string|max:100|alpha_dash',
        ]);

        $type->update([
            'icon'               => $request->icon ?: null,
            'has_slug'           => $request->boolean('has_slug', true),
            'has_excerpt'        => $request->boolean('has_excerpt'),
            'has_featured_image' => $request->boolean('has_featured_image'),
            'has_categories'     => $request->boolean('has_categories'),
            'has_tags'           => $request->boolean('has_tags'),
            'has_comments'       => $request->boolean('has_comments'),
            'has_seo'            => $request->boolean('has_seo', true),
            'is_hierarchical'    => $request->boolean('is_hierarchical'),
        ]);

        foreach ($languages as $lang) {
            $singular = $request->input("translations.{$lang->id}.singular");
            $plural   = $request->input("translations.{$lang->id}.plural");
            $slug     = $request->input("translations.{$lang->id}.slug");

            if (! $singular || ! $plural || ! $slug) {
                continue;
            }

            ContentTypeTranslation::updateOrCreate(
                ['content_type_id' => $type->id, 'language_id' => $lang->id],
                [
                    'slug'   => $slug,
                    'labels' => $this->buildLabels($singular, $plural,
                        $request->input("translations.{$lang->id}.labels", [])),
                ]
            );
        }

        $defaultSingular = $request->input("translations.{$defaultLangId}.singular");

        return redirect()->route('cms.admin.content-types.index')
            ->with('success', "Content type \"{$defaultSingular}\" saved.");
    }

    public function destroy(int $id)
    {
        $type = ContentType::find($id);

        if (! $type) {
            return redirect()->route('cms.admin.content-types.index');
        }

        if ($type->is_system) {
            return redirect()->route('cms.admin.content-types.index')
                ->with('error', 'Core content types cannot be deleted.');
        }

        $contentCount = \Illuminate\Support\Facades\DB::table('contents')
            ->where('content_type_id', $type->id)
            ->count();

        if ($contentCount > 0) {
            return redirect()->route('cms.admin.content-types.index')
                ->with('error', "Cannot delete \"{$type->name}\" — it still has {$contentCount} item(s). Delete the content first.");
        }

        $type->delete();

        return redirect()->route('cms.admin.content-types.index')
            ->with('success', 'Content type deleted.');
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private function buildLabels(string $singular, string $plural, array $overrides = []): array
    {
        $defaults = [
            'singular'  => $singular,
            'plural'    => $plural,
            'create'    => "Add New {$singular}",
            'edit'      => "Edit {$singular}",
            'delete'    => "Delete {$singular}",
            'all'       => "All {$plural}",
            'search'    => "Search {$plural}",
            'not_found' => "No {$plural} found",
        ];

        return array_merge($defaults, array_filter($overrides, fn ($v) => $v !== null && $v !== ''));
    }
}
