<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Str;
use Contensio\Models\Autosave;
use Contensio\Models\BlockType;
use Contensio\Support\Activity;
use Contensio\Models\Content;
use Contensio\Models\ContentFieldValue;
use Contensio\Models\ContentTranslation;
use Contensio\Models\ContentType;
use Contensio\Models\Language;
use Contensio\Models\Term;
use Contensio\Models\TermTranslation;
use Contensio\Services\WorkflowService;
use Contensio\Http\Controllers\Admin\ReviewController;

class ContentController extends Controller
{
    // ─── Pages ───────────────────────────────────────────────────────────────

    public function pages()
    {
        $type  = ContentType::where('name', 'page')->first();
        $items = $type
            ? Content::where('content_type_id', $type->id)->with(['translations', 'author'])->latest()->get()
            : collect();

        return view('contensio::admin.pages.index', compact('items'));
    }

    public function createPage()
    {
        $type = ContentType::where('name', 'page')
            ->with(['taxonomies.translations', 'taxonomies.terms.translations'])
            ->firstOrFail();

        $blockTypes = BlockType::active()->ordered()->get();

        return view('contensio::admin.content.edit', array_merge(
            $this->editViewData(null, $type),
            [
                'content'    => null,
                'type'       => $type,
                'blockTypes' => $blockTypes,
                'backRoute'  => route('contensio.account.pages.index'),
                'storeRoute' => route('contensio.account.pages.store'),
                'method'     => 'POST',
            ]
        ));
    }

    public function storePage(Request $request)
    {
        $type      = ContentType::where('name', 'page')->firstOrFail();
        $languages = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defLangId = $this->defaultLangId($languages);

        $request->validate([
            "translations.{$defLangId}.title" => 'required|string|max:500',
            "translations.{$defLangId}.slug"  => 'nullable|string|max:500',
            'status'                           => 'required|in:draft,published,scheduled',
        ]);

        $content = Content::create([
            'code'            => Str::random(16),
            'content_type_id' => $type->id,
            'author_id'       => auth()->id(),
            'status'          => $request->status,
            'blocks'          => [],
            'published_at'    => $this->resolvePublishedAt($request, null),
        ]);

        $this->syncContent($request, $content, $languages);

        do_action('contensio/content/created', $content);

        Activity::record(
            $request->status === 'published' ? 'published' : 'created',
            'content',
            $content->id,
            'Page: ' . $request->input("translations.{$defLangId}.title")
        )->withProperties(['type' => 'page', 'status' => $content->status]);

        return redirect()->route('contensio.account.pages.edit', $content->id)
            ->with('success', 'Page created.');
    }

    public function editPage(int $id)
    {
        $type = ContentType::where('name', 'page')
            ->with(['taxonomies.translations', 'taxonomies.terms.translations'])
            ->firstOrFail();

        $content = Content::where('content_type_id', $type->id)
            ->with(['translations', 'author', 'terms', 'featuredImage'])
            ->find($id);

        if (! $content) {
            return redirect()->route('contensio.account.pages.index')->with('error', 'Page not found.');
        }

        $blockTypes = BlockType::active()->ordered()->get();

        return view('contensio::admin.content.edit', array_merge(
            $this->editViewData($content, $type),
            [
                'content'    => $content,
                'type'       => $type,
                'blockTypes' => $blockTypes,
                'backRoute'  => route('contensio.account.pages.index'),
                'storeRoute' => route('contensio.account.pages.update', $id),
                'method'     => 'PUT',
            ]
        ));
    }

    public function updatePage(Request $request, int $id)
    {
        $type    = ContentType::where('name', 'page')->firstOrFail();
        $content = Content::where('content_type_id', $type->id)->find($id);

        if (! $content) {
            return redirect()->route('contensio.account.pages.index')->with('error', 'Page not found.');
        }

        $languages = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defLangId = $this->defaultLangId($languages);

        $this->enforceWorkflowStatus($request);

        $request->validate([
            "translations.{$defLangId}.title" => 'required|string|max:500',
            "translations.{$defLangId}.slug"  => 'nullable|string|max:500',
            'status'                           => 'required|in:draft,published,scheduled',
        ]);

        $prevStatus = $content->status;

        $content->update([
            'status'       => $request->status,
            'published_at' => $this->resolvePublishedAt($request, $content),
        ]);

        $this->syncContent($request, $content, $languages);
        $this->clearAutosave($content);

        do_action('contensio/content/updated', $content);
        if ($prevStatus !== $request->status) {
            do_action('contensio/content/status-changed', $content, $prevStatus, $request->status);
        }

        $verb = match(true) {
            $prevStatus !== 'published'  && $request->status === 'published'  => 'published',
            $prevStatus !== 'scheduled'  && $request->status === 'scheduled'  => 'scheduled',
            default => 'updated',
        };
        Activity::record($verb, 'content', $content->id,
            'Page: ' . $request->input("translations.{$defLangId}.title")
        )->withProperties(['type' => 'page', 'status' => $content->status]);

        if ($redirect = $this->handleSubmitForReview($request, $content, 'contensio.account.pages.edit', $id)) {
            return $redirect;
        }

        return redirect()->route('contensio.account.pages.edit', $id)->with('success', 'Page saved.');
    }

    public function destroyPage(int $id)
    {
        $type    = ContentType::where('name', 'page')->firstOrFail();
        $content = Content::where('content_type_id', $type->id)->find($id);

        if (! $content) {
            return redirect()->route('contensio.account.pages.index');
        }

        $title = $content->translations()->value('title');
        do_action('contensio/content/deleting', $content);
        $content->delete();
        do_action('contensio/content/deleted', $id, 'page');

        Activity::record('deleted', 'content', $id, "Page: {$title}")
            ->withProperties(['type' => 'page']);

        return redirect()->route('contensio.account.pages.index')->with('success', 'Page deleted.');
    }

    // ─── Posts ────────────────────────────────────────────────────────────────

    public function posts()
    {
        $type  = ContentType::where('name', 'post')->first();
        $items = $type
            ? Content::where('content_type_id', $type->id)->with(['translations', 'author', 'featuredImage.variants'])->latest()->get()
            : collect();

        return view('contensio::admin.posts.index', compact('items'));
    }

    public function createPost()
    {
        $type = ContentType::where('name', 'post')
            ->with(['taxonomies.translations', 'taxonomies.terms.translations'])
            ->firstOrFail();

        $blockTypes = BlockType::active()->ordered()->get();

        return view('contensio::admin.content.edit', array_merge(
            $this->editViewData(null, $type),
            [
                'content'    => null,
                'type'       => $type,
                'blockTypes' => $blockTypes,
                'backRoute'  => route('contensio.account.posts.index'),
                'storeRoute' => route('contensio.account.posts.store'),
                'method'     => 'POST',
            ]
        ));
    }

    public function storePost(Request $request)
    {
        $type      = ContentType::where('name', 'post')->firstOrFail();
        $languages = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defLangId = $this->defaultLangId($languages);

        $request->validate([
            "translations.{$defLangId}.title" => 'required|string|max:500',
            "translations.{$defLangId}.slug"  => 'nullable|string|max:500',
            'status'                           => 'required|in:draft,published,scheduled',
        ]);

        $content = Content::create([
            'code'            => Str::random(16),
            'content_type_id' => $type->id,
            'author_id'       => auth()->id(),
            'status'          => $request->status,
            'blocks'          => [],
            'published_at'    => $this->resolvePublishedAt($request, null),
        ]);

        $this->syncContent($request, $content, $languages);

        do_action('contensio/content/created', $content);

        Activity::record(
            $request->status === 'published' ? 'published' : 'created',
            'content',
            $content->id,
            'Post: ' . $request->input("translations.{$defLangId}.title")
        )->withProperties(['type' => 'post', 'status' => $content->status]);

        return redirect()->route('contensio.account.posts.edit', $content->id)
            ->with('success', 'Post created.');
    }

    public function editPost(int $id)
    {
        $type = ContentType::where('name', 'post')
            ->with(['taxonomies.translations', 'taxonomies.terms.translations'])
            ->firstOrFail();

        $content = Content::where('content_type_id', $type->id)
            ->with(['translations', 'author', 'terms', 'featuredImage'])
            ->find($id);

        if (! $content) {
            return redirect()->route('contensio.account.posts.index')->with('error', 'Post not found.');
        }

        $blockTypes = BlockType::active()->ordered()->get();

        return view('contensio::admin.content.edit', array_merge(
            $this->editViewData($content, $type),
            [
                'content'    => $content,
                'type'       => $type,
                'blockTypes' => $blockTypes,
                'backRoute'  => route('contensio.account.posts.index'),
                'storeRoute' => route('contensio.account.posts.update', $id),
                'method'     => 'PUT',
            ]
        ));
    }

    public function updatePost(Request $request, int $id)
    {
        $type    = ContentType::where('name', 'post')->firstOrFail();
        $content = Content::where('content_type_id', $type->id)->find($id);

        if (! $content) {
            return redirect()->route('contensio.account.posts.index')->with('error', 'Post not found.');
        }

        $languages = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defLangId = $this->defaultLangId($languages);

        $this->enforceWorkflowStatus($request);

        $request->validate([
            "translations.{$defLangId}.title" => 'required|string|max:500',
            "translations.{$defLangId}.slug"  => 'nullable|string|max:500',
            'status'                           => 'required|in:draft,published,scheduled',
        ]);

        $prevStatus = $content->status;

        $content->update([
            'status'       => $request->status,
            'published_at' => $this->resolvePublishedAt($request, $content),
        ]);

        $this->syncContent($request, $content, $languages);
        $this->clearAutosave($content);

        do_action('contensio/content/updated', $content);
        if ($prevStatus !== $request->status) {
            do_action('contensio/content/status-changed', $content, $prevStatus, $request->status);
        }

        $verb = match(true) {
            $prevStatus !== 'published'  && $request->status === 'published'  => 'published',
            $prevStatus !== 'scheduled'  && $request->status === 'scheduled'  => 'scheduled',
            default => 'updated',
        };
        Activity::record($verb, 'content', $content->id,
            'Post: ' . $request->input("translations.{$defLangId}.title")
        )->withProperties(['type' => 'post', 'status' => $content->status]);

        if ($redirect = $this->handleSubmitForReview($request, $content, 'contensio.account.posts.edit', $id)) {
            return $redirect;
        }

        return redirect()->route('contensio.account.posts.edit', $id)->with('success', 'Post saved.');
    }

    public function destroyPost(int $id)
    {
        $type    = ContentType::where('name', 'post')->firstOrFail();
        $content = Content::where('content_type_id', $type->id)->find($id);

        if (! $content) {
            return redirect()->route('contensio.account.posts.index');
        }

        $title = $content->translations()->value('title');
        do_action('contensio/content/deleting', $content);
        $content->delete();
        do_action('contensio/content/deleted', $id, 'post');

        Activity::record('deleted', 'content', $id, "Post: {$title}")
            ->withProperties(['type' => 'post']);

        return redirect()->route('contensio.account.posts.index')->with('success', 'Post deleted.');
    }

    // ─── Custom content types ─────────────────────────────────────────────────

    public function indexContent(string $type)
    {
        $contentType = ContentType::where('name', $type)->where('is_system', false)->firstOrFail();
        $items       = Content::where('content_type_id', $contentType->id)
            ->with(['translations', 'author'])
            ->latest()
            ->get();

        $trans  = $contentType->translations->first();
        $plural = $trans?->labels['plural'] ?? ucfirst($type);

        return view('contensio::admin.content.index', compact('contentType', 'items', 'plural', 'type'));
    }

    public function createContent(string $type)
    {
        $contentType = ContentType::where('name', $type)->where('is_system', false)
            ->with(['taxonomies.translations', 'taxonomies.terms.translations'])
            ->firstOrFail();

        $blockTypes = BlockType::active()->ordered()->get();

        return view('contensio::admin.content.edit', array_merge(
            $this->editViewData(null, $contentType),
            [
                'content'    => null,
                'type'       => $contentType,
                'blockTypes' => $blockTypes,
                'backRoute'  => route('contensio.account.content.index', $type),
                'storeRoute' => route('contensio.account.content.store', $type),
                'method'     => 'POST',
            ]
        ));
    }

    public function storeContent(Request $request, string $type)
    {
        $contentType = ContentType::where('name', $type)->where('is_system', false)->firstOrFail();
        $languages   = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defLangId   = $this->defaultLangId($languages);

        $request->validate([
            "translations.{$defLangId}.title" => 'required|string|max:500',
            "translations.{$defLangId}.slug"  => 'nullable|string|max:500',
            'status'                           => 'required|in:draft,published,scheduled',
        ]);

        $content = Content::create([
            'code'            => Str::random(16),
            'content_type_id' => $contentType->id,
            'author_id'       => auth()->id(),
            'status'          => $request->status,
            'blocks'          => [],
            'published_at'    => $this->resolvePublishedAt($request, null),
        ]);

        $this->syncContent($request, $content, $languages);

        do_action('contensio/content/created', $content);

        return redirect()->route('contensio.account.content.edit', [$type, $content->id])
            ->with('success', 'Entry created.');
    }

    public function editContent(string $type, int $id)
    {
        $contentType = ContentType::where('name', $type)->where('is_system', false)
            ->with(['taxonomies.translations', 'taxonomies.terms.translations'])
            ->firstOrFail();

        $content = Content::where('content_type_id', $contentType->id)
            ->with(['translations', 'author', 'terms', 'featuredImage'])
            ->find($id);

        if (! $content) {
            return redirect()->route('contensio.account.content.index', $type)->with('error', 'Entry not found.');
        }

        $blockTypes = BlockType::active()->ordered()->get();

        return view('contensio::admin.content.edit', array_merge(
            $this->editViewData($content, $contentType),
            [
                'content'    => $content,
                'type'       => $contentType,
                'blockTypes' => $blockTypes,
                'backRoute'  => route('contensio.account.content.index', $type),
                'storeRoute' => route('contensio.account.content.update', [$type, $id]),
                'method'     => 'PUT',
            ]
        ));
    }

    public function updateContent(Request $request, string $type, int $id)
    {
        $contentType = ContentType::where('name', $type)->where('is_system', false)->firstOrFail();
        $content     = Content::where('content_type_id', $contentType->id)->find($id);

        if (! $content) {
            return redirect()->route('contensio.account.content.index', $type)->with('error', 'Entry not found.');
        }

        $languages = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defLangId = $this->defaultLangId($languages);

        $this->enforceWorkflowStatus($request);

        $request->validate([
            "translations.{$defLangId}.title" => 'required|string|max:500',
            "translations.{$defLangId}.slug"  => 'nullable|string|max:500',
            'status'                           => 'required|in:draft,published,scheduled',
        ]);

        $prevStatus = $content->status;

        $content->update([
            'status'       => $request->status,
            'published_at' => $this->resolvePublishedAt($request, $content),
        ]);

        $this->syncContent($request, $content, $languages);
        $this->clearAutosave($content);

        do_action('contensio/content/updated', $content);
        if ($prevStatus !== $request->status) {
            do_action('contensio/content/status-changed', $content, $prevStatus, $request->status);
        }

        if ($redirect = $this->handleSubmitForReview($request, $content, 'contensio.account.content.edit', $type, $id)) {
            return $redirect;
        }

        return redirect()->route('contensio.account.content.edit', [$type, $id])->with('success', 'Entry saved.');
    }

    public function destroyContent(string $type, int $id)
    {
        $contentType = ContentType::where('name', $type)->where('is_system', false)->firstOrFail();
        $content     = Content::where('content_type_id', $contentType->id)->find($id);

        if ($content) {
            do_action('contensio/content/deleting', $content);
            $content->delete();
            do_action('contensio/content/deleted', $id, $type);
        }

        return redirect()->route('contensio.account.content.index', $type)->with('success', 'Entry deleted.');
    }

    // ─── Clone ───────────────────────────────────────────────────────────────

    public function clonePage(int $id)
    {
        $type    = ContentType::where('name', 'page')->firstOrFail();
        $content = Content::where('content_type_id', $type->id)
            ->with(['translations', 'fieldValues', 'terms'])
            ->find($id);

        if (! $content) {
            return redirect()->route('contensio.account.pages.index')->with('error', 'Page not found.');
        }

        $clone = $this->performClone($content);

        return redirect()->route('contensio.account.pages.edit', $clone->id)
            ->with('success', 'Page duplicated. You are now editing the copy.');
    }

    public function clonePost(int $id)
    {
        $type    = ContentType::where('name', 'post')->firstOrFail();
        $content = Content::where('content_type_id', $type->id)
            ->with(['translations', 'fieldValues', 'terms'])
            ->find($id);

        if (! $content) {
            return redirect()->route('contensio.account.posts.index')->with('error', 'Post not found.');
        }

        $clone = $this->performClone($content);

        return redirect()->route('contensio.account.posts.edit', $clone->id)
            ->with('success', 'Post duplicated. You are now editing the copy.');
    }

    public function cloneContent(string $type, int $id)
    {
        $contentType = ContentType::where('name', $type)->where('is_system', false)->firstOrFail();
        $content     = Content::where('content_type_id', $contentType->id)
            ->with(['translations', 'fieldValues', 'terms'])
            ->find($id);

        if (! $content) {
            return redirect()->route('contensio.account.content.index', $type)->with('error', 'Entry not found.');
        }

        $clone = $this->performClone($content);

        return redirect()->route('contensio.account.content.edit', [$type, $clone->id])
            ->with('success', 'Entry duplicated. You are now editing the copy.');
    }

    private function performClone(Content $content): Content
    {
        $clone = Content::create([
            'code'              => Str::random(16),
            'content_type_id'   => $content->content_type_id,
            'author_id'         => auth()->id(),
            'status'            => 'draft',
            'blocks'            => $content->blocks,
            'featured_image_id' => $content->featured_image_id,
            'parent_id'         => $content->parent_id,
            'allow_comments'    => $content->allow_comments,
            'published_at'      => null,
        ]);

        foreach ($content->translations as $trans) {
            ContentTranslation::create([
                'content_id'       => $clone->id,
                'language_id'      => $trans->language_id,
                'title'            => $trans->title . ' (Copy)',
                'slug'             => $trans->slug . '-copy-' . Str::lower(Str::random(4)),
                'excerpt'          => $trans->excerpt,
                'meta_title'       => $trans->meta_title,
                'meta_description' => $trans->meta_description,
            ]);
        }

        foreach ($content->fieldValues as $fv) {
            ContentFieldValue::create([
                'content_id'  => $clone->id,
                'field_id'    => $fv->field_id,
                'language_id' => $fv->language_id,
                'value'       => $fv->value,
                'position'    => $fv->position,
            ]);
        }

        $clone->terms()->sync($content->terms->pluck('id'));

        do_action('contensio/content/created', $clone);

        return $clone;
    }

    // ─── Bulk actions ────────────────────────────────────────────────────────

    public function bulkPages(Request $request)
    {
        $type = ContentType::where('name', 'page')->firstOrFail();
        $this->performBulk(
            array_filter(array_map('intval', $request->input('ids', []))),
            (string) $request->input('action'),
            $type->id
        );
        return redirect()->route('contensio.account.pages.index')
            ->with('success', $this->bulkLabel($request->input('action'), 'pages'));
    }

    public function bulkPosts(Request $request)
    {
        $type = ContentType::where('name', 'post')->firstOrFail();
        $this->performBulk(
            array_filter(array_map('intval', $request->input('ids', []))),
            (string) $request->input('action'),
            $type->id
        );
        return redirect()->route('contensio.account.posts.index')
            ->with('success', $this->bulkLabel($request->input('action'), 'posts'));
    }

    public function bulkContent(Request $request, string $type)
    {
        $contentType = ContentType::where('name', $type)->where('is_system', false)->firstOrFail();
        $this->performBulk(
            array_filter(array_map('intval', $request->input('ids', []))),
            (string) $request->input('action'),
            $contentType->id
        );
        return redirect()->route('contensio.account.content.index', $type)
            ->with('success', $this->bulkLabel($request->input('action'), 'entries'));
    }

    private function performBulk(array $ids, string $action, int $typeId): void
    {
        if (empty($ids)) {
            return;
        }

        $items = Content::whereIn('id', $ids)->where('content_type_id', $typeId)->get();

        foreach ($items as $content) {
            $prevStatus = $content->status;

            match($action) {
                'publish' => $content->update(['status' => 'published', 'published_at' => $content->published_at ?? now()]),
                'draft'   => $content->update(['status' => 'draft']),
                'delete'  => null,
                default   => null,
            };

            if ($action === 'delete') {
                do_action('contensio/content/deleting', $content);
                $content->delete();
                do_action('contensio/content/deleted', $content->id, $content->contentType?->name ?? '');
            } else {
                do_action('contensio/content/updated', $content);
                if ($prevStatus !== $content->status) {
                    do_action('contensio/content/status-changed', $content, $prevStatus, $content->status);
                }
            }
        }
    }

    private function bulkLabel(string $action, string $noun): string
    {
        return match($action) {
            'publish' => ucfirst($noun) . ' published.',
            'draft'   => ucfirst($noun) . ' set to draft.',
            'delete'  => ucfirst($noun) . ' deleted.',
            default   => 'Done.',
        };
    }

    // ─── Helpers ─────────────────────────────────────────────────────────────

    private function editViewData(?Content $content, ContentType $type): array
    {
        $languages       = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defaultLanguage = Language::where('is_default', true)->first() ?? $languages->first();
        $defaultLangId   = $defaultLanguage?->id ?? 1;

        $existing = [];
        if ($content) {
            foreach ($content->translations as $trans) {
                $existing[$trans->language_id] = [
                    'title'            => $trans->title,
                    'slug'             => $trans->slug,
                    'excerpt'          => $trans->excerpt ?? '',
                    'meta_title'       => $trans->meta_title ?? '',
                    'meta_description' => $trans->meta_description ?? '',
                ];
            }
        }

        $selectedTermIds = $content ? $content->terms->pluck('id')->all() : [];

        // If the current user has an autosave for this content that is newer
        // than the content's last saved state, expose it so the edit view
        // can show a "restore" banner.
        $autosave = null;
        if ($content && auth()->check()) {
            $row = Autosave::where('content_id', $content->id)
                ->where('user_id', auth()->id())
                ->first();
            if ($row && (! $content->updated_at || $row->created_at->gt($content->updated_at))) {
                $autosave = [
                    'created_at' => $row->created_at->toIso8601String(),
                    'human'      => $row->created_at->diffForHumans(),
                    'data'       => $row->data,
                ];
            }
        }

        // Custom field groups attached to this content type, with fields + any
        // existing values (per language for translatable fields).
        $fieldGroups = $type->fieldGroups()
            ->with(['fields' => fn ($q) => $q->orderBy('position')->with('translations')])
            ->orderBy('field_group_attachments.position')
            ->get();

        $fieldValues = [];
        if ($content) {
            $rows = $content->fieldValues()->get(['field_id', 'language_id', 'value']);
            foreach ($rows as $row) {
                $key = $row->language_id ? $row->field_id . ':' . $row->language_id : $row->field_id . ':_';
                $fieldValues[$key] = $row->value;
            }
        }

        return [
            'languages'         => $languages,
            'defaultLanguage'   => $defaultLanguage,
            'defaultLangId'     => $defaultLangId,
            'multiLang'         => $languages->count() > 1,
            'taxonomies'        => $type->taxonomies,
            'existing'          => $existing,
            'selectedTermIds'   => $selectedTermIds,
            'autosave'          => $autosave,
            'fieldGroups'       => $fieldGroups,
            'fieldValues'       => $fieldValues,
            'workflowEnabled'   => WorkflowService::isEnabled(),
            'canApprove'        => WorkflowService::canApprove(auth()->user()),
            'canBypassReview'   => WorkflowService::canBypassReview(auth()->user()),
        ];
    }

    /**
     * Save autosave snapshot for the current user on this content item.
     * Called via fetch() from the edit view every few seconds while the
     * form is dirty. Idempotent — upserts on (content_id, user_id).
     */
    public function autosave(Request $request, int $id)
    {
        $content = Content::findOrFail($id);

        $data = $request->except(['_token', '_method']);

        $row = Autosave::updateOrCreate(
            ['content_id' => $content->id, 'user_id' => auth()->id()],
            ['data' => $data, 'created_at' => now()]
        );

        return response()->json([
            'ok'         => true,
            'created_at' => $row->created_at->toIso8601String(),
        ]);
    }

    /** Discard the current user's autosave for a content item. */
    public function discardAutosave(int $id)
    {
        Autosave::where('content_id', $id)
            ->where('user_id', auth()->id())
            ->delete();

        return response()->json(['ok' => true]);
    }

    /**
     * Delete the user's autosave for a content item after a real save.
     * Called from updatePage / updatePost / updateContent.
     */
    protected function clearAutosave(Content $content): void
    {
        if (auth()->check()) {
            Autosave::where('content_id', $content->id)
                ->where('user_id', auth()->id())
                ->delete();
        }
    }

    private function syncContent(Request $request, Content $content, $languages): void
    {
        $defaultLangId = Language::where('is_default', true)->value('id') ?? 1;

        // Featured image (only when the form includes the field)
        if ($request->has('featured_image_id')) {
            $content->featured_image_id = $request->filled('featured_image_id')
                ? (int) $request->input('featured_image_id')
                : null;
            $content->save();
        }

        // Allow comments toggle (only when the form includes the field)
        if ($request->has('allow_comments')) {
            $content->allow_comments = $request->boolean('allow_comments');
            $content->save();
        }

        // Collect term IDs from hierarchical checkboxes
        $allTermIds = array_map('intval', $request->input('term_ids', []));

        // Collect term IDs from Tagify inputs (flat taxonomies)
        // tagify[taxonomyId] = JSON string like [{"value":"Laravel","id":5},{"value":"New Tag"}]
        foreach ($request->input('tagify', []) as $taxonomyId => $tagsJson) {
            if (! $tagsJson) {
                continue;
            }

            $tags = json_decode($tagsJson, true) ?? [];

            foreach ($tags as $tag) {
                $termId = ! empty($tag['id']) ? (int) $tag['id'] : null;

                if ($termId) {
                    $allTermIds[] = $termId;
                } else {
                    // Tag typed manually (no id from Tagify) — find existing or create new
                    $name = trim($tag['value'] ?? '');
                    if (! $name) {
                        continue;
                    }

                    // Check for an existing term with this name in the same taxonomy
                    $existing = TermTranslation::where('language_id', $defaultLangId)
                        ->where('name', $name)
                        ->whereHas('term', fn ($q) => $q->where('taxonomy_id', (int) $taxonomyId))
                        ->first();

                    if ($existing) {
                        $allTermIds[] = $existing->term_id;
                        continue;
                    }

                    $slug = Str::slug($name) ?: Str::random(12);

                    $term = Term::create([
                        'code'        => Str::random(16),
                        'taxonomy_id' => (int) $taxonomyId,
                        'parent_id'   => null,
                        'position'    => (Term::where('taxonomy_id', $taxonomyId)->max('position') ?? 0) + 1,
                    ]);

                    TermTranslation::create([
                        'term_id'     => $term->id,
                        'language_id' => $defaultLangId,
                        'name'        => $name,
                        'slug'        => $slug,
                        'description' => null,
                    ]);

                    $allTermIds[] = $term->id;
                }
            }
        }

        $content->terms()->sync($allTermIds);

        // Save/update translations per language
        foreach ($languages as $lang) {
            $title   = $request->input("translations.{$lang->id}.title");
            $slug    = $request->input("translations.{$lang->id}.slug");
            $excerpt = $request->input("translations.{$lang->id}.excerpt");

            if (! $title) {
                continue;
            }

            ContentTranslation::updateOrCreate(
                ['content_id' => $content->id, 'language_id' => $lang->id],
                [
                    'title'            => $title,
                    'slug'             => $slug ?: Str::slug($title),
                    'excerpt'          => $excerpt ?: null,
                    'meta_title'       => $request->input("translations.{$lang->id}.meta_title") ?: null,
                    'meta_description' => $request->input("translations.{$lang->id}.meta_description") ?: null,
                ]
            );
        }

        // Custom field values — accepts "fields" array from the edit form.
        $this->syncFieldValues($request, $content);
    }

    /**
     * Persist submitted custom-field values. Shape of `fields` request data:
     *   fields[{id}]              = "value"                (non-translatable, scalar)
     *   fields[{id}][]            = [...]                  (non-translatable, multi-select)
     *   fields[{id}][{language}]  = "value"                (translatable, scalar)
     *   fields[{id}][{language}][]= [...]                  (translatable, multi-select)
     *
     * Only fields belonging to groups attached to the content's type are
     * persisted — anti-tamper check on field_id.
     */
    private function syncFieldValues(Request $request, Content $content): void
    {
        $payload = (array) $request->input('fields', []);
        if (empty($payload)) return;

        // Whitelist: fields reachable from this content's type via attached groups
        $validFieldIds = \Contensio\Models\Field::query()
            ->whereHas('group.contentTypes', fn ($q) => $q->where('content_types.id', $content->content_type_id))
            ->pluck('id')
            ->flip(); // for O(1) isset checks

        foreach ($payload as $fieldId => $submitted) {
            if (! isset($validFieldIds[(int) $fieldId])) continue;

            $field = \Contensio\Models\Field::find($fieldId);
            if (! $field) continue;

            $cfg     = $field->config ?? [];
            $isMulti = in_array($field->type, ['multi-select'], true)
                    || ($field->type === 'media' && ! empty($cfg['multiple']));

            if ($field->is_translatable && is_array($submitted)) {
                foreach ($submitted as $langId => $value) {
                    $saveValue = $isMulti ? json_encode(array_values((array) $value)) : (string) ($value ?? '');
                    \Contensio\Models\ContentFieldValue::updateOrCreate(
                        [
                            'content_id'  => $content->id,
                            'field_id'    => (int) $fieldId,
                            'language_id' => (int) $langId,
                        ],
                        ['value' => $saveValue, 'position' => 0]
                    );
                }
            } else {
                $saveValue = $isMulti ? json_encode(array_values((array) $submitted)) : (string) (is_array($submitted) ? '' : $submitted);
                \Contensio\Models\ContentFieldValue::updateOrCreate(
                    [
                        'content_id'  => $content->id,
                        'field_id'    => (int) $fieldId,
                        'language_id' => null,
                    ],
                    ['value' => $saveValue, 'position' => 0]
                );
            }
        }
    }

    /**
     * Resolve the published_at timestamp from the request.
     * - published  → keep existing date if already published, otherwise now()
     * - scheduled  → use the submitted publish_at datetime
     * - draft      → null
     */
    private function resolvePublishedAt(Request $request, ?Content $existing): mixed
    {
        return match($request->status) {
            'published' => ($existing?->status === 'published' && $existing->published_at)
                ? $existing->published_at
                : now(),
            'scheduled' => $request->filled('publish_at')
                ? $request->input('publish_at')
                : now()->addHour()->toDateTimeString(),
            default => null,
        };
    }

    private function defaultLangId($languages): int
    {
        $default = Language::where('is_default', true)->first() ?? $languages->first();
        return $default?->id ?? 1;
    }

    /**
     * When the approval workflow is active and the user cannot bypass review,
     * force the content status to 'draft' regardless of what the form submitted.
     * Returns true when the caller should restrict publish controls.
     */
    private function enforceWorkflowStatus(Request $request): bool
    {
        if (WorkflowService::isEnabled() && ! WorkflowService::canBypassReview(auth()->user())) {
            $request->merge(['status' => 'draft']);
            return true;
        }
        return false;
    }

    /**
     * After the regular content save, check if the author clicked
     * "Submit for Review". If so, mark as pending and notify reviewers.
     * Returns a redirect response when the submit action was handled, or null.
     */
    private function handleSubmitForReview(Request $request, Content $content, string $redirectRoute, ...$routeParams): ?\Illuminate\Http\RedirectResponse
    {
        if (! WorkflowService::isEnabled()) {
            return null;
        }
        if (WorkflowService::canBypassReview(auth()->user())) {
            return null;
        }
        if ($request->input('_review_action') !== 'submit_review') {
            return null;
        }
        if (! $content->canBeSubmittedForReview()) {
            return null;
        }

        $content->update([
            'review_status'       => Content::REVIEW_PENDING,
            'review_requested_at' => now(),
        ]);

        ReviewController::notifyReviewers(
            $content->loadMissing(['translations', 'contentType', 'author'])
        );

        return redirect()->route($redirectRoute, $routeParams)
            ->with('success', 'Submitted for review.');
    }
}
