<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Cms\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Str;
use Contensio\Cms\Models\Autosave;
use Contensio\Cms\Models\BlockType;
use Contensio\Cms\Support\Activity;
use Contensio\Cms\Models\Content;
use Contensio\Cms\Models\ContentTranslation;
use Contensio\Cms\Models\ContentType;
use Contensio\Cms\Models\Language;
use Contensio\Cms\Models\Term;
use Contensio\Cms\Models\TermTranslation;

class ContentController extends Controller
{
    // ─── Pages ───────────────────────────────────────────────────────────────

    public function pages()
    {
        $type  = ContentType::where('name', 'page')->first();
        $items = $type
            ? Content::where('content_type_id', $type->id)->with(['translations', 'author'])->latest()->get()
            : collect();

        return view('cms::admin.pages.index', compact('items'));
    }

    public function createPage()
    {
        $type = ContentType::where('name', 'page')
            ->with(['taxonomies.translations', 'taxonomies.terms.translations'])
            ->firstOrFail();

        $blockTypes = BlockType::active()->ordered()->get();

        return view('cms::admin.content.edit', array_merge(
            $this->editViewData(null, $type),
            [
                'content'    => null,
                'type'       => $type,
                'blockTypes' => $blockTypes,
                'backRoute'  => route('cms.admin.pages.index'),
                'storeRoute' => route('cms.admin.pages.store'),
                'method'     => 'POST',
            ]
        ));
    }

    public function storePage(Request $request)
    {
        $type      = ContentType::where('name', 'page')->firstOrFail();
        $languages = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defLangId = $this->defaultLangId($languages);

        $request->validate([
            "translations.{$defLangId}.title" => 'required|string|max:500',
            "translations.{$defLangId}.slug"  => 'nullable|string|max:500',
            'status'                           => 'required|in:draft,published',
        ]);

        $content = Content::create([
            'code'            => Str::random(16),
            'content_type_id' => $type->id,
            'author_id'       => auth()->id(),
            'status'          => $request->status,
            'blocks'          => [],
            'published_at'    => $request->status === 'published' ? now() : null,
        ]);

        $this->syncContent($request, $content, $languages);

        Activity::record(
            $request->status === 'published' ? 'published' : 'created',
            'content',
            $content->id,
            'Page: ' . $request->input("translations.{$defLangId}.title")
        )->withProperties(['type' => 'page', 'status' => $content->status]);

        return redirect()->route('cms.admin.pages.edit', $content->id)
            ->with('success', 'Page created.');
    }

    public function editPage(int $id)
    {
        $type = ContentType::where('name', 'page')
            ->with(['taxonomies.translations', 'taxonomies.terms.translations'])
            ->firstOrFail();

        $content = Content::where('content_type_id', $type->id)
            ->with(['translations', 'author', 'terms'])
            ->find($id);

        if (! $content) {
            return redirect()->route('cms.admin.pages.index')->with('error', 'Page not found.');
        }

        $blockTypes = BlockType::active()->ordered()->get();

        return view('cms::admin.content.edit', array_merge(
            $this->editViewData($content, $type),
            [
                'content'    => $content,
                'type'       => $type,
                'blockTypes' => $blockTypes,
                'backRoute'  => route('cms.admin.pages.index'),
                'storeRoute' => route('cms.admin.pages.update', $id),
                'method'     => 'PUT',
            ]
        ));
    }

    public function updatePage(Request $request, int $id)
    {
        $type    = ContentType::where('name', 'page')->firstOrFail();
        $content = Content::where('content_type_id', $type->id)->find($id);

        if (! $content) {
            return redirect()->route('cms.admin.pages.index')->with('error', 'Page not found.');
        }

        $languages = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defLangId = $this->defaultLangId($languages);

        $request->validate([
            "translations.{$defLangId}.title" => 'required|string|max:500',
            "translations.{$defLangId}.slug"  => 'nullable|string|max:500',
            'status'                           => 'required|in:draft,published',
        ]);

        $prevStatus = $content->status;

        $content->update([
            'status'       => $request->status,
            'published_at' => $request->status === 'published' && ! $content->published_at
                ? now() : $content->published_at,
        ]);

        $this->syncContent($request, $content, $languages);
        $this->clearAutosave($content);

        $verb = ($prevStatus !== 'published' && $request->status === 'published') ? 'published' : 'updated';
        Activity::record($verb, 'content', $content->id,
            'Page: ' . $request->input("translations.{$defLangId}.title")
        )->withProperties(['type' => 'page', 'status' => $content->status]);

        return redirect()->route('cms.admin.pages.edit', $id)->with('success', 'Page saved.');
    }

    public function destroyPage(int $id)
    {
        $type    = ContentType::where('name', 'page')->firstOrFail();
        $content = Content::where('content_type_id', $type->id)->find($id);

        if (! $content) {
            return redirect()->route('cms.admin.pages.index');
        }

        $title = $content->translations()->value('title');
        $content->delete();

        Activity::record('deleted', 'content', $id, "Page: {$title}")
            ->withProperties(['type' => 'page']);

        return redirect()->route('cms.admin.pages.index')->with('success', 'Page deleted.');
    }

    // ─── Posts ────────────────────────────────────────────────────────────────

    public function posts()
    {
        $type  = ContentType::where('name', 'post')->first();
        $items = $type
            ? Content::where('content_type_id', $type->id)->with(['translations', 'author'])->latest()->get()
            : collect();

        return view('cms::admin.posts.index', compact('items'));
    }

    public function createPost()
    {
        $type = ContentType::where('name', 'post')
            ->with(['taxonomies.translations', 'taxonomies.terms.translations'])
            ->firstOrFail();

        $blockTypes = BlockType::active()->ordered()->get();

        return view('cms::admin.content.edit', array_merge(
            $this->editViewData(null, $type),
            [
                'content'    => null,
                'type'       => $type,
                'blockTypes' => $blockTypes,
                'backRoute'  => route('cms.admin.posts.index'),
                'storeRoute' => route('cms.admin.posts.store'),
                'method'     => 'POST',
            ]
        ));
    }

    public function storePost(Request $request)
    {
        $type      = ContentType::where('name', 'post')->firstOrFail();
        $languages = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defLangId = $this->defaultLangId($languages);

        $request->validate([
            "translations.{$defLangId}.title" => 'required|string|max:500',
            "translations.{$defLangId}.slug"  => 'nullable|string|max:500',
            'status'                           => 'required|in:draft,published',
        ]);

        $content = Content::create([
            'code'            => Str::random(16),
            'content_type_id' => $type->id,
            'author_id'       => auth()->id(),
            'status'          => $request->status,
            'blocks'          => [],
            'published_at'    => $request->status === 'published' ? now() : null,
        ]);

        $this->syncContent($request, $content, $languages);

        Activity::record(
            $request->status === 'published' ? 'published' : 'created',
            'content',
            $content->id,
            'Post: ' . $request->input("translations.{$defLangId}.title")
        )->withProperties(['type' => 'post', 'status' => $content->status]);

        return redirect()->route('cms.admin.posts.edit', $content->id)
            ->with('success', 'Post created.');
    }

    public function editPost(int $id)
    {
        $type = ContentType::where('name', 'post')
            ->with(['taxonomies.translations', 'taxonomies.terms.translations'])
            ->firstOrFail();

        $content = Content::where('content_type_id', $type->id)
            ->with(['translations', 'author', 'terms'])
            ->find($id);

        if (! $content) {
            return redirect()->route('cms.admin.posts.index')->with('error', 'Post not found.');
        }

        $blockTypes = BlockType::active()->ordered()->get();

        return view('cms::admin.content.edit', array_merge(
            $this->editViewData($content, $type),
            [
                'content'    => $content,
                'type'       => $type,
                'blockTypes' => $blockTypes,
                'backRoute'  => route('cms.admin.posts.index'),
                'storeRoute' => route('cms.admin.posts.update', $id),
                'method'     => 'PUT',
            ]
        ));
    }

    public function updatePost(Request $request, int $id)
    {
        $type    = ContentType::where('name', 'post')->firstOrFail();
        $content = Content::where('content_type_id', $type->id)->find($id);

        if (! $content) {
            return redirect()->route('cms.admin.posts.index')->with('error', 'Post not found.');
        }

        $languages = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defLangId = $this->defaultLangId($languages);

        $request->validate([
            "translations.{$defLangId}.title" => 'required|string|max:500',
            "translations.{$defLangId}.slug"  => 'nullable|string|max:500',
            'status'                           => 'required|in:draft,published',
        ]);

        $prevStatus = $content->status;

        $content->update([
            'status'       => $request->status,
            'published_at' => $request->status === 'published' && ! $content->published_at
                ? now() : $content->published_at,
        ]);

        $this->syncContent($request, $content, $languages);
        $this->clearAutosave($content);

        $verb = ($prevStatus !== 'published' && $request->status === 'published') ? 'published' : 'updated';
        Activity::record($verb, 'content', $content->id,
            'Post: ' . $request->input("translations.{$defLangId}.title")
        )->withProperties(['type' => 'post', 'status' => $content->status]);

        return redirect()->route('cms.admin.posts.edit', $id)->with('success', 'Post saved.');
    }

    public function destroyPost(int $id)
    {
        $type    = ContentType::where('name', 'post')->firstOrFail();
        $content = Content::where('content_type_id', $type->id)->find($id);

        if (! $content) {
            return redirect()->route('cms.admin.posts.index');
        }

        $title = $content->translations()->value('title');
        $content->delete();

        Activity::record('deleted', 'content', $id, "Post: {$title}")
            ->withProperties(['type' => 'post']);

        return redirect()->route('cms.admin.posts.index')->with('success', 'Post deleted.');
    }

    // ─── Custom content types ─────────────────────────────────────────────────

    public function indexContent(string $type)
    {
        $contentType = ContentType::where('name', $type)->where('is_system', false)->firstOrFail();
        $items       = Content::where('content_type_id', $contentType->id)
            ->with(['translations', 'author'])
            ->latest()
            ->get();

        $trans  = $contentType->translations->first();
        $plural = $trans?->labels['plural'] ?? ucfirst($type);

        return view('cms::admin.content.index', compact('contentType', 'items', 'plural', 'type'));
    }

    public function createContent(string $type)
    {
        $contentType = ContentType::where('name', $type)->where('is_system', false)
            ->with(['taxonomies.translations', 'taxonomies.terms.translations'])
            ->firstOrFail();

        $blockTypes = BlockType::active()->ordered()->get();

        return view('cms::admin.content.edit', array_merge(
            $this->editViewData(null, $contentType),
            [
                'content'    => null,
                'type'       => $contentType,
                'blockTypes' => $blockTypes,
                'backRoute'  => route('cms.admin.content.index', $type),
                'storeRoute' => route('cms.admin.content.store', $type),
                'method'     => 'POST',
            ]
        ));
    }

    public function storeContent(Request $request, string $type)
    {
        $contentType = ContentType::where('name', $type)->where('is_system', false)->firstOrFail();
        $languages   = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defLangId   = $this->defaultLangId($languages);

        $request->validate([
            "translations.{$defLangId}.title" => 'required|string|max:500',
            "translations.{$defLangId}.slug"  => 'nullable|string|max:500',
            'status'                           => 'required|in:draft,published',
        ]);

        $content = Content::create([
            'code'            => Str::random(16),
            'content_type_id' => $contentType->id,
            'author_id'       => auth()->id(),
            'status'          => $request->status,
            'blocks'          => [],
            'published_at'    => $request->status === 'published' ? now() : null,
        ]);

        $this->syncContent($request, $content, $languages);

        return redirect()->route('cms.admin.content.edit', [$type, $content->id])
            ->with('success', 'Entry created.');
    }

    public function editContent(string $type, int $id)
    {
        $contentType = ContentType::where('name', $type)->where('is_system', false)
            ->with(['taxonomies.translations', 'taxonomies.terms.translations'])
            ->firstOrFail();

        $content = Content::where('content_type_id', $contentType->id)
            ->with(['translations', 'author', 'terms'])
            ->find($id);

        if (! $content) {
            return redirect()->route('cms.admin.content.index', $type)->with('error', 'Entry not found.');
        }

        $blockTypes = BlockType::active()->ordered()->get();

        return view('cms::admin.content.edit', array_merge(
            $this->editViewData($content, $contentType),
            [
                'content'    => $content,
                'type'       => $contentType,
                'blockTypes' => $blockTypes,
                'backRoute'  => route('cms.admin.content.index', $type),
                'storeRoute' => route('cms.admin.content.update', [$type, $id]),
                'method'     => 'PUT',
            ]
        ));
    }

    public function updateContent(Request $request, string $type, int $id)
    {
        $contentType = ContentType::where('name', $type)->where('is_system', false)->firstOrFail();
        $content     = Content::where('content_type_id', $contentType->id)->find($id);

        if (! $content) {
            return redirect()->route('cms.admin.content.index', $type)->with('error', 'Entry not found.');
        }

        $languages = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defLangId = $this->defaultLangId($languages);

        $request->validate([
            "translations.{$defLangId}.title" => 'required|string|max:500',
            "translations.{$defLangId}.slug"  => 'nullable|string|max:500',
            'status'                           => 'required|in:draft,published',
        ]);

        $content->update([
            'status'       => $request->status,
            'published_at' => $request->status === 'published' && ! $content->published_at
                ? now() : $content->published_at,
        ]);

        $this->syncContent($request, $content, $languages);
        $this->clearAutosave($content);

        return redirect()->route('cms.admin.content.edit', [$type, $id])->with('success', 'Entry saved.');
    }

    public function destroyContent(string $type, int $id)
    {
        $contentType = ContentType::where('name', $type)->where('is_system', false)->firstOrFail();
        $content     = Content::where('content_type_id', $contentType->id)->find($id);

        if ($content) {
            $content->delete();
        }

        return redirect()->route('cms.admin.content.index', $type)->with('success', 'Entry deleted.');
    }

    // ─── Helpers ─────────────────────────────────────────────────────────────

    private function editViewData(?Content $content, ContentType $type): array
    {
        $languages       = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defaultLanguage = Language::where('is_default', true)->first() ?? $languages->first();
        $defaultLangId   = $defaultLanguage?->id ?? 1;

        $existing = [];
        if ($content) {
            foreach ($content->translations as $trans) {
                $existing[$trans->language_id] = [
                    'title'            => $trans->title,
                    'slug'             => $trans->slug,
                    'excerpt'          => $trans->excerpt ?? '',
                    'meta_title'       => $trans->meta_title ?? '',
                    'meta_description' => $trans->meta_description ?? '',
                ];
            }
        }

        $selectedTermIds = $content ? $content->terms->pluck('id')->all() : [];

        // If the current user has an autosave for this content that is newer
        // than the content's last saved state, expose it so the edit view
        // can show a "restore" banner.
        $autosave = null;
        if ($content && auth()->check()) {
            $row = Autosave::where('content_id', $content->id)
                ->where('user_id', auth()->id())
                ->first();
            if ($row && (! $content->updated_at || $row->created_at->gt($content->updated_at))) {
                $autosave = [
                    'created_at' => $row->created_at->toIso8601String(),
                    'human'      => $row->created_at->diffForHumans(),
                    'data'       => $row->data,
                ];
            }
        }

        // Custom field groups attached to this content type, with fields + any
        // existing values (per language for translatable fields).
        $fieldGroups = $type->fieldGroups()
            ->with(['fields' => fn ($q) => $q->orderBy('position')->with('translations')])
            ->orderBy('field_group_attachments.position')
            ->get();

        $fieldValues = [];
        if ($content) {
            $rows = $content->fieldValues()->get(['field_id', 'language_id', 'value']);
            foreach ($rows as $row) {
                $key = $row->language_id ? $row->field_id . ':' . $row->language_id : $row->field_id . ':_';
                $fieldValues[$key] = $row->value;
            }
        }

        return [
            'languages'       => $languages,
            'defaultLanguage' => $defaultLanguage,
            'defaultLangId'   => $defaultLangId,
            'multiLang'       => $languages->count() > 1,
            'taxonomies'      => $type->taxonomies,
            'existing'        => $existing,
            'selectedTermIds' => $selectedTermIds,
            'autosave'        => $autosave,
            'fieldGroups'     => $fieldGroups,
            'fieldValues'     => $fieldValues,
        ];
    }

    /**
     * Save autosave snapshot for the current user on this content item.
     * Called via fetch() from the edit view every few seconds while the
     * form is dirty. Idempotent — upserts on (content_id, user_id).
     */
    public function autosave(Request $request, int $id)
    {
        $content = Content::findOrFail($id);

        $data = $request->except(['_token', '_method']);

        $row = Autosave::updateOrCreate(
            ['content_id' => $content->id, 'user_id' => auth()->id()],
            ['data' => $data, 'created_at' => now()]
        );

        return response()->json([
            'ok'         => true,
            'created_at' => $row->created_at->toIso8601String(),
        ]);
    }

    /** Discard the current user's autosave for a content item. */
    public function discardAutosave(int $id)
    {
        Autosave::where('content_id', $id)
            ->where('user_id', auth()->id())
            ->delete();

        return response()->json(['ok' => true]);
    }

    /**
     * Delete the user's autosave for a content item after a real save.
     * Called from updatePage / updatePost / updateContent.
     */
    protected function clearAutosave(Content $content): void
    {
        if (auth()->check()) {
            Autosave::where('content_id', $content->id)
                ->where('user_id', auth()->id())
                ->delete();
        }
    }

    private function syncContent(Request $request, Content $content, $languages): void
    {
        $defaultLangId = Language::where('is_default', true)->value('id') ?? 1;

        // Collect term IDs from hierarchical checkboxes
        $allTermIds = array_map('intval', $request->input('term_ids', []));

        // Collect term IDs from Tagify inputs (flat taxonomies)
        // tagify[taxonomyId] = JSON string like [{"value":"Laravel","id":5},{"value":"New Tag"}]
        foreach ($request->input('tagify', []) as $taxonomyId => $tagsJson) {
            if (! $tagsJson) {
                continue;
            }

            $tags = json_decode($tagsJson, true) ?? [];

            foreach ($tags as $tag) {
                $termId = ! empty($tag['id']) ? (int) $tag['id'] : null;

                if ($termId) {
                    $allTermIds[] = $termId;
                } else {
                    // New tag typed by the user — create term + default-language translation
                    $name = trim($tag['value'] ?? '');
                    if (! $name) {
                        continue;
                    }

                    $slug = Str::slug($name) ?: Str::random(12);

                    $term = Term::create([
                        'code'        => Str::random(16),
                        'taxonomy_id' => (int) $taxonomyId,
                        'parent_id'   => null,
                        'position'    => (Term::where('taxonomy_id', $taxonomyId)->max('position') ?? 0) + 1,
                    ]);

                    TermTranslation::create([
                        'term_id'     => $term->id,
                        'language_id' => $defaultLangId,
                        'name'        => $name,
                        'slug'        => $slug,
                        'description' => null,
                    ]);

                    $allTermIds[] = $term->id;
                }
            }
        }

        $content->terms()->sync($allTermIds);

        // Save/update translations per language
        foreach ($languages as $lang) {
            $title   = $request->input("translations.{$lang->id}.title");
            $slug    = $request->input("translations.{$lang->id}.slug");
            $excerpt = $request->input("translations.{$lang->id}.excerpt");

            if (! $title) {
                continue;
            }

            ContentTranslation::updateOrCreate(
                ['content_id' => $content->id, 'language_id' => $lang->id],
                [
                    'title'            => $title,
                    'slug'             => $slug ?: Str::slug($title),
                    'excerpt'          => $excerpt ?: null,
                    'meta_title'       => $request->input("translations.{$lang->id}.meta_title") ?: null,
                    'meta_description' => $request->input("translations.{$lang->id}.meta_description") ?: null,
                ]
            );
        }

        // Custom field values — accepts "fields" array from the edit form.
        $this->syncFieldValues($request, $content);
    }

    /**
     * Persist submitted custom-field values. Shape of `fields` request data:
     *   fields[{id}]              = "value"                (non-translatable, scalar)
     *   fields[{id}][]            = [...]                  (non-translatable, multi-select)
     *   fields[{id}][{language}]  = "value"                (translatable, scalar)
     *   fields[{id}][{language}][]= [...]                  (translatable, multi-select)
     *
     * Only fields belonging to groups attached to the content's type are
     * persisted — anti-tamper check on field_id.
     */
    private function syncFieldValues(Request $request, Content $content): void
    {
        $payload = (array) $request->input('fields', []);
        if (empty($payload)) return;

        // Whitelist: fields reachable from this content's type via attached groups
        $validFieldIds = \Contensio\Cms\Models\Field::query()
            ->whereHas('group.contentTypes', fn ($q) => $q->where('content_types.id', $content->content_type_id))
            ->pluck('id')
            ->flip(); // for O(1) isset checks

        foreach ($payload as $fieldId => $submitted) {
            if (! isset($validFieldIds[(int) $fieldId])) continue;

            $field = \Contensio\Cms\Models\Field::find($fieldId);
            if (! $field) continue;

            $cfg     = $field->config ?? [];
            $isMulti = in_array($field->type, ['multi-select'], true)
                    || ($field->type === 'media' && ! empty($cfg['multiple']));

            if ($field->is_translatable && is_array($submitted)) {
                foreach ($submitted as $langId => $value) {
                    $saveValue = $isMulti ? json_encode(array_values((array) $value)) : (string) ($value ?? '');
                    \Contensio\Cms\Models\ContentFieldValue::updateOrCreate(
                        [
                            'content_id'  => $content->id,
                            'field_id'    => (int) $fieldId,
                            'language_id' => (int) $langId,
                        ],
                        ['value' => $saveValue, 'position' => 0]
                    );
                }
            } else {
                $saveValue = $isMulti ? json_encode(array_values((array) $submitted)) : (string) (is_array($submitted) ? '' : $submitted);
                \Contensio\Cms\Models\ContentFieldValue::updateOrCreate(
                    [
                        'content_id'  => $content->id,
                        'field_id'    => (int) $fieldId,
                        'language_id' => null,
                    ],
                    ['value' => $saveValue, 'position' => 0]
                );
            }
        }
    }

    private function defaultLangId($languages): int
    {
        $default = Language::where('is_default', true)->first() ?? $languages->first();
        return $default?->id ?? 1;
    }
}
