<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Cms\Http\Controllers\Admin;

use Illuminate\Routing\Controller;
use Contensio\Cms\Models\ActivityLog;
use Contensio\Cms\Models\Comment;
use Contensio\Cms\Models\Content;
use Contensio\Cms\Models\Media;

class DashboardController extends Controller
{
    public function index()
    {
        $stats = [
            'contents'         => Content::count(),
            'media'            => Media::count(),
            'pending_comments' => Comment::where('status', Comment::STATUS_PENDING)->count(),
            'users'            => \App\Models\User::count(),
        ];

        $recentActivity = ActivityLog::with('user')
            ->latest('created_at')
            ->limit(10)
            ->get();

        $recentContent = Content::with(['contentType', 'author'])
            ->latest()
            ->limit(5)
            ->get();

        return view('cms::admin.dashboard', compact('stats', 'recentActivity', 'recentContent'));
    }
}
