<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Cms\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\DB;
use Contensio\Cms\Models\Language;

class LanguageController extends Controller
{
    public function index()
    {
        $languages = Language::orderBy('position')->orderBy('id')->get();

        return view('cms::admin.languages.index', compact('languages'));
    }

    public function create()
    {
        return view('cms::admin.languages.form', ['language' => null]);
    }

    public function store(Request $request)
    {
        $request->validate([
            'code'      => 'required|string|max:5|unique:languages,code',
            'name'      => 'required|string|max:50',
            'direction' => 'required|in:ltr,rtl',
            'status'    => 'required|in:active,inactive,disabled',
        ]);

        Language::create([
            'code'       => strtolower($request->code),
            'name'       => $request->name,
            'direction'  => $request->direction,
            'status'     => $request->status,
            'is_default' => false,
            'position'   => (Language::max('position') ?? 0) + 1,
        ]);

        return redirect()->route('cms.admin.languages.index')
            ->with('success', "Language \"{$request->name}\" added.");
    }

    public function edit(int $id)
    {
        $language = Language::find($id);

        if (! $language) {
            return redirect()->route('cms.admin.languages.index');
        }

        return view('cms::admin.languages.form', compact('language'));
    }

    public function update(Request $request, int $id)
    {
        $language = Language::find($id);

        if (! $language) {
            return redirect()->route('cms.admin.languages.index');
        }

        $request->validate([
            'name'      => 'required|string|max:50',
            'direction' => 'required|in:ltr,rtl',
            'status'    => 'required|in:active,inactive,disabled',
        ]);

        // Cannot disable the default language
        if ($language->is_default && $request->status === 'disabled') {
            return back()->withInput()
                ->withErrors(['status' => 'The default language cannot be disabled. Set another language as default first.']);
        }

        $language->update([
            'name'      => $request->name,
            'direction' => $request->direction,
            'status'    => $request->status,
        ]);

        return redirect()->route('cms.admin.languages.index')
            ->with('success', "Language \"{$request->name}\" saved.");
    }

    public function destroy(int $id)
    {
        $language = Language::find($id);

        if (! $language) {
            return redirect()->route('cms.admin.languages.index');
        }

        if ($language->is_default) {
            return redirect()->route('cms.admin.languages.index')
                ->with('error', 'Cannot delete the default language. Set another language as default first.');
        }

        $count = DB::table('content_translations')->where('language_id', $language->id)->count();

        if ($count > 0) {
            return redirect()->route('cms.admin.languages.index')
                ->with('error', "Cannot delete \"{$language->name}\" — it has {$count} content translation(s).");
        }

        $language->delete();

        return redirect()->route('cms.admin.languages.index')
            ->with('success', 'Language deleted.');
    }

    public function setDefault(int $id)
    {
        $language = Language::find($id);

        if (! $language) {
            return redirect()->route('cms.admin.languages.index');
        }

        Language::where('is_default', true)->update(['is_default' => false]);

        // Default language must be at least active
        $status = $language->status === 'disabled' ? 'active' : $language->status;
        $language->update(['is_default' => true, 'status' => $status]);

        return redirect()->route('cms.admin.languages.index')
            ->with('success', "\"{$language->name}\" is now the default language.");
    }
}
