<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Cms\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Contensio\Cms\Models\Media;

class MediaController extends Controller
{
    public function index()
    {
        $items = Media::latest()->paginate(48);

        return view('cms::admin.media.index', compact('items'));
    }

    public function upload(Request $request)
    {
        $request->validate([
            'files'   => 'required|array|min:1',
            'files.*' => 'required|file|max:20480', // 20 MB per file
        ]);

        $year   = date('Y');
        $month  = date('m');
        $folder = "uploads/{$year}/{$month}";

        foreach ($request->file('files') as $file) {
            $original = $file->getClientOriginalName();
            $ext      = strtolower($file->getClientOriginalExtension());
            $stored   = Str::uuid() . ($ext ? ".{$ext}" : '');

            $path     = Storage::disk('public')->putFileAs($folder, $file, $stored);

            $width = $height = null;
            if (str_starts_with($file->getMimeType(), 'image/')) {
                $size   = @getimagesize($file->getRealPath());
                $width  = $size[0] ?? null;
                $height = $size[1] ?? null;
            }

            Media::create([
                'code'      => Str::random(16),
                'user_id'   => auth()->id(),
                'file_name' => $original,
                'file_path' => $path,
                'disk'      => 'public',
                'mime_type' => $file->getMimeType(),
                'file_size' => $file->getSize(),
                'width'     => $width,
                'height'    => $height,
            ]);
        }

        return redirect()->route('cms.admin.media.index')
            ->with('success', 'Files uploaded successfully.');
    }

    public function destroy(int $id)
    {
        $media = Media::findOrFail($id);
        Storage::disk($media->disk)->delete($media->file_path);
        $media->delete();

        return redirect()->route('cms.admin.media.index')
            ->with('success', 'File deleted.');
    }
}
