<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Contensio\Jobs\ProcessMediaVariants;
use Contensio\Models\Media;

class MediaController extends Controller
{
    public function index()
    {
        $items = Media::latest()->paginate(48);

        return view('contensio::admin.media.index', compact('items'));
    }

    public function upload(Request $request)
    {
        $request->validate([
            'files'   => 'required|array|min:1',
            'files.*' => 'required|file|max:20480', // 20 MB per file
        ]);

        $year   = date('Y');
        $month  = date('m');
        $folder = "uploads/{$year}/{$month}";

        foreach ($request->file('files') as $file) {
            $original = $file->getClientOriginalName();
            $ext      = strtolower($file->getClientOriginalExtension());
            $stored   = Str::uuid() . ($ext ? ".{$ext}" : '');

            $path     = Storage::disk('public')->putFileAs($folder, $file, $stored);

            $width = $height = null;
            if (str_starts_with($file->getMimeType(), 'image/')) {
                $size   = @getimagesize($file->getRealPath());
                $width  = $size[0] ?? null;
                $height = $size[1] ?? null;
            }

            $media = Media::create([
                'code'      => Str::random(16),
                'user_id'   => auth()->id(),
                'file_name' => $original,
                'file_path' => $path,
                'disk'      => 'public',
                'mime_type' => $file->getMimeType(),
                'file_size' => $file->getSize(),
                'width'     => $width,
                'height'    => $height,
            ]);

            if ($media->isImage()) {
                ProcessMediaVariants::dispatch($media);
            }
        }

        return redirect()->route('contensio.account.media.index')
            ->with('success', 'Files uploaded successfully.');
    }

    public function destroy(int $id)
    {
        $media = Media::with('variants')->findOrFail($id);

        // Delete all variant files before removing the original
        foreach ($media->variants as $variant) {
            Storage::disk($media->disk)->delete($variant->path);
        }

        Storage::disk($media->disk)->delete($media->file_path);
        $media->delete(); // variants cascade via FK

        return redirect()->route('contensio.account.media.index')
            ->with('success', 'File deleted.');
    }

    /**
     * JSON endpoint for the Media Library picker modal.
     * Returns paginated media items with optional MIME filter + search.
     *
     *   GET /admin/media/pick?q=hero&mime=image%2F&page=2
     */
    public function pick(Request $request)
    {
        $q    = trim((string) $request->input('q', ''));
        $mime = trim((string) $request->input('mime', '')); // e.g. "image/"

        $items = Media::query()
            ->when($q,    fn ($qb) => $qb->where('file_name', 'like', "%{$q}%"))
            ->when($mime, fn ($qb) => $qb->where('mime_type', 'like', "{$mime}%"))
            ->latest()
            ->paginate(36);

        return response()->json([
            'items' => $items->map(fn (Media $m) => $this->mediaAsJson($m))->values(),
            'page'  => $items->currentPage(),
            'pages' => $items->lastPage(),
            'total' => $items->total(),
        ]);
    }

    /**
     * JSON upload endpoint for the picker. Single-file upload, returns the
     * newly-created media item in the same shape as pick().
     */
    public function pickUpload(Request $request)
    {
        $request->validate([
            'file' => 'required|file|max:20480',
        ]);

        $file   = $request->file('file');
        $year   = date('Y');
        $month  = date('m');
        $folder = "uploads/{$year}/{$month}";

        $original = $file->getClientOriginalName();
        $ext      = strtolower($file->getClientOriginalExtension());
        $stored   = Str::uuid() . ($ext ? ".{$ext}" : '');
        $path     = Storage::disk('public')->putFileAs($folder, $file, $stored);

        $width = $height = null;
        if (str_starts_with($file->getMimeType(), 'image/')) {
            $size   = @getimagesize($file->getRealPath());
            $width  = $size[0] ?? null;
            $height = $size[1] ?? null;
        }

        $media = Media::create([
            'code'      => Str::random(16),
            'user_id'   => auth()->id(),
            'file_name' => $original,
            'file_path' => $path,
            'disk'      => 'public',
            'mime_type' => $file->getMimeType(),
            'file_size' => $file->getSize(),
            'width'     => $width,
            'height'    => $height,
        ]);

        if ($media->isImage()) {
            ProcessMediaVariants::dispatch($media);
        }

        return response()->json(['item' => $this->mediaAsJson($media)]);
    }

    protected function mediaAsJson(Media $m): array
    {
        return [
            'id'        => $m->id,
            'file_name' => $m->file_name,
            'url'       => Storage::disk($m->disk)->url($m->file_path),
            'mime_type' => $m->mime_type,
            'file_size' => $m->file_size,
            'width'     => $m->width,
            'height'    => $m->height,
            'is_image'  => str_starts_with((string) $m->mime_type, 'image/'),
        ];
    }
}
