<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Cms\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Contensio\Cms\Models\Content;
use Contensio\Cms\Models\ContentType;
use Contensio\Cms\Models\Language;
use Contensio\Cms\Models\Menu;
use Contensio\Cms\Models\MenuItem;
use Contensio\Cms\Models\MenuItemTranslation;
use Contensio\Cms\Models\MenuLocation;
use Contensio\Cms\Models\MenuTranslation;
use Contensio\Cms\Models\Taxonomy;
use Contensio\Cms\Models\Term;
use Contensio\Cms\Support\ThemeRegistry;

class MenuController extends Controller
{
    public function index()
    {
        $languages = Language::notDisabled()->orderBy('position')->get();
        $defaultLangId = $languages->firstWhere('is_default', true)?->id ?? $languages->first()?->id;

        $menus = Menu::with(['translations', 'locations', 'allItems'])->orderBy('name')->get();

        return view('cms::admin.menus.index', compact('menus', 'languages', 'defaultLangId'));
    }

    public function store(Request $request)
    {
        $data = $request->validate([
            'label' => ['required', 'string', 'max:100'],
        ]);

        $menu = Menu::create([
            'name' => $this->uniqueSlug($data['label']),
        ]);

        // Populate translations for every language with the same label.
        // Admin exposes one "Menu name" field; items carry the frontend-visible,
        // per-language labels.
        foreach (Language::notDisabled()->get() as $lang) {
            MenuTranslation::create([
                'menu_id'     => $menu->id,
                'language_id' => $lang->id,
                'label'       => $data['label'],
            ]);
        }

        return redirect()->route('cms.admin.menus.edit', $menu->id)
            ->with('success', 'Menu created. Now add some items to it.');
    }

    public function edit(int $id)
    {
        $menu = Menu::with([
            'translations',
            'locations',
            'allItems.translations',
        ])->findOrFail($id);

        $languages = Language::notDisabled()->orderBy('position')->get();
        $defaultLangId = $languages->firstWhere('is_default', true)?->id ?? $languages->first()?->id;

        // Items, flat list ordered by position (parent grouping done in the view)
        $items = $menu->allItems->sortBy('position')->values();

        // For the item source pickers
        $pages = $this->contentOptions('page');
        $posts = $this->contentOptions('post');
        $terms = Term::with('translations')->get()->mapWithKeys(function ($t) use ($defaultLangId) {
            $tr = $t->translations->firstWhere('language_id', $defaultLangId) ?? $t->translations->first();
            return [$t->id => $tr?->name ?? ('Term #' . $t->id)];
        });

        // Theme-declared locations
        $themeLocations   = $this->themeLocations();
        $assignedLocations = $menu->locations->pluck('menu_id', 'location')->map(fn () => true)->toArray();
        // Which locations are currently assigned to THIS menu (keyed by location key)
        $myAssignments = MenuLocation::where('menu_id', $menu->id)->pluck('location')->toArray();

        return view('cms::admin.menus.edit', compact(
            'menu', 'items', 'languages', 'defaultLangId',
            'pages', 'posts', 'terms', 'themeLocations', 'myAssignments'
        ));
    }

    public function update(Request $request, int $id)
    {
        $menu = Menu::findOrFail($id);

        $data = $request->validate([
            'label'                                    => ['required', 'string', 'max:100'],
            'items'                                    => ['array'],
            'items.*.id'                               => ['nullable', 'integer'],
            'items.*.type'                             => ['required', 'string', 'in:page,post,content,term,custom_url'],
            'items.*.reference_id'                     => ['nullable', 'integer'],
            'items.*.parent_id'                        => ['nullable', 'integer'],
            'items.*.position'                         => ['nullable', 'integer'],
            'items.*.target'                           => ['required', 'string', 'in:_self,_blank'],
            'items.*.icon'                             => ['nullable', 'string', 'max:100'],
            'items.*.is_active'                        => ['nullable'],
            'items.*.translations'                     => ['array'],
            'items.*.translations.*.label'             => ['nullable', 'string', 'max:255'],
            'items.*.translations.*.url'               => ['nullable', 'string', 'max:500'],
            'locations'                                => ['array'],
            'locations.*'                              => ['nullable'],
        ]);

        DB::transaction(function () use ($menu, $data) {
            // Keep the original slug unless the label changed so the name isn't
            // constantly regenerated. If labels collide, uniqueSlug handles it.
            $currentLabel = $menu->translations->first()?->label;
            if ($currentLabel !== $data['label']) {
                $menu->update(['name' => $this->uniqueSlug($data['label'], $menu->id)]);
            }

            // Propagate the single admin-facing label to every language row.
            foreach (Language::notDisabled()->get() as $lang) {
                MenuTranslation::updateOrCreate(
                    ['menu_id' => $menu->id, 'language_id' => $lang->id],
                    ['label' => $data['label']]
                );
            }

            // Items
            $seenItemIds = [];
            $position    = 0;
            foreach ($data['items'] ?? [] as $row) {
                $position++;

                $payload = [
                    'menu_id'      => $menu->id,
                    'parent_id'    => ! empty($row['parent_id']) ? (int) $row['parent_id'] : null,
                    'type'         => $row['type'],
                    'reference_id' => ! empty($row['reference_id']) ? (int) $row['reference_id'] : null,
                    'target'       => $row['target'] ?? '_self',
                    'icon'         => $row['icon'] ?? null,
                    'is_active'    => ! empty($row['is_active']),
                    'position'     => $row['position'] ?? $position,
                ];

                if (! empty($row['id'])) {
                    $item = MenuItem::where('menu_id', $menu->id)->find($row['id']);
                    if ($item) {
                        $item->update($payload);
                    }
                } else {
                    $item = MenuItem::create($payload);
                }

                if (! $item) {
                    continue;
                }

                $seenItemIds[] = $item->id;

                // Item translations
                foreach ($row['translations'] ?? [] as $langId => $trans) {
                    $label = trim($trans['label'] ?? '');
                    $url   = trim($trans['url']   ?? '');
                    if ($label === '' && $url === '') {
                        MenuItemTranslation::where('menu_item_id', $item->id)
                            ->where('language_id', $langId)
                            ->delete();
                        continue;
                    }
                    MenuItemTranslation::updateOrCreate(
                        ['menu_item_id' => $item->id, 'language_id' => $langId],
                        ['label' => $label ?: '—', 'url' => $url ?: null]
                    );
                }
            }

            // Delete items that are no longer in the form (explicit removes)
            MenuItem::where('menu_id', $menu->id)
                ->when(! empty($seenItemIds), fn ($q) => $q->whereNotIn('id', $seenItemIds))
                ->delete();

            // Fix any parent_id that now points at a deleted item
            MenuItem::where('menu_id', $menu->id)
                ->whereNotNull('parent_id')
                ->whereNotIn('parent_id', array_merge($seenItemIds, [0]))
                ->update(['parent_id' => null]);

            // Locations for the active theme only
            $theme       = ThemeRegistry::activeName();
            $declared    = array_keys($this->themeLocations());
            $requested   = array_keys(array_filter($data['locations'] ?? [], fn ($v) => ! empty($v)));
            $toAssign    = array_intersect($declared, $requested);

            // Unassign any of THIS menu's current locations that were unchecked
            MenuLocation::where('menu_id', $menu->id)
                ->where('theme', $theme)
                ->whereNotIn('location', $toAssign)
                ->delete();

            // Assign requested locations (may steal from other menus — that's expected)
            foreach ($toAssign as $location) {
                MenuLocation::updateOrCreate(
                    ['theme' => $theme, 'location' => $location],
                    ['menu_id' => $menu->id]
                );
            }
        });

        return redirect()->route('cms.admin.menus.edit', $menu->id)
            ->with('success', 'Menu saved.');
    }

    public function destroy(int $id)
    {
        Menu::findOrFail($id)->delete();

        return redirect()->route('cms.admin.menus.index')->with('success', 'Menu deleted.');
    }

    /**
     * Persist a new item order from drag-and-drop.
     * Request body: { ids: [3, 1, 2] } — array of menu_item IDs in the new order.
     */
    public function reorderItems(Request $request, int $id)
    {
        $menu = Menu::findOrFail($id);

        $data = $request->validate([
            'ids'   => ['required', 'array'],
            'ids.*' => ['integer'],
        ]);

        // Restrict update to items that actually belong to this menu.
        $validIds = MenuItem::where('menu_id', $menu->id)
            ->whereIn('id', $data['ids'])
            ->pluck('id')
            ->toArray();

        DB::transaction(function () use ($validIds, $data, $menu) {
            $position = 0;
            foreach ($data['ids'] as $itemId) {
                if (! in_array((int) $itemId, $validIds, true)) {
                    continue;
                }
                $position++;
                MenuItem::where('menu_id', $menu->id)
                    ->where('id', $itemId)
                    ->update(['position' => $position]);
            }
        });

        return response()->json(['ok' => true, 'count' => count($validIds)]);
    }

    /** Add a blank item and reload the editor — mirrors the block-add pattern. */
    public function addItem(Request $request, int $id)
    {
        $menu = Menu::findOrFail($id);

        $data = $request->validate([
            'type'         => ['required', 'string', 'in:page,post,content,term,custom_url'],
            'reference_id' => ['nullable', 'integer'],
            'label'        => ['nullable', 'string', 'max:255'],
            'url'          => ['nullable', 'string', 'max:500'],
        ]);

        $position = (MenuItem::where('menu_id', $menu->id)->max('position') ?? 0) + 1;

        $item = MenuItem::create([
            'menu_id'      => $menu->id,
            'type'         => $data['type'],
            'reference_id' => $data['reference_id'] ?? null,
            'target'       => '_self',
            'is_active'    => true,
            'position'     => $position,
        ]);

        // Derive a default label and URL
        [$label, $url] = $this->deriveLabelAndUrl($data['type'], $data);

        // Create translation for every language (labels all the same on create)
        foreach (Language::notDisabled()->get() as $lang) {
            MenuItemTranslation::create([
                'menu_item_id' => $item->id,
                'language_id'  => $lang->id,
                'label'        => $label,
                'url'          => $data['type'] === 'custom_url' ? $url : null,
            ]);
        }

        return redirect()->route('cms.admin.menus.edit', $menu->id)
            ->with('success', 'Item added.');
    }

    // ── Helpers ─────────────────────────────────────────────────────────────

    /**
     * Slugify the given label and guarantee it's unique in the menus table.
     * Appends -2, -3, etc. until available (excluding the current menu's own row).
     */
    protected function uniqueSlug(string $label, ?int $exceptId = null): string
    {
        $base = Str::slug($label);
        if ($base === '') {
            $base = 'menu';
        }
        $base = substr($base, 0, 90);

        $slug    = $base;
        $counter = 2;
        while (
            Menu::where('name', $slug)
                ->when($exceptId, fn ($q) => $q->where('id', '!=', $exceptId))
                ->exists()
        ) {
            $slug = $base . '-' . $counter++;
        }
        return $slug;
    }

    /** id => "Title" map for a given content type (page, post, etc.). */
    protected function contentOptions(string $typeName): array
    {
        $lang = Language::where('is_default', true)->first()
            ?? Language::notDisabled()->orderBy('position')->first();

        $type = ContentType::where('name', $typeName)->first();
        if (! $type || ! $lang) {
            return [];
        }

        return Content::where('content_type_id', $type->id)
            ->with(['translations' => fn ($q) => $q->where('language_id', $lang->id)])
            ->get()
            ->mapWithKeys(function ($c) {
                $t = $c->translations->first();
                return [$c->id => $t?->title ?? ('#' . $c->id)];
            })
            ->toArray();
    }

    /** Locations declared by the active theme's theme.json. */
    protected function themeLocations(): array
    {
        $active = ThemeRegistry::active();
        return $active['meta']['menu_locations'] ?? [];
    }

    /** Guess label + url for a new item based on its type + reference. */
    protected function deriveLabelAndUrl(string $type, array $data): array
    {
        $lang = Language::where('is_default', true)->first()
            ?? Language::notDisabled()->orderBy('position')->first();

        switch ($type) {
            case 'custom_url':
                return [$data['label'] ?? 'Link', $data['url'] ?? '#'];

            case 'term':
                if (! empty($data['reference_id']) && $lang) {
                    $term = Term::with('translations')->find($data['reference_id']);
                    $tr   = $term?->translations->firstWhere('language_id', $lang->id)
                          ?? $term?->translations->first();
                    return [$tr?->name ?? 'Term', null];
                }
                return ['Term', null];

            default: // page, post, content
                if (! empty($data['reference_id']) && $lang) {
                    $content = Content::with(['translations' => fn ($q) => $q->where('language_id', $lang->id)])
                        ->find($data['reference_id']);
                    $tr = $content?->translations->first();
                    return [$tr?->title ?? Str::title($type), null];
                }
                return [Str::title($type), null];
        }
    }
}
