<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Http\Controllers\Admin;

use Contensio\Services\PluginUpdateChecker;
use Contensio\Support\AccessControl;
use Contensio\Support\Activity;
use Contensio\Support\PluginOptions;
use Contensio\Support\PluginRegistry;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Log;
use ZipArchive;

class PluginController extends Controller
{
    /** List all discovered plugins with their enabled state. */
    public function index()
    {
        $plugins     = PluginRegistry::all();
        $enabledList = PluginRegistry::enabledNames();
        $updateInfo  = PluginUpdateChecker::all();

        return view('contensio::admin.plugins.index', compact('plugins', 'enabledList', 'updateInfo'));
    }

    /** Enable a plugin. Also runs its migrations (if any) to spare admins a CLI step. */
    public function enable(Request $request)
    {
        $data = $request->validate(['plugin' => 'required|string']);

        $plugin = PluginRegistry::get($data['plugin']);
        if (! $plugin) {
            return back()->withErrors(['plugin' => 'Plugin not found.']);
        }

        PluginRegistry::enable($data['plugin']);

        // Run the plugin's bundled migrations (both local + Composer plugins).
        // Non-fatal: if a migration errors, we keep the plugin enabled and surface
        // a friendly message so the admin can investigate.
        $migrationWarning = $this->runPluginMigrations($plugin);

        $message = 'Plugin enabled.';
        if ($migrationWarning) {
            $message .= ' ' . $migrationWarning;
        }

        Activity::record('plugin_enabled', 'plugin', null, "Plugin: {$data['plugin']}")
            ->withProperties(['name' => $data['plugin'], 'version' => $plugin['meta']['version'] ?? null]);

        return back()->with('success', $message);
    }

    /**
     * Run any migrations shipped with the plugin (in `database/migrations/`).
     * Returns null on success, or a short warning string describing a failure.
     */
    protected function runPluginMigrations(array $plugin): ?string
    {
        $migrationsPath = rtrim($plugin['path'] ?? '', '/\\') . DIRECTORY_SEPARATOR . 'database' . DIRECTORY_SEPARATOR . 'migrations';

        if (! is_dir($migrationsPath)) {
            return null;
        }

        // Only bother if there's at least one migration file.
        $hasFiles = (bool) glob($migrationsPath . DIRECTORY_SEPARATOR . '*.php');
        if (! $hasFiles) {
            return null;
        }

        try {
            Artisan::call('migrate', [
                '--path'     => $migrationsPath,
                '--realpath' => true,
                '--force'    => true,
            ]);
            return null;
        } catch (\Throwable $e) {
            report($e);
            return 'Its migrations did not run cleanly — run `php artisan migrate` manually to investigate.';
        }
    }

    /** Disable a plugin. */
    public function disable(Request $request)
    {
        $data = $request->validate(['plugin' => 'required|string']);

        PluginRegistry::disable($data['plugin']);

        Activity::record('plugin_disabled', 'plugin', null, "Plugin: {$data['plugin']}");

        return back()->with('success', 'Plugin disabled.');
    }

    /**
     * Install a plugin from an uploaded ZIP file.
     *
     * The ZIP must contain a plugin.json at its root (or one folder deep),
     * with a "name" field in "vendor/package" format.
     */
    public function install(Request $request)
    {
        $request->validate([
            'zip' => 'required|file|mimes:zip|max:102400', // 100 MB
        ]);

        $zip  = new ZipArchive;
        $file = $request->file('zip');

        if ($zip->open($file->getRealPath()) !== true) {
            return back()->withErrors(['zip' => 'Could not open the ZIP file.']);
        }

        // Find plugin.json — root or one folder deep
        $manifestIndex = $zip->locateName('plugin.json');
        if ($manifestIndex === false) {
            for ($i = 0; $i < $zip->numFiles; $i++) {
                $entry = $zip->getNameIndex($i);
                if (preg_match('#^[^/]+/plugin\.json$#', $entry)) {
                    $manifestIndex = $i;
                    break;
                }
            }
        }

        if ($manifestIndex === false) {
            $zip->close();
            return back()->withErrors(['zip' => 'No plugin.json found in the ZIP.']);
        }

        $meta = json_decode($zip->getFromIndex($manifestIndex), true);
        if (empty($meta['name']) || ! preg_match('#^[a-z0-9_-]+/[a-z0-9_-]+$#', $meta['name'])) {
            $zip->close();
            return back()->withErrors(['zip' => 'Invalid plugin name in plugin.json. Must be "vendor/name".']);
        }

        $pluginName  = $meta['name'];
        $pluginsRoot = rtrim(config('contensio.packages_path', base_path('packages')), '/') . '/plugins';
        $targetPath  = $pluginsRoot . '/' . $pluginName;

        // Wipe any previous installation of the same plugin
        if (is_dir($targetPath)) {
            File::deleteDirectory($targetPath);
        }

        File::ensureDirectoryExists($targetPath);
        $zip->extractTo($targetPath);
        $zip->close();

        // If the ZIP contained a single wrapper folder, flatten it
        $entries = array_diff(scandir($targetPath), ['.', '..']);
        if (count($entries) === 1) {
            $inner = $targetPath . '/' . reset($entries);
            if (is_dir($inner)) {
                foreach (scandir($inner) as $item) {
                    if ($item === '.' || $item === '..') continue;
                    rename("{$inner}/{$item}", "{$targetPath}/{$item}");
                }
                rmdir($inner);
            }
        }

        return back()->with('success', "Plugin \"{$pluginName}\" installed. Activate it when ready.");
    }

    /**
     * Plugin settings page — dynamic form driven by the plugin's settings schema.
     */
    public function settings(Request $request)
    {
        $name   = (string) $request->query('plugin', '');
        $plugin = PluginRegistry::get($name);

        if (! $plugin) {
            return redirect()
                ->route('contensio.account.plugins.index')
                ->withErrors(['plugin' => 'Plugin not found.']);
        }

        if (! PluginRegistry::isEnabled($name)) {
            return redirect()
                ->route('contensio.account.plugins.index')
                ->withErrors(['plugin' => 'Enable the plugin first to configure it.']);
        }

        $sections = PluginOptions::schema($name);

        if (empty($sections)) {
            return redirect()
                ->route('contensio.account.plugins.index')
                ->withErrors(['plugin' => 'This plugin does not declare any settings.']);
        }

        $values = PluginOptions::all($name);

        return view('contensio::admin.plugins.settings', compact('name', 'plugin', 'sections', 'values'));
    }

    /**
     * Save plugin settings. Walks the declared schema so unknown keys
     * from the request are ignored and each field is cast to its type.
     */
    public function saveSettings(Request $request)
    {
        $data = $request->validate(['plugin' => 'required|string']);
        $name = $data['plugin'];

        if (! PluginRegistry::get($name)) {
            return redirect()
                ->route('contensio.account.plugins.index')
                ->withErrors(['plugin' => 'Plugin not found.']);
        }

        $sections = PluginOptions::schema($name);
        $values   = [];

        foreach ($sections as $section) {
            foreach ($section['fields'] ?? [] as $field) {
                $key = $field['key'] ?? null;
                if (! $key) {
                    continue;
                }
                $type = $field['type'] ?? 'text';
                $raw  = $request->input("options.{$key}");

                $values[$key] = match ($type) {
                    'checkbox'        => $request->boolean("options.{$key}"),
                    'number', 'range' => is_numeric($raw) ? 0 + $raw : ($field['default'] ?? 0),
                    default           => is_scalar($raw) || is_null($raw) ? (string) ($raw ?? '') : '',
                };
            }
        }

        PluginOptions::save($name, $values);

        return redirect()
            ->route('contensio.account.plugins.settings', ['plugin' => $name])
            ->with('success', 'Plugin settings saved.');
    }

    /** Reset a plugin's settings to its declared defaults. */
    public function resetSettings(Request $request)
    {
        $data = $request->validate(['plugin' => 'required|string']);
        PluginOptions::reset($data['plugin']);

        return redirect()
            ->route('contensio.account.plugins.settings', ['plugin' => $data['plugin']])
            ->with('success', 'Plugin settings reset to defaults.');
    }

    /**
     * Update a plugin to its latest available version.
     *
     * Downloads the ZIP from the cached update info, extracts it over the
     * existing plugin directory, then re-runs migrations.
     */
    public function update(Request $request)
    {
        $data = $request->validate(['plugin' => 'required|string']);
        $name = $data['plugin'];

        $plugin = PluginRegistry::get($name);
        if (! $plugin) {
            return back()->withErrors(['plugin' => 'Plugin not found.']);
        }

        $updateInfo = PluginUpdateChecker::forPlugin($name);
        if (! $updateInfo) {
            return back()->withErrors(['plugin' => 'No update available for this plugin.']);
        }

        $downloadUrl = $updateInfo['download_url'] ?? null;
        if (! $downloadUrl || ! str_starts_with($downloadUrl, 'https://')) {
            return back()->withErrors(['plugin' => 'Invalid download URL.']);
        }

        // Download the ZIP
        try {
            $response = Http::timeout(60)->get($downloadUrl);
            if (! $response->successful()) {
                return back()->withErrors(['plugin' => 'Could not download the update ZIP. Try again later.']);
            }
        } catch (\Throwable $e) {
            Log::warning("[PluginUpdate] Download failed for {$name}: " . $e->getMessage());
            return back()->withErrors(['plugin' => 'Download failed: ' . $e->getMessage()]);
        }

        // Write to a temp file and run through the standard install flow
        $tmpPath = sys_get_temp_dir() . '/' . 'contensio_update_' . md5($name) . '.zip';
        file_put_contents($tmpPath, $response->body());

        $zip = new ZipArchive;
        if ($zip->open($tmpPath) !== true) {
            @unlink($tmpPath);
            return back()->withErrors(['plugin' => 'Could not open the downloaded ZIP.']);
        }

        // Validate plugin.json inside the ZIP
        $manifestIndex = $zip->locateName('plugin.json');
        if ($manifestIndex === false) {
            for ($i = 0; $i < $zip->numFiles; $i++) {
                $entry = $zip->getNameIndex($i);
                if (preg_match('#^[^/]+/plugin\.json$#', $entry)) {
                    $manifestIndex = $i;
                    break;
                }
            }
        }

        if ($manifestIndex === false) {
            $zip->close();
            @unlink($tmpPath);
            return back()->withErrors(['plugin' => 'No plugin.json found in the update ZIP.']);
        }

        $meta = json_decode($zip->getFromIndex($manifestIndex), true);
        if (($meta['name'] ?? '') !== $name) {
            $zip->close();
            @unlink($tmpPath);
            return back()->withErrors(['plugin' => 'The downloaded ZIP does not match this plugin.']);
        }

        // Extract over existing files
        $pluginsRoot = rtrim(config('contensio.packages_path', base_path('packages')), '/') . '/plugins';
        $targetPath  = $pluginsRoot . '/' . $name;

        File::deleteDirectory($targetPath);
        File::ensureDirectoryExists($targetPath);
        $zip->extractTo($targetPath);
        $zip->close();
        @unlink($tmpPath);

        // Flatten single wrapper folder if present
        $entries = array_diff(scandir($targetPath), ['.', '..']);
        if (count($entries) === 1) {
            $inner = $targetPath . '/' . reset($entries);
            if (is_dir($inner)) {
                foreach (scandir($inner) as $item) {
                    if ($item === '.' || $item === '..') continue;
                    rename("{$inner}/{$item}", "{$targetPath}/{$item}");
                }
                rmdir($inner);
            }
        }

        // Re-run migrations for the updated plugin
        $updatedPlugin = PluginRegistry::get($name) ?? $plugin;
        $this->runPluginMigrations($updatedPlugin);

        // Clear the update cache entry so the badge disappears
        PluginUpdateChecker::clearCache();

        $newVersion = $updateInfo['latest_version'];
        Activity::record('plugin_updated', 'plugin', null, "Plugin: {$name} → v{$newVersion}");

        return back()->with('success', "Plugin \"{$name}\" updated to v{$newVersion}.");
    }

    /** Uninstall a local plugin (Composer-installed plugins can't be removed via admin). */
    public function uninstall(Request $request)
    {
        $data = $request->validate(['plugin' => 'required|string']);

        $name   = $data['plugin'];
        $plugin = PluginRegistry::get($name);

        if (! $plugin) {
            return back()->withErrors(['plugin' => 'Plugin not found.']);
        }

        if (($plugin['source'] ?? '') !== 'local') {
            return back()->withErrors(['plugin' => 'Only locally installed plugins can be removed. Remove Composer plugins via `composer remove`.']);
        }

        if (PluginRegistry::isEnabled($name)) {
            return back()->withErrors(['plugin' => 'Disable the plugin first, then uninstall.']);
        }

        File::deleteDirectory($plugin['path']);

        // Clean up plugin-declared permissions + roles (user assignments to
        // those roles are automatically cascaded by the foreign keys)
        AccessControl::removePluginDefinitions($name);

        // Also drop any stored plugin options
        PluginOptions::reset($name);

        return back()->with('success', "Plugin \"{$name}\" removed.");
    }
}
