<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Cms\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Contensio\Cms\Models\ContentType;
use Contensio\Cms\Models\Language;
use Contensio\Cms\Models\Setting;

class SettingController extends Controller
{
    public function index()
    {
        $stats = [
            'languages'     => Language::count(),
            'content_types' => ContentType::count(),
        ];

        return view('cms::admin.settings.index', compact('stats'));
    }

    public function general()
    {
        $settings = Setting::where('module', 'core')->pluck('value', 'setting_key');

        return view('cms::admin.settings.general', compact('settings'));
    }

    public function saveGeneral(Request $request)
    {
        $request->validate([
            'site_name'    => 'required|string|max:200',
            'site_tagline' => 'nullable|string|max:500',
            'timezone'     => 'required|string|max:100',
            'date_format'  => 'nullable|string|max:50',
        ]);

        $map = [
            'site_name'    => $request->site_name,
            'site_tagline' => $request->site_tagline ?? '',
            'timezone'     => $request->timezone,
            'date_format'  => $request->date_format ?? 'M d, Y',
        ];

        foreach ($map as $key => $value) {
            Setting::updateOrCreate(
                ['module' => 'core', 'setting_key' => $key],
                ['value' => $value, 'updated_at' => now()]
            );
        }

        return redirect()->route('cms.admin.settings.general')->with('success', 'Settings saved.');
    }

    /** SEO settings page — sitemap-related toggles, OG defaults, verification codes. */
    public function seo()
    {
        $settings = Setting::where('module', 'core')
            ->whereIn('setting_key', [
                'seo_noindex',
                'default_og_image',
                'google_site_verification',
                'robots_txt',
            ])
            ->pluck('value', 'setting_key');

        return view('cms::admin.settings.seo', compact('settings'));
    }

    public function saveSeo(Request $request)
    {
        $data = $request->validate([
            'seo_noindex'              => 'nullable',
            'default_og_image'         => 'nullable|string|max:500',
            'google_site_verification' => 'nullable|string|max:200',
            'robots_txt'               => 'nullable|string|max:5000',
        ]);

        $map = [
            'seo_noindex'              => $request->boolean('seo_noindex') ? '1' : '',
            'default_og_image'         => trim((string) ($data['default_og_image'] ?? '')),
            'google_site_verification' => trim((string) ($data['google_site_verification'] ?? '')),
            'robots_txt'               => trim((string) ($data['robots_txt'] ?? '')),
        ];

        foreach ($map as $key => $value) {
            Setting::updateOrCreate(
                ['module' => 'core', 'setting_key' => $key],
                ['value' => $value, 'updated_at' => now()]
            );
        }

        return redirect()->route('cms.admin.settings.seo')->with('success', 'SEO settings saved.');
    }
}
