<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Crypt;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use Contensio\Models\ContentType;
use Contensio\Models\Language;
use Contensio\Models\Role;
use Contensio\Models\Setting;
use Contensio\Support\EmailConfig;

class SettingController extends Controller
{
    public function index()
    {
        $stats = [
            'languages'     => Language::count(),
            'content_types' => ContentType::count(),
        ];

        return view('contensio::admin.settings.index', compact('stats'));
    }

    public function general()
    {
        $settings = Setting::where('module', 'core')->pluck('value', 'setting_key');

        return view('contensio::admin.settings.general', compact('settings'));
    }

    public function saveGeneral(Request $request)
    {
        $request->validate([
            'site_name'    => 'required|string|max:200',
            'site_tagline' => 'nullable|string|max:500',
            'timezone'     => 'required|string|max:100',
            'date_format'  => 'nullable|string|max:50',
        ]);

        $map = [
            'site_name'    => $request->site_name,
            'site_tagline' => $request->site_tagline ?? '',
            'timezone'     => $request->timezone,
            'date_format'  => $request->date_format ?? 'M d, Y',
        ];

        foreach ($map as $key => $value) {
            Setting::updateOrCreate(
                ['module' => 'core', 'setting_key' => $key],
                ['value' => $value, 'updated_at' => now()]
            );
        }

        return redirect()->route('contensio.account.settings.general')->with('success', 'Settings saved.');
    }

    /** SEO settings page — sitemap-related toggles, OG defaults, verification codes. */
    public function seo()
    {
        $settings = Setting::where('module', 'core')
            ->whereIn('setting_key', [
                'seo_noindex',
                'default_og_image',
                'google_site_verification',
                'robots_txt',
            ])
            ->pluck('value', 'setting_key');

        return view('contensio::admin.settings.seo', compact('settings'));
    }

    public function saveSeo(Request $request)
    {
        $data = $request->validate([
            'seo_noindex'              => 'nullable',
            'default_og_image'         => 'nullable|string|max:500',
            'google_site_verification' => 'nullable|string|max:200',
            'robots_txt'               => 'nullable|string|max:5000',
        ]);

        $map = [
            'seo_noindex'              => $request->boolean('seo_noindex') ? '1' : '',
            'default_og_image'         => trim((string) ($data['default_og_image'] ?? '')),
            'google_site_verification' => trim((string) ($data['google_site_verification'] ?? '')),
            'robots_txt'               => trim((string) ($data['robots_txt'] ?? '')),
        ];

        foreach ($map as $key => $value) {
            Setting::updateOrCreate(
                ['module' => 'core', 'setting_key' => $key],
                ['value' => $value, 'updated_at' => now()]
            );
        }

        return redirect()->route('contensio.account.settings.seo')->with('success', 'SEO settings saved.');
    }

    /** Email / SMTP settings. */
    public function email()
    {
        $settings = EmailConfig::load();

        return view('contensio::admin.settings.email', compact('settings'));
    }

    public function saveEmail(Request $request)
    {
        $data = $request->validate([
            'mailer'       => 'required|in:smtp,sendmail,log,array',
            'host'         => 'nullable|string|max:255',
            'port'         => 'nullable|integer|min:1|max:65535',
            'encryption'   => 'nullable|in:tls,ssl,',
            'username'     => 'nullable|string|max:255',
            'password'     => 'nullable|string|max:500',
            'from_address' => 'required|email|max:255',
            'from_name'    => 'required|string|max:255',
        ]);

        // When password is empty, keep the previously-stored value —
        // the form shows a placeholder, not the actual secret.
        if ($data['password'] === null || $data['password'] === '') {
            unset($data['password']);
        } else {
            $data['password'] = Crypt::encryptString($data['password']);
        }

        foreach ($data as $key => $value) {
            Setting::updateOrCreate(
                ['module' => 'email', 'setting_key' => $key],
                ['value' => (string) $value, 'updated_at' => now()]
            );
        }

        // Re-apply so the next request (and any test email) uses fresh config
        EmailConfig::apply();

        return redirect()->route('contensio.account.settings.email')->with('success', 'Email settings saved.');
    }

    /** Comments settings. */
    public function comments()
    {
        $settings = Setting::where('module', 'comments')
            ->pluck('value', 'setting_key');

        return view('contensio::admin.settings.comments', compact('settings'));
    }

    public function saveComments(Request $request)
    {
        $data = $request->validate([
            'comments_enabled'         => 'nullable',
            'comments_require_approval'=> 'nullable',
            'comments_allow_guests'    => 'nullable',
            'comments_close_after_days'=> 'nullable|integer|min:0|max:3650',
        ]);

        $map = [
            'comments_enabled'          => $request->boolean('comments_enabled')          ? '1' : '',
            'comments_require_approval' => $request->boolean('comments_require_approval') ? '1' : '',
            'comments_allow_guests'     => $request->boolean('comments_allow_guests')     ? '1' : '',
            'comments_close_after_days' => (string) intval($data['comments_close_after_days'] ?? 0),
        ];

        foreach ($map as $key => $value) {
            Setting::updateOrCreate(
                ['module' => 'comments', 'setting_key' => $key],
                ['value' => $value, 'updated_at' => now()]
            );
        }

        return redirect()->route('contensio.account.settings.comments')->with('success', 'Comment settings saved.');
    }

    /** Users & registration settings. */
    public function users()
    {
        $settings = Setting::where('module', 'users')->pluck('value', 'setting_key');
        $roles    = Role::with('translations')->orderBy('position')->orderBy('name')->get();

        return view('contensio::admin.settings.users', compact('settings', 'roles'));
    }

    public function saveUsers(Request $request)
    {
        $request->validate([
            'default_registration_role_id' => ['nullable', 'integer', 'exists:roles,id'],
            'username_cooldown_days'        => ['nullable', 'integer', 'min:0', 'max:3650'],
            'inactivity_logout_days'        => ['nullable', 'integer', 'min:0', 'max:3650'],
            'max_sessions'                  => ['nullable', 'integer', 'min:0', 'max:100'],
        ]);

        $map = [
            // Registration
            'registration_disabled'        => $request->boolean('registration_disabled')        ? '1' : '',
            'require_approval'             => $request->boolean('require_approval')             ? '1' : '',
            'default_registration_role_id' => (string) intval($request->input('default_registration_role_id')),
            'email_verification_disabled'  => $request->boolean('email_verification_disabled')  ? '1' : '',
            // Accounts
            'allow_email_change'           => $request->boolean('allow_email_change')           ? '1' : '',
            'allow_account_deletion'       => $request->boolean('allow_account_deletion')       ? '1' : '',
            // Profile
            'allow_bio'                    => $request->boolean('allow_bio')                    ? '1' : '',
            'allow_avatar'                 => $request->boolean('allow_avatar')                 ? '1' : '',
            // Usernames
            'users_can_change_username'    => $request->boolean('users_can_change_username')    ? '1' : '',
            'username_cooldown_days'       => (string) intval($request->input('username_cooldown_days', 0)),
            // Security
            'inactivity_logout_days'       => (string) intval($request->input('inactivity_logout_days', 0)),
            'max_sessions'                 => (string) intval($request->input('max_sessions', 0)),
        ];

        foreach ($map as $key => $value) {
            Setting::updateOrCreate(
                ['module' => 'users', 'setting_key' => $key],
                ['value' => $value, 'updated_at' => now()]
            );
        }

        // When email verification is disabled, immediately verify all unverified users
        if ($map['email_verification_disabled'] === '1') {
            DB::table('users')->whereNull('email_verified_at')->update(['email_verified_at' => now()]);
        }

        return redirect()->route('contensio.account.settings.users')->with('success', 'Settings saved.');
    }

    public function sendTestEmail(Request $request)
    {
        $request->validate(['to' => 'required|email']);

        EmailConfig::apply();

        try {
            Mail::raw(
                "This is a test email from " . config('contensio.name', 'Contensio') . ".\n\n"
                . "If you received this, your email settings are working correctly.",
                function ($m) use ($request) {
                    $m->to($request->to)->subject('Test email from ' . config('contensio.name', 'Contensio'));
                }
            );
        } catch (\Throwable $e) {
            return redirect()->route('contensio.account.settings.email')
                ->with('error', 'Failed to send: ' . $e->getMessage());
        }

        return redirect()->route('contensio.account.settings.email')
            ->with('success', 'Test email sent to ' . $request->to . '.');
    }
}
