<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Cms\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Contensio\Cms\Models\ContentType;
use Contensio\Cms\Models\Language;
use Contensio\Cms\Models\Taxonomy;
use Contensio\Cms\Models\TaxonomyTranslation;

class TaxonomyController extends Controller
{
    public function create(int $typeId)
    {
        $type = ContentType::find($typeId);

        if (! $type) {
            return redirect()->route('cms.admin.content-types.index')
                ->with('error', 'Content type not found.');
        }

        $languages       = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defaultLanguage = Language::where('is_default', true)->first() ?? $languages->first();

        return view('cms::admin.taxonomies.form', [
            'taxonomy'        => null,
            'type'            => $type,
            'languages'       => $languages,
            'defaultLanguage' => $defaultLanguage,
            'existing'        => [],
        ]);
    }

    public function store(Request $request, int $typeId)
    {
        $type = ContentType::find($typeId);

        if (! $type) {
            return redirect()->route('cms.admin.content-types.index')
                ->with('error', 'Content type not found.');
        }

        $languages       = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defaultLanguage = Language::where('is_default', true)->first() ?? $languages->first();
        $defaultLangId   = $defaultLanguage?->id ?? 1;

        $request->validate([
            "translations.{$defaultLangId}.singular" => 'required|string|max:100',
            "translations.{$defaultLangId}.plural"   => 'required|string|max:100',
            "translations.{$defaultLangId}.slug"     => 'required|string|max:100|alpha_dash',
        ]);

        $defaultSingular = $request->input("translations.{$defaultLangId}.singular");
        $internalName    = Str::slug($defaultSingular, '_');

        if (Taxonomy::where('name', $internalName)->exists()) {
            return back()->withInput()
                ->withErrors(["translations.{$defaultLangId}.singular" => 'A taxonomy with this name already exists.']);
        }

        $taxonomy = Taxonomy::create([
            'name'            => $internalName,
            'is_hierarchical' => $request->boolean('is_hierarchical'),
            'is_system'       => false,
        ]);

        foreach ($languages as $lang) {
            $singular = $request->input("translations.{$lang->id}.singular");
            $plural   = $request->input("translations.{$lang->id}.plural");
            $slug     = $request->input("translations.{$lang->id}.slug");

            if (! $singular || ! $plural || ! $slug) {
                continue;
            }

            TaxonomyTranslation::create([
                'taxonomy_id' => $taxonomy->id,
                'language_id' => $lang->id,
                'slug'        => $slug,
                'labels'      => $this->buildLabels($singular, $plural,
                    $request->input("translations.{$lang->id}.labels", [])),
            ]);
        }

        DB::table('content_type_taxonomies')->insertOrIgnore([
            'content_type_id' => $type->id,
            'taxonomy_id'     => $taxonomy->id,
        ]);

        return redirect()->route('cms.admin.content-types.index')
            ->with('success', "Taxonomy \"{$defaultSingular}\" added to {$type->name}.");
    }

    public function edit(int $typeId, int $id)
    {
        $type     = ContentType::find($typeId);
        $taxonomy = Taxonomy::with('translations')->find($id);

        if (! $type || ! $taxonomy) {
            return redirect()->route('cms.admin.content-types.index')
                ->with('error', 'Not found.');
        }

        $languages       = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defaultLanguage = Language::where('is_default', true)->first() ?? $languages->first();

        // Build existing translations map keyed by language_id
        $existing = [];
        foreach ($taxonomy->translations as $trans) {
            $existing[$trans->language_id] = [
                'singular'  => $trans->labels['singular']  ?? '',
                'plural'    => $trans->labels['plural']    ?? '',
                'slug'      => $trans->slug,
                'create'    => $trans->labels['create']    ?? '',
                'all'       => $trans->labels['all']       ?? '',
                'not_found' => $trans->labels['not_found'] ?? '',
            ];
        }

        return view('cms::admin.taxonomies.form', [
            'taxonomy'        => $taxonomy,
            'type'            => $type,
            'languages'       => $languages,
            'defaultLanguage' => $defaultLanguage,
            'existing'        => $existing,
        ]);
    }

    public function update(Request $request, int $typeId, int $id)
    {
        $type     = ContentType::find($typeId);
        $taxonomy = Taxonomy::find($id);

        if (! $type || ! $taxonomy) {
            return redirect()->route('cms.admin.content-types.index')
                ->with('error', 'Not found.');
        }

        $languages       = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defaultLanguage = Language::where('is_default', true)->first() ?? $languages->first();
        $defaultLangId   = $defaultLanguage?->id ?? 1;

        $request->validate([
            "translations.{$defaultLangId}.singular" => 'required|string|max:100',
            "translations.{$defaultLangId}.plural"   => 'required|string|max:100',
            "translations.{$defaultLangId}.slug"     => 'required|string|max:100|alpha_dash',
        ]);

        $taxonomy->update([
            'is_hierarchical' => $request->boolean('is_hierarchical'),
        ]);

        foreach ($languages as $lang) {
            $singular = $request->input("translations.{$lang->id}.singular");
            $plural   = $request->input("translations.{$lang->id}.plural");
            $slug     = $request->input("translations.{$lang->id}.slug");

            if (! $singular || ! $plural || ! $slug) {
                continue;
            }

            TaxonomyTranslation::updateOrCreate(
                ['taxonomy_id' => $taxonomy->id, 'language_id' => $lang->id],
                [
                    'slug'   => $slug,
                    'labels' => $this->buildLabels($singular, $plural,
                        $request->input("translations.{$lang->id}.labels", [])),
                ]
            );
        }

        $defaultSingular = $request->input("translations.{$defaultLangId}.singular");

        return redirect()->route('cms.admin.content-types.index')
            ->with('success', "Taxonomy \"{$defaultSingular}\" saved.");
    }

    public function destroy(int $typeId, int $id)
    {
        $taxonomy = Taxonomy::find($id);

        if (! $taxonomy) {
            return redirect()->route('cms.admin.content-types.index');
        }

        if ($taxonomy->is_system) {
            return redirect()->route('cms.admin.content-types.index')
                ->with('error', 'Core taxonomies cannot be deleted.');
        }

        $termCount = DB::table('terms')->where('taxonomy_id', $taxonomy->id)->count();

        if ($termCount > 0) {
            return redirect()->route('cms.admin.content-types.index')
                ->with('error', "Cannot delete taxonomy — it still has {$termCount} term(s).");
        }

        $taxonomy->delete();

        return redirect()->route('cms.admin.content-types.index')
            ->with('success', 'Taxonomy deleted.');
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private function buildLabels(string $singular, string $plural, array $overrides = []): array
    {
        $defaults = [
            'singular'  => $singular,
            'plural'    => $plural,
            'create'    => "Add New {$singular}",
            'all'       => "All {$plural}",
            'not_found' => "No {$plural} found",
        ];

        return array_merge($defaults, array_filter($overrides, fn ($v) => $v !== null && $v !== ''));
    }
}
