<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Str;
use Contensio\Models\Language;
use Contensio\Models\Taxonomy;
use Contensio\Models\Term;
use Contensio\Models\TermTranslation;

class TermController extends Controller
{
    public function index(int $taxonomyId)
    {
        $taxonomy = Taxonomy::with('translations')->find($taxonomyId);

        if (! $taxonomy) {
            return redirect()->route('contensio.account.content-types.index')
                ->with('error', 'Taxonomy not found.');
        }

        $defaultLanguage = Language::where('is_default', true)->first();
        $defaultLangId   = $defaultLanguage?->id ?? 1;

        if ($taxonomy->is_hierarchical) {
            $terms = Term::with(['translations', 'children.translations'])
                ->where('taxonomy_id', $taxonomyId)
                ->whereNull('parent_id')
                ->orderBy('position')
                ->get();
        } else {
            $terms = Term::with('translations')
                ->where('taxonomy_id', $taxonomyId)
                ->orderBy('position')
                ->get();
        }

        return view('contensio::admin.terms.index', [
            'taxonomy'      => $taxonomy,
            'terms'         => $terms,
            'defaultLangId' => $defaultLangId,
        ]);
    }

    public function create(int $taxonomyId)
    {
        $taxonomy = Taxonomy::with('translations')->find($taxonomyId);

        if (! $taxonomy) {
            return redirect()->route('contensio.account.content-types.index')
                ->with('error', 'Taxonomy not found.');
        }

        $languages       = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defaultLanguage = Language::where('is_default', true)->first() ?? $languages->first();
        $defaultLangId   = $defaultLanguage?->id ?? 1;

        $parentOptions = $this->buildParentOptions($taxonomyId, $defaultLangId);

        return view('contensio::admin.terms.form', [
            'term'            => null,
            'taxonomy'        => $taxonomy,
            'languages'       => $languages,
            'defaultLanguage' => $defaultLanguage,
            'existing'        => [],
            'parentOptions'   => $parentOptions,
        ]);
    }

    public function store(Request $request, int $taxonomyId)
    {
        $taxonomy = Taxonomy::find($taxonomyId);

        if (! $taxonomy) {
            return redirect()->route('contensio.account.content-types.index')
                ->with('error', 'Taxonomy not found.');
        }

        $languages       = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defaultLanguage = Language::where('is_default', true)->first() ?? $languages->first();
        $defaultLangId   = $defaultLanguage?->id ?? 1;

        $request->validate([
            "translations.{$defaultLangId}.name" => 'required|string|max:200',
            "translations.{$defaultLangId}.slug" => 'required|string|max:200|alpha_dash',
        ]);

        $slug = $request->input("translations.{$defaultLangId}.slug");
        $name = $request->input("translations.{$defaultLangId}.name");

        $slugExists = TermTranslation::where('language_id', $defaultLangId)
            ->where('slug', $slug)
            ->whereHas('term', fn ($q) => $q->where('taxonomy_id', $taxonomyId))
            ->exists();

        $nameExists = TermTranslation::where('language_id', $defaultLangId)
            ->where('name', $name)
            ->whereHas('term', fn ($q) => $q->where('taxonomy_id', $taxonomyId))
            ->exists();

        if ($slugExists || $nameExists) {
            return back()->withInput()->withErrors(array_filter([
                "translations.{$defaultLangId}.slug" => $slugExists ? 'A term with this slug already exists in this taxonomy.' : null,
                "translations.{$defaultLangId}.name" => $nameExists ? 'A term with this name already exists in this taxonomy.' : null,
            ]));
        }

        $term = Term::create([
            'code'        => Str::random(16),
            'taxonomy_id' => $taxonomyId,
            'parent_id'   => $taxonomy->is_hierarchical ? ($request->input('parent_id') ?: null) : null,
            'position'    => (Term::where('taxonomy_id', $taxonomyId)->max('position') ?? 0) + 1,
            'image_id'    => $request->filled('image_id') ? (int) $request->input('image_id') : null,
        ]);

        foreach ($languages as $lang) {
            $name = $request->input("translations.{$lang->id}.name");
            $slug = $request->input("translations.{$lang->id}.slug");

            if (! $name || ! $slug) {
                continue;
            }

            TermTranslation::create([
                'term_id'     => $term->id,
                'language_id' => $lang->id,
                'name'        => $name,
                'slug'        => $slug,
                'description' => $request->input("translations.{$lang->id}.description") ?: null,
            ]);
        }

        $defaultName = $request->input("translations.{$defaultLangId}.name");

        return redirect()->route('contensio.account.terms.index', $taxonomyId)
            ->with('success', "\"{$defaultName}\" added.");
    }

    public function edit(int $taxonomyId, int $id)
    {
        $taxonomy = Taxonomy::with('translations')->find($taxonomyId);
        $term     = Term::with(['translations', 'image'])->find($id);

        if (! $taxonomy || ! $term || $term->taxonomy_id !== $taxonomyId) {
            return redirect()->route('contensio.account.content-types.index')
                ->with('error', 'Not found.');
        }

        $languages       = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defaultLanguage = Language::where('is_default', true)->first() ?? $languages->first();
        $defaultLangId   = $defaultLanguage?->id ?? 1;

        $existing = [];
        foreach ($term->translations as $trans) {
            $existing[$trans->language_id] = [
                'name'        => $trans->name,
                'slug'        => $trans->slug,
                'description' => $trans->description ?? '',
            ];
        }

        $parentOptions = $this->buildParentOptions($taxonomyId, $defaultLangId, $id);

        return view('contensio::admin.terms.form', [
            'term'            => $term,
            'taxonomy'        => $taxonomy,
            'languages'       => $languages,
            'defaultLanguage' => $defaultLanguage,
            'existing'        => $existing,
            'parentOptions'   => $parentOptions,
        ]);
    }

    public function update(Request $request, int $taxonomyId, int $id)
    {
        $taxonomy = Taxonomy::find($taxonomyId);
        $term     = Term::find($id);

        if (! $taxonomy || ! $term || $term->taxonomy_id !== $taxonomyId) {
            return redirect()->route('contensio.account.content-types.index')
                ->with('error', 'Not found.');
        }

        $languages       = Language::notDisabled()->orderBy('position')->orderBy('id')->get();
        $defaultLanguage = Language::where('is_default', true)->first() ?? $languages->first();
        $defaultLangId   = $defaultLanguage?->id ?? 1;

        $request->validate([
            "translations.{$defaultLangId}.name" => 'required|string|max:200',
            "translations.{$defaultLangId}.slug" => 'required|string|max:200|alpha_dash',
        ]);

        $slug = $request->input("translations.{$defaultLangId}.slug");
        $name = $request->input("translations.{$defaultLangId}.name");

        $slugExists = TermTranslation::where('language_id', $defaultLangId)
            ->where('slug', $slug)
            ->where('term_id', '!=', $id)
            ->whereHas('term', fn ($q) => $q->where('taxonomy_id', $taxonomyId))
            ->exists();

        $nameExists = TermTranslation::where('language_id', $defaultLangId)
            ->where('name', $name)
            ->where('term_id', '!=', $id)
            ->whereHas('term', fn ($q) => $q->where('taxonomy_id', $taxonomyId))
            ->exists();

        if ($slugExists || $nameExists) {
            return back()->withInput()->withErrors(array_filter([
                "translations.{$defaultLangId}.slug" => $slugExists ? 'A term with this slug already exists in this taxonomy.' : null,
                "translations.{$defaultLangId}.name" => $nameExists ? 'A term with this name already exists in this taxonomy.' : null,
            ]));
        }

        $term->update([
            'parent_id' => $taxonomy->is_hierarchical ? ($request->input('parent_id') ?: null) : null,
            'image_id'  => $request->filled('image_id') ? (int) $request->input('image_id') : null,
        ]);

        foreach ($languages as $lang) {
            $name = $request->input("translations.{$lang->id}.name");
            $slug = $request->input("translations.{$lang->id}.slug");

            if (! $name || ! $slug) {
                continue;
            }

            TermTranslation::updateOrCreate(
                ['term_id' => $term->id, 'language_id' => $lang->id],
                [
                    'name'        => $name,
                    'slug'        => $slug,
                    'description' => $request->input("translations.{$lang->id}.description") ?: null,
                ]
            );
        }

        $defaultName = $request->input("translations.{$defaultLangId}.name");

        return redirect()->route('contensio.account.terms.index', $taxonomyId)
            ->with('success', "\"{$defaultName}\" saved.");
    }

    public function destroy(int $taxonomyId, int $id)
    {
        $term = Term::find($id);

        if (! $term || $term->taxonomy_id !== $taxonomyId) {
            return redirect()->route('contensio.account.terms.index', $taxonomyId);
        }

        // Re-parent children to this term's parent before deleting
        Term::where('parent_id', $id)->update(['parent_id' => $term->parent_id]);

        $term->delete();

        return redirect()->route('contensio.account.terms.index', $taxonomyId)
            ->with('success', 'Term deleted.');
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private function buildParentOptions(int $taxonomyId, int $defaultLangId, ?int $excludeId = null): array
    {
        $query = Term::with('translations')
            ->where('taxonomy_id', $taxonomyId)
            ->whereNull('parent_id')
            ->orderBy('position');

        if ($excludeId) {
            $query->where('id', '!=', $excludeId);
        }

        return $query->get()->mapWithKeys(function ($term) use ($defaultLangId) {
            $trans = $term->translations->firstWhere('language_id', $defaultLangId)
                ?? $term->translations->first();
            return [$term->id => $trans?->name ?? "Term #{$term->id}"];
        })->all();
    }
}
