<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Http\Controllers\Admin;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\File;
use Contensio\Support\ThemeOptions;
use Contensio\Support\ThemeRegistry;
use ZipArchive;

class ThemeController extends Controller
{
    /**
     * Serve a theme's screenshot from its public/ directory.
     * Tries screenshot.svg, .png, .jpg, .webp in that order.
     * Accepts the theme identifier via ?theme=vendor/name to sidestep slashes in route params.
     */
    public function screenshot(Request $request)
    {
        $theme = ThemeRegistry::get((string) $request->query('theme', ''));
        if (! $theme || empty($theme['path'])) {
            abort(404);
        }

        foreach (['screenshot.svg', 'screenshot.png', 'screenshot.jpg', 'screenshot.webp'] as $filename) {
            $path = rtrim($theme['path'], '/\\') . '/public/' . $filename;
            if (is_file($path)) {
                return response()->file($path, ['Cache-Control' => 'public, max-age=3600']);
            }
        }

        abort(404);
    }

    /** List all discovered themes. */
    public function index()
    {
        $themes     = ThemeRegistry::all();
        $activeName = ThemeRegistry::activeName();

        return view('contensio::admin.themes.index', compact('themes', 'activeName'));
    }

    /** Activate a theme. */
    public function activate(Request $request)
    {
        $request->validate(['theme' => 'required|string']);

        $name = $request->input('theme');

        if (! ThemeRegistry::get($name)) {
            return back()->withErrors(['theme' => 'Theme not found.']);
        }

        ThemeRegistry::activate($name);

        return back()->with('success', 'Theme activated. Reload the site to see the changes.');
    }

    /**
     * Install a theme from an uploaded ZIP file.
     *
     * The ZIP must contain a theme.json at its root (or one folder deep),
     * with a "name" field in "vendor/package" format.
     */
    public function install(Request $request)
    {
        $request->validate([
            'zip' => 'required|file|mimes:zip|max:51200', // 50 MB
        ]);

        $zip  = new ZipArchive;
        $file = $request->file('zip');

        if ($zip->open($file->getRealPath()) !== true) {
            return back()->withErrors(['zip' => 'Could not open the ZIP file.']);
        }

        // Find theme.json inside the ZIP (root or one folder deep)
        $manifestIndex = $zip->locateName('theme.json');
        if ($manifestIndex === false) {
            // Try one level deep: {folder}/theme.json
            for ($i = 0; $i < $zip->numFiles; $i++) {
                $entry = $zip->getNameIndex($i);
                if (preg_match('#^[^/]+/theme\.json$#', $entry)) {
                    $manifestIndex = $i;
                    break;
                }
            }
        }

        if ($manifestIndex === false) {
            $zip->close();
            return back()->withErrors(['zip' => 'No theme.json found in the ZIP.']);
        }

        $meta = json_decode($zip->getFromIndex($manifestIndex), true);
        if (empty($meta['name']) || ! preg_match('#^[a-z0-9_-]+/[a-z0-9_-]+$#', $meta['name'])) {
            $zip->close();
            return back()->withErrors(['zip' => 'Invalid theme name in theme.json. Must be "vendor/name".']);
        }

        $themeName  = $meta['name'];
        $themesRoot = base_path('themes');
        $targetPath = $themesRoot . '/' . $themeName;

        // Wipe any previous installation of the same theme
        if (is_dir($targetPath)) {
            File::deleteDirectory($targetPath);
        }

        File::ensureDirectoryExists($targetPath);
        $zip->extractTo($targetPath);
        $zip->close();

        // If the ZIP contained a single wrapper folder, flatten it
        $entries = array_diff(scandir($targetPath), ['.', '..']);
        if (count($entries) === 1) {
            $inner = $targetPath . '/' . reset($entries);
            if (is_dir($inner)) {
                foreach (scandir($inner) as $item) {
                    if ($item === '.' || $item === '..') continue;
                    rename("{$inner}/{$item}", "{$targetPath}/{$item}");
                }
                rmdir($inner);
            }
        }

        return back()->with('success', "Theme \"{$themeName}\" installed successfully.");
    }

    /** Uninstall a local theme (cannot remove built-in or Composer themes). */
    public function uninstall(Request $request)
    {
        $request->validate(['theme' => 'required|string']);

        $name  = $request->input('theme');
        $theme = ThemeRegistry::get($name);

        if (! $theme) {
            return back()->withErrors(['theme' => 'Theme not found.']);
        }

        if ($theme['source'] !== 'local') {
            return back()->withErrors(['theme' => 'Only locally installed themes can be removed.']);
        }

        if (ThemeRegistry::isActive($name)) {
            return back()->withErrors(['theme' => 'Cannot remove the active theme. Activate another theme first.']);
        }

        File::deleteDirectory($theme['path']);

        return back()->with('success', "Theme \"{$name}\" has been removed.");
    }

    /**
     * Customize page — dynamic form built from the active theme's settings schema.
     */
    public function customize()
    {
        $name     = ThemeRegistry::activeName();
        $theme    = ThemeRegistry::get($name);

        if (! $theme) {
            return redirect()
                ->route('contensio.account.themes.index')
                ->withErrors(['theme' => 'Active theme not found.']);
        }

        $sections = ThemeOptions::schema($name);
        $values   = ThemeOptions::all($name);

        return view('contensio::admin.themes.customize', compact('name', 'theme', 'sections', 'values'));
    }

    /**
     * Save customization values. Walks the schema so unknown keys from the
     * request are ignored and each field is cast to its declared type.
     */
    public function saveCustomize(Request $request)
    {
        $name     = ThemeRegistry::activeName();
        $sections = ThemeOptions::schema($name);

        $values = [];
        foreach ($sections as $section) {
            foreach ($section['fields'] ?? [] as $field) {
                $key = $field['key'] ?? null;
                if (! $key) {
                    continue;
                }
                $type = $field['type'] ?? 'text';
                $raw  = $request->input("options.{$key}");

                $values[$key] = match ($type) {
                    'checkbox'        => $request->boolean("options.{$key}"),
                    'number', 'range' => is_numeric($raw) ? 0 + $raw : ($field['default'] ?? 0),
                    default           => is_scalar($raw) || is_null($raw) ? (string) ($raw ?? '') : '',
                };
            }
        }

        ThemeOptions::save($name, $values);

        return redirect()
            ->route('contensio.account.themes.customize')
            ->with('success', 'Theme customization saved.');
    }

    /** Reset all customizations to the theme's declared defaults. */
    public function resetCustomize()
    {
        $name = ThemeRegistry::activeName();
        ThemeOptions::reset($name);

        return redirect()
            ->route('contensio.account.themes.customize')
            ->with('success', 'Theme reset to default settings.');
    }
}
