<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Services\Install;

class EnvWriter
{
    private string $path;

    public function __construct()
    {
        $this->path = base_path('.env');
    }

    public function set(string $key, string $value): void
    {
        $content = file_exists($this->path)
            ? file_get_contents($this->path)
            : file_get_contents(base_path('.env.example'));

        // Quote values that contain spaces
        $escaped = str_contains($value, ' ') ? '"' . $value . '"' : $value;

        if (preg_match('/^' . preg_quote($key, '/') . '=/m', $content)) {
            // Key exists — replace it
            $content = preg_replace(
                '/^' . preg_quote($key, '/') . '=.*/m',
                $key . '=' . $escaped,
                $content
            );
        } else {
            // Key missing — append it
            $content .= PHP_EOL . $key . '=' . $escaped;
        }

        file_put_contents($this->path, $content);
    }

    public function setMany(array $values): void
    {
        foreach ($values as $key => $value) {
            $this->set($key, (string) $value);
        }
    }

    public function get(string $key): ?string
    {
        if (!file_exists($this->path)) {
            return null;
        }

        $content = file_get_contents($this->path);

        if (preg_match('/^' . preg_quote($key, '/') . '=(.*)$/m', $content, $matches)) {
            return trim($matches[1], '"');
        }

        return null;
    }
}
