<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Cms\Services\Install;

class RequirementsChecker
{
    private const MIN_PHP = '8.2.0';

    private const REQUIRED_EXTENSIONS = [
        'pdo',
        'mbstring',
        'openssl',
        'tokenizer',
        'xml',
        'ctype',
        'json',
        'bcmath',
        'fileinfo',
    ];

    private const RECOMMENDED_EXTENSIONS = [
        'gd',
        'imagick',
    ];

    private const WRITABLE_PATHS = [
        'storage/app',
        'storage/framework',
        'storage/logs',
        'bootstrap/cache',
    ];

    private const MIN_DISK_MB = 100;

    public function check(): array
    {
        return [
            'php'        => $this->checkPhp(),
            'extensions' => $this->checkExtensions(),
            'permissions'=> $this->checkPermissions(),
            'disk'       => $this->checkDisk(),
        ];
    }

    public function passes(): bool
    {
        $results = $this->check();

        return $results['php']['passes']
            && $results['extensions']['passes']
            && $results['permissions']['passes']
            && $results['disk']['passes'];
    }

    private function checkPhp(): array
    {
        $passes = version_compare(PHP_VERSION, self::MIN_PHP, '>=');

        return [
            'passes'   => $passes,
            'current'  => PHP_VERSION,
            'required' => self::MIN_PHP,
            'message'  => $passes
                ? 'PHP ' . PHP_VERSION
                : 'PHP ' . PHP_VERSION . ' is installed. Version ' . self::MIN_PHP . ' or higher is required.',
        ];
    }

    private function checkExtensions(): array
    {
        $required = [];
        $recommended = [];
        $allPasses = true;

        foreach (self::REQUIRED_EXTENSIONS as $ext) {
            $loaded = extension_loaded($ext);
            if (!$loaded) {
                $allPasses = false;
            }
            $required[] = [
                'name'    => $ext,
                'passes'  => $loaded,
                'message' => $loaded
                    ? null
                    : 'Ask your hosting provider to enable the ' . $ext . ' PHP extension.',
            ];
        }

        foreach (self::RECOMMENDED_EXTENSIONS as $ext) {
            $loaded = extension_loaded($ext);
            $recommended[] = [
                'name'    => $ext,
                'passes'  => $loaded,
                'message' => $loaded
                    ? null
                    : 'Recommended for image processing. Ask your hosting provider to enable the ' . $ext . ' PHP extension.',
            ];
        }

        return [
            'passes'      => $allPasses,
            'required'    => $required,
            'recommended' => $recommended,
        ];
    }

    private function checkPermissions(): array
    {
        $items = [];
        $allPasses = true;

        foreach (self::WRITABLE_PATHS as $path) {
            $fullPath = base_path($path);
            $writable = is_writable($fullPath);

            if (!$writable) {
                $allPasses = false;
            }

            $items[] = [
                'path'    => $path,
                'passes'  => $writable,
                'message' => $writable
                    ? null
                    : 'The ' . $path . ' folder must be writable. Ask your hosting provider to set permissions to 755.',
            ];
        }

        // Check .env file
        $envPath = base_path('.env');
        $envExists = file_exists($envPath);
        $envWritable = $envExists ? is_writable($envPath) : is_writable(base_path());

        if (!$envWritable) {
            $allPasses = false;
        }

        $items[] = [
            'path'    => '.env',
            'passes'  => $envWritable,
            'message' => $envWritable
                ? null
                : 'The .env file must be writable. Ask your hosting provider to make this file writable.',
        ];

        return [
            'passes' => $allPasses,
            'items'  => $items,
        ];
    }

    private function checkDisk(): array
    {
        $free = disk_free_space(base_path());
        $freeMb = $free !== false ? (int) ($free / 1024 / 1024) : 0;
        $passes = $freeMb >= self::MIN_DISK_MB;

        return [
            'passes'  => $passes,
            'free_mb' => $freeMb,
            'message' => $passes
                ? $freeMb . ' MB available'
                : 'Only ' . $freeMb . ' MB of disk space available. At least ' . self::MIN_DISK_MB . ' MB is required.',
        ];
    }
}
