<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Cms\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;

class SeedBlockTypesCommand extends Command
{
    protected $signature = 'cms:seed-blocks
                            {--fresh : Deactivate all existing core types before re-seeding}';

    protected $description = 'Seed (or re-seed) core block types into the block_types table';

    public function handle(): int
    {
        $definitions = config('cms.blocks', []);

        if (empty($definitions)) {
            $this->error('No block type definitions found in config(\'cms.blocks\').');
            return self::FAILURE;
        }

        if ($this->option('fresh')) {
            DB::table('block_types')->where('is_core', true)->update(['is_active' => false]);
            $this->line('  <fg=yellow>Deactivated existing core block types.</>');
        }

        $this->line('');
        $this->line('  Seeding block types...');
        $this->line('');

        $seeded  = 0;
        $updated = 0;

        foreach ($definitions as $name => $def) {
            $exists = DB::table('block_types')->where('name', $name)->exists();

            DB::table('block_types')->updateOrInsert(
                ['name' => $name],
                [
                    'label'       => $def['label']       ?? ucfirst($name),
                    'icon'        => $def['icon']         ?? null,
                    'description' => $def['description']  ?? null,
                    'category'    => $def['category']     ?? 'text',
                    'is_core'     => true,
                    'is_active'   => true,
                    'sort_order'  => $def['sort_order']   ?? 0,
                    'updated_at'  => now(),
                    'created_at'  => now(),
                ]
            );

            $label  = $def['label'] ?? ucfirst($name);
            $cat    = $def['category'] ?? 'text';

            if ($exists) {
                $this->line("  <fg=blue>UPDATED</> <fg=white>{$name}</> <fg=gray>({$cat}) — {$label}</>");
                $updated++;
            } else {
                $this->line("  <fg=green>CREATED</> <fg=white>{$name}</> <fg=gray>({$cat}) — {$label}</>");
                $seeded++;
            }
        }

        $this->line('');
        $this->info("Done. {$seeded} created, {$updated} updated.");
        $this->line('');

        return self::SUCCESS;
    }
}
