<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Http\Controllers\Frontend;

use Illuminate\Routing\Controller;
use Contensio\Models\Comment;
use Contensio\Models\Content;
use Contensio\Models\ContentTranslation;
use Contensio\Models\ContentType;
use Contensio\Models\Language;
use Contensio\Models\Setting;

class FrontendController extends Controller
{
    public function home()
    {
        $site = $this->siteConfig();
        $lang = $this->defaultLang();

        $postType = ContentType::where('name', 'post')->first();
        $posts    = $postType
            ? Content::where('content_type_id', $postType->id)
                ->where('status', 'published')
                ->with(['translations' => fn ($q) => $q->where('language_id', $lang?->id), 'featuredImage'])
                ->latest('published_at')
                ->limit(6)
                ->get()
            : collect();

        return view('theme::home', compact('site', 'posts', 'lang'));
    }

    public function page(string $slug)
    {
        $lang = $this->defaultLang();

        $translation = ContentTranslation::where('slug', $slug)
            ->where('language_id', $lang?->id)
            ->with(['content.featuredImage'])
            ->first();

        if (! $translation || $translation->content?->status !== 'published') {
            abort(404);
        }

        $content = $translation->content;
        $site    = $this->siteConfig();

        return view('theme::page', compact('translation', 'content', 'site', 'lang'));
    }

    public function archive()
    {
        $lang     = $this->defaultLang();
        $site     = $this->siteConfig();
        $postType = ContentType::where('name', 'post')->first();

        $posts = $postType
            ? Content::where('content_type_id', $postType->id)
                ->where('status', 'published')
                ->with(['translations' => fn ($q) => $q->where('language_id', $lang?->id), 'author', 'featuredImage'])
                ->latest('published_at')
                ->paginate(12)
            : collect();

        return view('theme::archive', compact('posts', 'site', 'lang'));
    }

    public function post(string $slug)
    {
        $lang     = $this->defaultLang();
        $postType = ContentType::where('name', 'post')->first();

        if (! $postType) {
            abort(404);
        }

        $translation = ContentTranslation::where('slug', $slug)
            ->where('language_id', $lang?->id)
            ->whereHas('content', fn ($q) => $q->where('content_type_id', $postType->id)->where('status', 'published'))
            ->with(['content.author', 'content.featuredImage'])
            ->first();

        if (! $translation) {
            abort(404);
        }

        $content = $translation->content;
        $site    = $this->siteConfig();

        $commentsEnabled = (bool) Setting::where('module', 'comments')
            ->where('setting_key', 'comments_enabled')
            ->value('value');

        $comments = $commentsEnabled && $content->allow_comments
            ? Comment::where('content_id', $content->id)
                ->where('status', Comment::STATUS_APPROVED)
                ->whereNull('parent_id')
                ->with([
                    'author',
                    'replies' => fn ($q) => $q->where('status', Comment::STATUS_APPROVED)->oldest(),
                    'replies.author',
                ])
                ->oldest()
                ->get()
            : collect();

        return view('theme::post', compact('translation', 'content', 'site', 'lang', 'comments', 'commentsEnabled'));
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private function siteConfig(): array
    {
        $settings = Setting::where('module', 'core')
            ->whereIn('setting_key', ['site_name', 'site_tagline'])
            ->pluck('value', 'setting_key');

        return [
            'name'    => $settings['site_name']    ?? config('app.name'),
            'tagline' => $settings['site_tagline'] ?? '',
        ];
    }

    private function defaultLang(): ?Language
    {
        return Language::where('is_default', true)->first()
            ?? Language::where('status', '!=', 'disabled')->orderBy('position')->first();
    }
}
