<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\MorphToMany;

class ContentType extends Model
{
    protected $guarded = [];

    protected $casts = [
        'has_slug'           => 'boolean',
        'has_editor'         => 'boolean',
        'has_excerpt'        => 'boolean',
        'has_featured_image' => 'boolean',
        'has_categories'     => 'boolean',
        'has_tags'           => 'boolean',
        'has_comments'       => 'boolean',
        'has_seo'            => 'boolean',
        'has_autosave'       => 'boolean',
        'is_hierarchical'    => 'boolean',
        'is_system'          => 'boolean',
        'position'           => 'integer',
    ];

    public function translations(): HasMany
    {
        return $this->hasMany(ContentTypeTranslation::class);
    }

    public function meta(): HasMany
    {
        return $this->hasMany(ContentTypeMeta::class);
    }

    /** Field groups attached to this content type (polymorphic). */
    public function fieldGroups(): MorphToMany
    {
        return $this->morphToMany(
            FieldGroup::class,
            'attachable',
            'field_group_attachments'
        )->withPivot('position')->withTimestamps()->orderBy('field_group_attachments.position');
    }

    public function contents(): HasMany
    {
        return $this->hasMany(Content::class);
    }

    public function taxonomies(): BelongsToMany
    {
        return $this->belongsToMany(Taxonomy::class, 'content_type_taxonomies');
    }

    /**
     * Return the image size configuration for this content type.
     * Reads from content_type_meta (key: image_sizes) or falls back to
     * the config defaults with per-type activation rules applied.
     */
    public function getImageSizes(): array
    {
        $meta = $this->meta()->where('meta_key', 'image_sizes')->first();

        if ($meta && $meta->meta_value) {
            return json_decode($meta->meta_value, true) ?? [];
        }

        return $this->defaultImageSizes();
    }

    /**
     * Build the default image sizes for this content type from config,
     * applying per-preset default_for rules to set the initial active state.
     */
    public function defaultImageSizes(): array
    {
        $presets = config('contensio.image_sizes', []);
        $name    = $this->name;

        return collect($presets)
            ->map(function (array $preset, string $key) use ($name): array {
                $defaultFor = $preset['default_for'] ?? [];
                $active     = in_array('*', $defaultFor) || in_array($name, $defaultFor);

                return [
                    'key'        => $key,
                    'label'      => $preset['label'],
                    'width'      => $preset['width'],
                    'height'     => $preset['height'],
                    'fit'        => $preset['fit'],
                    'quality'    => $preset['quality'],
                    'background' => $preset['background'] ?? '#ffffff',
                    'active'     => $active,
                ];
            })
            ->values()
            ->all();
    }
}
