<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Cms\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;

class Content extends Model
{
    public const STATUS_DRAFT     = 'draft';
    public const STATUS_PUBLISHED = 'published';
    public const STATUS_SCHEDULED = 'scheduled';
    public const STATUS_TRASHED   = 'trashed';

    protected $guarded = [];

    protected $casts = [
        'allow_comments' => 'boolean',
        'position'       => 'integer',
        'published_at'   => 'datetime',
        'blocks'         => 'array',
    ];

    public function contentType(): BelongsTo
    {
        return $this->belongsTo(ContentType::class);
    }

    public function author(): BelongsTo
    {
        return $this->belongsTo(\App\Models\User::class, 'author_id');
    }

    public function featuredImage(): BelongsTo
    {
        return $this->belongsTo(Media::class, 'featured_image_id');
    }

    public function parent(): BelongsTo
    {
        return $this->belongsTo(Content::class, 'parent_id');
    }

    public function children(): HasMany
    {
        return $this->hasMany(Content::class, 'parent_id')->orderBy('position');
    }

    public function translations(): HasMany
    {
        return $this->hasMany(ContentTranslation::class);
    }

    public function fieldValues(): HasMany
    {
        return $this->hasMany(ContentFieldValue::class);
    }

    /**
     * Retrieve the value of a custom field by its key, for the given language.
     *
     * Looks up the field across all groups attached to this content's type.
     * Translatable fields resolve by language_id; non-translatable fields
     * match any language_id (stored as null or the first-saved language).
     *
     * Returns the raw stored value (string, or JSON-decoded array for
     * multi-value types). Type-specific casting happens in themes/helpers.
     *
     * @param  string  $key       Field key, e.g. 'price'
     * @param  int|null  $languageId  Defaults to current app locale's language
     * @return mixed
     */
    public function field(string $key, ?int $languageId = null)
    {
        static $resolved = [];

        $cacheKey = $this->id . ':' . $key . ':' . ($languageId ?? 'current');
        if (array_key_exists($cacheKey, $resolved)) {
            return $resolved[$cacheKey];
        }

        // Find the field via the content type's attached groups
        $field = Field::where('key', $key)
            ->whereHas('group.contentTypes', fn ($q) => $q->where('content_types.id', $this->content_type_id))
            ->first();

        if (! $field) {
            return $resolved[$cacheKey] = null;
        }

        $query = $this->fieldValues()->where('field_id', $field->id);

        if ($field->is_translatable) {
            $langId = $languageId ?? Language::where('code', app()->getLocale())->value('id');
            $query->where('language_id', $langId);
        }

        $value = $query->value('value');

        // Decode JSON for multi-value types
        if (in_array($field->type, ['multi-select', 'media'], true) && is_string($value)) {
            $decoded = json_decode($value, true);
            $value = $decoded ?: $value;
        }

        return $resolved[$cacheKey] = $value;
    }

    public function meta(): HasMany
    {
        return $this->hasMany(ContentMeta::class);
    }

    public function terms(): BelongsToMany
    {
        return $this->belongsToMany(Term::class, 'content_terms');
    }

    public function comments(): HasMany
    {
        return $this->hasMany(Comment::class);
    }

    public function autosave(): HasOne
    {
        return $this->hasOne(Autosave::class);
    }
}
