<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Language extends Model
{
    protected $guarded = [];

    protected $casts = [
        'is_default' => 'boolean',
        'position'   => 'integer',
    ];

    /** Active + inactive (anything visible to admins). */
    public function scopeNotDisabled($query)
    {
        return $query->where('status', '!=', 'disabled');
    }

    /** Active only (visible on frontend). */
    public function scopeActive($query)
    {
        return $query->where('status', 'active');
    }

    public function contentTypeTranslations(): HasMany
    {
        return $this->hasMany(ContentTypeTranslation::class);
    }

    public function contentTranslations(): HasMany
    {
        return $this->hasMany(ContentTranslation::class);
    }

    public function termTranslations(): HasMany
    {
        return $this->hasMany(TermTranslation::class);
    }

    public function mediaTranslations(): HasMany
    {
        return $this->hasMany(MediaTranslation::class);
    }

    public function menuTranslations(): HasMany
    {
        return $this->hasMany(MenuTranslation::class);
    }

    public function roleTranslations(): HasMany
    {
        return $this->hasMany(RoleTranslation::class);
    }

    public function settingTranslations(): HasMany
    {
        return $this->hasMany(SettingTranslation::class);
    }
}
