<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\MorphTo;

/**
 * Polymorphic metadata table shared across all plugins.
 *
 * Each row belongs to any model (Post, User, Term, …) via the morph columns,
 * and optionally records which plugin owns the row so it can be cleaned up on
 * uninstall.
 *
 * Plugins should interact with this model directly rather than creating their
 * own per-feature metadata tables for simple key→value storage.
 */
class Meta extends Model
{
    protected $table = 'contensio_meta';

    protected $guarded = [];

    /* ── Relationships ─────────────────────────────────────────────────── */

    public function metable(): MorphTo
    {
        return $this->morphTo();
    }

    /* ── Scopes ────────────────────────────────────────────────────────── */

    public function scopeForPlugin(Builder $query, string $plugin): Builder
    {
        return $query->where('plugin', $plugin);
    }

    public function scopeForKey(Builder $query, string $key): Builder
    {
        return $query->where('meta_key', $key);
    }

    /* ── Static helpers ────────────────────────────────────────────────── */

    /**
     * Get a single meta value for a model instance.
     */
    public static function getValue(Model $model, string $key, mixed $default = null): mixed
    {
        $row = static::where('metable_type', get_class($model))
            ->where('metable_id', $model->getKey())
            ->where('meta_key', $key)
            ->value('meta_value');

        return $row !== null ? $row : $default;
    }

    /**
     * Set a meta value for a model instance (upsert).
     */
    public static function setValue(Model $model, string $key, mixed $value, ?string $plugin = null): void
    {
        static::updateOrCreate(
            [
                'metable_type' => get_class($model),
                'metable_id'   => $model->getKey(),
                'meta_key'     => $key,
            ],
            [
                'meta_value' => $value,
                'plugin'     => $plugin,
            ]
        );
    }

    /**
     * Increment a numeric meta value atomically.
     */
    public static function increment(Model $model, string $key, int $amount = 1, ?string $plugin = null): void
    {
        $existing = static::where('metable_type', get_class($model))
            ->where('metable_id', $model->getKey())
            ->where('meta_key', $key)
            ->first();

        if ($existing) {
            $existing->increment('meta_value', $amount);
        } else {
            static::create([
                'metable_type' => get_class($model),
                'metable_id'   => $model->getKey(),
                'meta_key'     => $key,
                'meta_value'   => $amount,
                'plugin'       => $plugin,
            ]);
        }
    }
}
