<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

/**
 * Generic entries table shared across all plugins.
 *
 * Replaces the need for simple per-plugin tables. Each plugin stores its items
 * here with a unique `plugin` + `type` combination. The `data` JSON column holds
 * plugin-specific fields so each plugin defines its own schema without migrations.
 *
 * Examples:
 *   plugin=contensio/plugin-faq,          type=group → FAQ group
 *   plugin=contensio/plugin-faq,          type=item  → FAQ question/answer (parent_id = group id)
 *   plugin=contensio/plugin-team,         type=member
 *   plugin=contensio/plugin-testimonials, type=testimonial
 *   plugin=contensio/plugin-changelog,    type=entry
 *   plugin=contensio/plugin-downloads,    type=file  (post_id = the post it belongs to)
 */
class PluginEntry extends Model
{
    protected $table = 'contensio_plugin_entries';

    protected $guarded = [];

    protected $casts = [
        'data'       => 'array',
        'sort_order' => 'integer',
        'parent_id'  => 'integer',
        'post_id'    => 'integer',
        'user_id'    => 'integer',
    ];

    /* ── Scopes ────────────────────────────────────────────────────────── */

    public function scopeForPlugin(Builder $query, string $plugin): Builder
    {
        return $query->where('plugin', $plugin);
    }

    public function scopeOfType(Builder $query, string $type): Builder
    {
        return $query->where('type', $type);
    }

    public function scopeActive(Builder $query): Builder
    {
        return $query->where('status', 'active');
    }

    public function scopeForPost(Builder $query, int $postId): Builder
    {
        return $query->where('post_id', $postId);
    }

    public function scopeOrdered(Builder $query): Builder
    {
        return $query->orderBy('sort_order')->orderBy('id');
    }

    /* ── Helpers ───────────────────────────────────────────────────────── */

    public function isActive(): bool
    {
        return $this->status === 'active';
    }

    /** Read a field from the JSON data blob, with an optional default. */
    public function get(string $key, mixed $default = null): mixed
    {
        return $this->data[$key] ?? $default;
    }

    /** Children of this entry (e.g. FAQ items within a group). */
    public function children()
    {
        return $this->hasMany(static::class, 'parent_id')->orderBy('sort_order');
    }

    /** Parent of this entry (e.g. the FAQ group for an item). */
    public function parent()
    {
        return $this->belongsTo(static::class, 'parent_id');
    }
}
