<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Cms;

use Contensio\Cms\Console\Commands\InstallCommand;
use Contensio\Cms\Console\Commands\SeedBlockTypesCommand;
use Contensio\Cms\Http\Middleware\AdminAuthenticate;
use Contensio\Cms\Http\Middleware\RequireAdminRole;
use Contensio\Cms\Models\ContentType;
use Contensio\Cms\Services\Install\EnvWriter;
use Contensio\Cms\Services\Install\RequirementsChecker;
use Contensio\Cms\Support\ThemeRegistry;
use Illuminate\Foundation\Console\AboutCommand;
use Illuminate\Support\Facades\View;
use Illuminate\Support\ServiceProvider;

class CmsServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        $this->mergeConfigFrom(__DIR__ . '/../config/cms.php', 'cms');

        // Autoload global helpers (theme_asset(), etc.)
        require_once __DIR__ . '/helpers.php';

        // Register core block type definitions.
        // Plugins can extend this by merging into 'cms.blocks' in their own service providers.
        $this->app['config']->set('cms.blocks', array_merge(
            require __DIR__ . '/../config/blocks.php',
            $this->app['config']->get('cms.blocks', [])
        ));

        $this->app->singleton(RequirementsChecker::class);
        $this->app->singleton(EnvWriter::class);
    }

    public function boot(): void
    {
        $this->loadMigrationsFrom(__DIR__ . '/../database/migrations');
        $this->loadViewsFrom(__DIR__ . '/../resources/views', 'cms');
        $this->loadTranslationsFrom(__DIR__ . '/../lang', 'cms');

        $this->app['router']->aliasMiddleware('cms.auth', AdminAuthenticate::class);
        $this->app['router']->aliasMiddleware('cms.admin', RequireAdminRole::class);

        // Always load install routes — the controller guards each step internally.
        // This ensures /install/complete is reachable after storeAccount() writes
        // CMS_INSTALLED=true and redirects (which would be a new request).
        $this->loadRoutesFrom(__DIR__ . '/../routes/install.php');

        if ($this->isInstalled()) {
            $this->loadRoutesFrom(__DIR__ . '/../routes/web.php');

            // Discover all themes (built-in, local, Composer)
            ThemeRegistry::discover();

            // Boot the active theme's service provider (Composer themes only)
            $active = ThemeRegistry::active();
            if ($active && ($active['source'] ?? '') === 'composer' && ! empty($active['provider'])) {
                $this->app->register($active['provider']);
            }

            // Register the theme:: view namespace once all providers have booted
            $this->app->booted(function () {
                $active = ThemeRegistry::active();
                if ($active && is_dir($active['viewPath'])) {
                    view()->addNamespace('theme', $active['viewPath']);
                }
            });

            // Share custom content types with the admin layout for the sidebar
            View::composer('cms::admin.layout', function ($view) {
                try {
                    $view->with('customContentTypes',
                        ContentType::where('is_system', false)
                            ->with('translations')
                            ->orderBy('id')
                            ->get()
                    );
                } catch (\Exception $e) {
                    $view->with('customContentTypes', collect());
                }
            });
        }

        if ($this->app->runningInConsole()) {
            $this->commands([
                InstallCommand::class,
                SeedBlockTypesCommand::class,
            ]);

            $this->publishes([
                __DIR__ . '/../config/cms.php' => config_path('cms.php'),
            ], 'cms-config');

            $this->publishes([
                __DIR__ . '/../resources/views' => resource_path('views/vendor/cms'),
            ], 'cms-views');

            $this->publishes([
                __DIR__ . '/../public' => public_path('vendor/cms'),
            ], 'cms-assets');

            $this->publishes([
                __DIR__ . '/../lang' => $this->app->langPath('vendor/cms'),
            ], 'cms-lang');

            $this->publishesMigrations([
                __DIR__ . '/../database/migrations' => database_path('migrations'),
            ], 'cms-migrations');
        }

        AboutCommand::add('Contensio', fn () => [
            'Version'   => '1.0.0',
            'Installed' => $this->isInstalled() ? 'Yes' : 'No',
        ]);
    }

    private function isInstalled(): bool
    {
        return (bool) env('CMS_INSTALLED', false);
    }
}
