<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio;

use Contensio\Console\Commands\BackupCommand;
use Contensio\Console\Commands\InstallCommand;
use Contensio\Console\Commands\PublishScheduledContent;
use Contensio\Console\Commands\RestoreCommand;
use Contensio\Console\Commands\SeedBlockTypesCommand;
use Illuminate\Console\Scheduling\Schedule;
use Contensio\Http\Middleware\AdminAuthenticate;
use Contensio\Http\Middleware\HandleRedirects;
use Contensio\Http\Middleware\RequireAdminRole;
use Contensio\Http\Middleware\RequirePermission;
use Contensio\Http\Middleware\TrackUserActivity;
use Contensio\Models\ContentType;
use Contensio\Services\Install\EnvWriter;
use Contensio\Services\Install\Installer;
use Contensio\Services\Install\RequirementsChecker;
use Contensio\Support\AccessControl;
use Contensio\Support\AdminNavigation;
use Contensio\Support\WidgetArea;
use Contensio\Support\WidgetRegistry;
use Contensio\Widgets\CategoriesWidget;
use Contensio\Widgets\CustomHtmlWidget;
use Contensio\Widgets\LatestPostsWidget;
use Contensio\Widgets\RecentCommentsWidget;
use Contensio\Widgets\SearchBoxWidget;
use Contensio\Widgets\TagCloudWidget;
use Contensio\Support\EmailConfig;
use Contensio\Support\FortifyIntegration;
use Contensio\Models\Language;
use Contensio\Support\PluginRegistry;
use Contensio\Support\SiteConfig;
use Contensio\Support\ThemeRegistry;
use Illuminate\Foundation\Console\AboutCommand;
use Illuminate\Support\Facades\View;
use Illuminate\Support\ServiceProvider;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class ContensioServiceProvider extends ServiceProvider
{
    /** Canonical version — updated on every release. */
    const VERSION = '2.0.0';

    /**
     * Returns the installed version of the core package.
     * Reads from Composer's runtime API; falls back to the VERSION constant
     * in dev/git installs where no Composer version tag is recorded.
     */
    public static function version(): string
    {
        try {
            $v = \Composer\InstalledVersions::getPrettyVersion('contensio/contensio');
            if ($v && $v !== 'dev-main' && $v !== 'dev-master') {
                return ltrim($v, 'v');
            }
        } catch (\Throwable) {}

        return self::VERSION;
    }

    public function register(): void
    {
        $this->mergeConfigFrom(__DIR__ . '/../config/contensio.php', 'contensio');

        // Autoload global helpers (theme_asset(), etc.)
        require_once __DIR__ . '/helpers.php';

        // Register core block type definitions.
        // Plugins can extend this by merging into 'contensio.blocks' in their own service providers.
        $this->app['config']->set('contensio.blocks', array_merge(
            require __DIR__ . '/../config/blocks.php',
            $this->app['config']->get('contensio.blocks', [])
        ));

        $this->app->singleton(RequirementsChecker::class);
        $this->app->singleton(EnvWriter::class);
        $this->app->singleton(Installer::class);
    }

    public function boot(): void
    {
        $this->loadMigrationsFrom(__DIR__ . '/../database/migrations');
        $this->loadViewsFrom(__DIR__ . '/../resources/views', 'contensio');
        $this->loadTranslationsFrom(__DIR__ . '/../lang', 'contensio');

        $this->app['router']->aliasMiddleware('contensio.auth', AdminAuthenticate::class);
        $this->app['router']->aliasMiddleware('contensio.admin', RequireAdminRole::class);
        $this->app['router']->aliasMiddleware('contensio.permission', RequirePermission::class);
        $this->app['router']->pushMiddlewareToGroup('web', TrackUserActivity::class);

        // Global: serve admin-configured URL redirects on every public request.
        // Prepended so it runs before route resolution — an existing page with
        // the same URL is still overridden by a matching redirect (admin intent wins).
        $this->app['router']->prependMiddlewareToGroup('web', HandleRedirects::class);

        // Always load install routes — the controller guards each step internally.
        // This ensures /install/complete is reachable after storeAccount() writes
        // CONTENSIO_INSTALLED=true and redirects (which would be a new request).
        $this->loadRoutesFrom(__DIR__ . '/../routes/install.php');

        if ($this->isInstalled()) {
            $this->loadRoutesFrom(__DIR__ . '/../routes/web.php');

            // Overlay stored email/SMTP settings onto Laravel's mail config before
            // anything else that might send mail (Fortify, plugins, etc.).
            try {
                EmailConfig::apply();
            } catch (\Throwable) {
                // Settings table may not exist during fresh install
            }

            // Wire Fortify (password reset + email verification views) into Contensio.
            // Must run during boot so view callbacks are in place before Fortify resolves routes.
            FortifyIntegration::configure($this->app);

            // Ensure Fortify's service provider is loaded — this defines the named
            // routes (password.request, password.reset, verification.*, etc.) that
            // our views reference. Users don't need to add it to their own
            // bootstrap/providers.php manually.
            if (class_exists(\Laravel\Fortify\FortifyServiceProvider::class)) {
                $this->app->register(\Laravel\Fortify\FortifyServiceProvider::class);
            }

            // Seed core permissions + roles on first boot. Idempotent —
            // running this every boot is safe; subsequent calls are effectively no-ops.
            try {
                if (! AccessControl::isSeeded()) {
                    AccessControl::seedCoreDefaults();
                }
            } catch (\Throwable) {
                // Table may not exist yet during migrations — skip silently
            }

            // Register core widget types.
            // Plugins add their own types via WidgetRegistry::register() in their service providers.
            WidgetRegistry::register('latest-posts',     LatestPostsWidget::class);
            WidgetRegistry::register('categories',       CategoriesWidget::class);
            WidgetRegistry::register('tag-cloud',        TagCloudWidget::class);
            WidgetRegistry::register('search-box',       SearchBoxWidget::class);
            WidgetRegistry::register('custom-html',      CustomHtmlWidget::class);
            WidgetRegistry::register('recent-comments',  RecentCommentsWidget::class);

            // Discover all themes (built-in, local, Composer)
            ThemeRegistry::discover();

            // Boot the active theme's service provider (Composer themes only)
            $active = ThemeRegistry::active();
            if ($active && ($active['source'] ?? '') === 'composer' && ! empty($active['provider'])) {
                $this->app->register($active['provider']);
            }

            // Register the theme:: view namespace once all providers have booted.
            // The active theme's path is registered first (highest priority).
            // The built-in default theme is always added as a fallback so that
            // views shipped with core (e.g. contact.blade.php) are available even
            // when the active theme hasn't overridden them. Laravel's addNamespace
            // merges hint paths, so the first registered path wins on conflict.
            $this->app->booted(function () {
                $active      = ThemeRegistry::active();
                $builtInPath = dirname(__DIR__) . '/resources/themes/contensio/default/views';

                if ($active && is_dir($active['viewPath'])) {
                    view()->addNamespace('theme', $active['viewPath']);
                }

                // Add built-in views as fallback (skipped if it IS the active theme)
                if (is_dir($builtInPath) && ($active['viewPath'] ?? '') !== $builtInPath) {
                    view()->addNamespace('theme', $builtInPath);
                }

                // Register widget areas declared in the active theme's theme.json.
                // Done in booted() so ThemeRegistry::active() is settled.
                if ($active && ! empty($active['meta']['widget_areas'])) {
                    WidgetArea::registerMany($active['meta']['widget_areas']);
                }
            });

            // Discover + register enabled plugins. Each plugin's own service
            // provider takes over from here (its register()/boot() run in the
            // normal Laravel lifecycle). Additionally, if the plugin's
            // manifest includes a "menu" block, we register a sidebar entry.
            PluginRegistry::discover();
            foreach (PluginRegistry::enabledNames() as $pluginName) {
                $plugin = PluginRegistry::get($pluginName);
                if (! $plugin) {
                    continue;
                }
                PluginRegistry::registerProvider($plugin, $this->app);

                // `menu` may be a single object or an array of objects.
                // A big plugin can declare multiple entries (e.g. root + tools).
                $menu = $plugin['meta']['menu'] ?? null;
                if (is_array($menu)) {
                    $entries = array_is_list($menu) ? $menu : [$menu];
                    foreach ($entries as $entry) {
                        if (is_array($entry) && ! empty($entry['placement']) && $entry['placement'] !== 'none') {
                            AdminNavigation::register(array_merge($entry, ['plugin' => $pluginName]));
                        }
                    }
                }
            }

            // Share custom content types with the admin layout for the sidebar
            View::composer('contensio::admin.layout', function ($view) {
                try {
                    $view->with('customContentTypes',
                        ContentType::where('is_system', false)
                            ->with('translations')
                            ->orderBy('id')
                            ->get()
                    );
                } catch (\Exception $e) {
                    $view->with('customContentTypes', collect());
                }
            });
        }

        // Render themed 404 pages for frontend routes (not admin, not API, not JSON).
        // Use $this->booted() so the exception handler is fully configured before we attach.
        $this->booted(function () {
            app(\Illuminate\Contracts\Debug\ExceptionHandler::class)
                ->renderable(function (NotFoundHttpException $e, $request) {
                    if ($request->expectsJson() || $request->is('account/*', 'api/*', 'install/*')) {
                        return null;
                    }

                    try {
                        $site = SiteConfig::all();
                        $lang = Language::where('is_default', true)->first()
                            ?? Language::where('status', '!=', 'disabled')->orderBy('position')->first();

                        return response()->view('contensio::errors.404', compact('site', 'lang'), 404);
                    } catch (\Throwable) {
                        return null; // DB not ready (install phase) — fall back to default
                    }
                });
        });

        // Auto-publish scheduled content every minute.
        $this->callAfterResolving(Schedule::class, function (Schedule $schedule) {
            $schedule->command('contensio:publish-scheduled')->everyMinute()->withoutOverlapping();
        });

        if ($this->app->runningInConsole()) {
            $this->commands([
                BackupCommand::class,
                InstallCommand::class,
                PublishScheduledContent::class,
                RestoreCommand::class,
                SeedBlockTypesCommand::class,
            ]);

            $this->publishes([
                __DIR__ . '/../config/contensio.php' => config_path('contensio.php'),
            ], 'contensio-config');

            $this->publishes([
                __DIR__ . '/../resources/views' => resource_path('views/vendor/contensio'),
            ], 'contensio-views');

            $this->publishes([
                __DIR__ . '/../public' => public_path('vendor/contensio'),
            ], 'contensio-assets');

            $this->publishes([
                __DIR__ . '/../lang' => $this->app->langPath('vendor/contensio'),
            ], 'contensio-lang');

            $this->publishesMigrations([
                __DIR__ . '/../database/migrations' => database_path('migrations'),
            ], 'contensio-migrations');
        }

        AboutCommand::add('Contensio', fn () => [
            'Version'   => '1.0.0',
            'Installed' => $this->isInstalled() ? 'Yes' : 'No',
        ]);
    }

    private function isInstalled(): bool
    {
        return (bool) env('CONTENSIO_INSTALLED', false);
    }
}
