<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

use Contensio\Cms\Support\MenuRenderer;
use Contensio\Cms\Support\ThemeOptions;
use Contensio\Cms\Support\ThemeRegistry;

if (! function_exists('theme_asset')) {
    /**
     * Return the public URL for an asset in the active theme.
     *
     * Usage in theme views:
     *   <link rel="stylesheet" href="{{ theme_asset('css/theme.css') }}">
     *   <img src="{{ theme_asset('images/logo.svg') }}">
     */
    function theme_asset(string $path): string
    {
        $active  = ThemeRegistry::active();
        $baseUrl = $active['assetUrl'] ?? 'themes/contensio/default';

        return asset(rtrim($baseUrl, '/') . '/' . ltrim($path, '/'));
    }
}

if (! function_exists('theme_menu')) {
    /**
     * Return the menu tree assigned to a theme location, or an empty array.
     *
     * Usage in theme views:
     *   @foreach(theme_menu('header') as $item)
     *       <a href="{{ $item['url'] }}" target="{{ $item['target'] }}">{{ $item['label'] }}</a>
     *   @endforeach
     */
    function theme_menu(string $location, ?int $langId = null): array
    {
        return MenuRenderer::forLocation($location, $langId);
    }
}

if (! function_exists('theme_option')) {
    /**
     * Return a customization value for the active theme, falling back
     * to the provided default if the key isn't set.
     *
     * Usage in theme views:
     *   style="color: {{ theme_option('primary_color', '#2563eb') }}"
     *   @if(theme_option('show_footer_tagline', true)) ... @endif
     */
    function theme_option(string $key, mixed $default = null): mixed
    {
        return ThemeOptions::get($key, $default);
    }
}
