<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

use Contensio\Support\Hook;
use Contensio\Support\MenuRenderer;
use Contensio\Support\PluginOptions;
use Contensio\Support\SiteConfig;
use Contensio\Support\ThemeOptions;
use Contensio\Support\ThemeRegistry;

// ── Hook helpers ─────────────────────────────────────────────────────────────

if (! function_exists('add_action')) {
    /**
     * Register an action callback on a hook.
     * The callback is called when do_action() fires the hook.
     * Return values are discarded — use add_filter() if you need to modify data.
     */
    function add_action(string $hook, callable $callback, int $priority = 10): void
    {
        Hook::addAction($hook, $callback, $priority);
    }
}

if (! function_exists('do_action')) {
    /**
     * Fire all callbacks registered for a hook, passing the given arguments.
     * Called by core at well-defined points in the lifecycle.
     */
    function do_action(string $hook, mixed ...$args): void
    {
        Hook::doAction($hook, ...$args);
    }
}

if (! function_exists('remove_action')) {
    /**
     * Remove a previously registered action callback.
     * You must pass the same callable reference that was used in add_action().
     */
    function remove_action(string $hook, callable $callback, int $priority = 10): void
    {
        Hook::removeAction($hook, $callback, $priority);
    }
}

if (! function_exists('has_action')) {
    /**
     * True if at least one callback is registered for the given action hook.
     */
    function has_action(string $hook): bool
    {
        return Hook::hasAction($hook);
    }
}

if (! function_exists('add_filter')) {
    /**
     * Register a filter callback on a hook.
     * The callback receives the current value as its first argument,
     * must return the (optionally modified) value.
     */
    function add_filter(string $hook, callable $callback, int $priority = 10): void
    {
        Hook::addFilter($hook, $callback, $priority);
    }
}

if (! function_exists('apply_filters')) {
    /**
     * Pass a value through all filter callbacks registered for a hook.
     * Returns the final filtered value.
     * Called by core wherever plugins should be able to modify data.
     */
    function apply_filters(string $hook, mixed $value, mixed ...$args): mixed
    {
        return Hook::applyFilters($hook, $value, ...$args);
    }
}

if (! function_exists('remove_filter')) {
    /**
     * Remove a previously registered filter callback.
     */
    function remove_filter(string $hook, callable $callback, int $priority = 10): void
    {
        Hook::removeFilter($hook, $callback, $priority);
    }
}

if (! function_exists('has_filter')) {
    /**
     * True if at least one callback is registered for the given filter hook.
     */
    function has_filter(string $hook): bool
    {
        return Hook::hasFilter($hook);
    }
}

// ── Site identity helpers ─────────────────────────────────────────────────────

if (! function_exists('site_name')) {
    /**
     * The site name from Settings → General.
     * Falls back to the app.name config value.
     *
     * Usage in theme templates:
     *   <title>{{ site_name() }}</title>
     */
    function site_name(): string
    {
        return (string) SiteConfig::get('name', config('app.name'));
    }
}

if (! function_exists('site_tagline')) {
    /**
     * The site tagline from Settings → General, or an empty string.
     *
     * Usage in theme templates:
     *   @if(site_tagline()) <p>{{ site_tagline() }}</p> @endif
     */
    function site_tagline(): string
    {
        return (string) SiteConfig::get('tagline', '');
    }
}

if (! function_exists('site_logo')) {
    /**
     * The site logo URL from Settings → General, or an empty string if not set.
     * A theme should fall back to the site name text when this is empty.
     *
     * Usage in theme templates:
     *   @if(site_logo())
     *       <img src="{{ site_logo() }}" alt="{{ site_name() }}" class="h-8 w-auto">
     *   @else
     *       <span>{{ site_name() }}</span>
     *   @endif
     */
    function site_logo(): string
    {
        return (string) SiteConfig::get('logo', '');
    }
}

if (! function_exists('site_favicon')) {
    /**
     * The site favicon URL from Settings → General, or an empty string if not set.
     * Falls back to the bundled Contensio icon when empty.
     *
     * Usage in theme templates:
     *   <link rel="icon" href="{{ site_favicon() ?: asset('vendor/contensio/img/favicon128x128.png') }}">
     */
    function site_favicon(): string
    {
        return (string) SiteConfig::get('favicon', '');
    }
}

// ── Theme / plugin helpers ────────────────────────────────────────────────────

if (! function_exists('theme_asset')) {
    /**
     * Return the public URL for an asset in the active theme.
     *
     * Usage in theme views:
     *   <link rel="stylesheet" href="{{ theme_asset('css/theme.css') }}">
     *   <img src="{{ theme_asset('images/logo.svg') }}">
     */
    function theme_asset(string $path): string
    {
        $active  = ThemeRegistry::active();
        $baseUrl = $active['assetUrl'] ?? 'themes/contensio/default';

        return asset(rtrim($baseUrl, '/') . '/' . ltrim($path, '/'));
    }
}

if (! function_exists('theme_menu')) {
    /**
     * Return the menu tree assigned to a theme location, or an empty array.
     *
     * Usage in theme views:
     *   @foreach(theme_menu('header') as $item)
     *       <a href="{{ $item['url'] }}" target="{{ $item['target'] }}">{{ $item['label'] }}</a>
     *   @endforeach
     */
    function theme_menu(string $location, ?int $langId = null): array
    {
        return MenuRenderer::forLocation($location, $langId);
    }
}

if (! function_exists('theme_option')) {
    /**
     * Return a customization value for the active theme, falling back
     * to the provided default if the key isn't set.
     *
     * Usage in theme views:
     *   style="color: {{ theme_option('primary_color', '#2563eb') }}"
     *   @if(theme_option('show_footer_tagline', true)) ... @endif
     */
    function theme_option(string $key, mixed $default = null): mixed
    {
        return ThemeOptions::get($key, $default);
    }
}

if (! function_exists('plugin_option')) {
    /**
     * Return a configuration value for a plugin, falling back to the
     * provided default if the key isn't set.
     *
     * Usage inside a plugin's code:
     *   $apiKey = plugin_option('acme/seo', 'google_verification', '');
     */
    function plugin_option(string $plugin, string $key, mixed $default = null): mixed
    {
        return PluginOptions::get($plugin, $key, $default);
    }
}
