<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Http\Controllers\Install;

use Contensio\Services\Install\EnvWriter;
use Contensio\Services\Install\Installer;
use Contensio\Services\Install\RequirementsChecker;
use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class InstallController extends Controller
{
    public function __construct(
        private RequirementsChecker $checker,
        private EnvWriter $env,
        private Installer $installer,
    ) {}

    // ─── Requirements ────────────────────────────────────────────────────────

    public function requirements()
    {
        if ((bool) env('CONTENSIO_INSTALLED', false)) {
            return redirect('/');
        }

        $results = $this->checker->check();
        $passes  = $this->checker->passes();

        return view('contensio::install.requirements', compact('results', 'passes'));
    }

    // ─── Step 1: Database ────────────────────────────────────────────────────

    public function database()
    {
        if ((bool) env('CONTENSIO_INSTALLED', false)) {
            return redirect('/');
        }

        if (!$this->checker->passes()) {
            return redirect()->route('contensio.install.requirements');
        }

        // Auto-skip only on first visit — not when navigating back
        if (! session('install_db_done') && $this->isDatabaseAlreadyConfigured()) {
            Artisan::call('migrate', ['--force' => true]);
            session(['install_db_done' => true]);
            return redirect()->route('contensio.install.website');
        }

        return view('contensio::install.database');
    }

    public function testDatabase(Request $request)
    {
        $request->validate([
            'db_host'     => 'required|string',
            'db_name'     => 'required|string',
            'db_username' => 'required|string',
            'db_password' => 'nullable|string',
            'db_port'     => 'nullable|integer',
        ]);

        try {
            $connection = new \PDO(
                sprintf(
                    'mysql:host=%s;port=%s;dbname=%s',
                    $request->db_host,
                    $request->db_port ?? 3306,
                    $request->db_name
                ),
                $request->db_username,
                $request->db_password ?? '',
            );

            $connection->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);

            return response()->json(['success' => true, 'message' => 'Connection successful!']);
        } catch (\PDOException $e) {
            return response()->json([
                'success' => false,
                'message' => 'Could not connect. Please check your credentials and try again.',
            ]);
        }
    }

    public function storeDatabase(Request $request)
    {
        $request->validate([
            'db_host'     => 'required|string',
            'db_name'     => 'required|string',
            'db_username' => 'required|string',
            'db_password' => 'nullable|string',
            'db_port'     => 'nullable|integer',
        ]);

        // Write to .env
        $this->env->setMany([
            'DB_CONNECTION' => 'mysql',
            'DB_HOST'       => $request->db_host,
            'DB_PORT'       => $request->db_port ?? 3306,
            'DB_DATABASE'   => $request->db_name,
            'DB_USERNAME'   => $request->db_username,
            'DB_PASSWORD'   => $request->db_password ?? '',
        ]);

        // Reconnect with new credentials
        $this->refreshDatabaseConnection($request);

        // Run migrations
        Artisan::call('migrate', ['--force' => true]);

        session(['install_db_done' => true]);

        return redirect()->route('contensio.install.website');
    }

    // ─── Step 2: Website ─────────────────────────────────────────────────────

    public function website()
    {
        if ((bool) env('CONTENSIO_INSTALLED', false)) {
            return redirect('/');
        }

        if (!session('install_db_done') && !$this->isDatabaseAlreadyConfigured()) {
            return redirect()->route('contensio.install.database');
        }

        return view('contensio::install.website', [
            'languages' => $this->installer->availableLanguages(),
        ]);
    }

    public function storeWebsite(Request $request)
    {
        $request->validate([
            'site_name' => 'required|string|max:255',
            'language'  => 'required|string|max:10',
        ]);

        // Generate app key if missing
        if (!config('app.key')) {
            Artisan::call('key:generate', ['--force' => true]);
        }

        $this->env->setMany([
            'APP_NAME' => $request->site_name,
        ]);

        $languageId = $this->installer->seedLanguage($request->language);
        $this->installer->seedSettings($request->site_name, $languageId);
        $this->installer->seedContentTypes($languageId);
        $this->installer->seedTaxonomies($languageId);
        $this->installer->seedBlockTypes();

        session([
            'install_db_done'      => true,
            'install_website_done' => true,
            'install_language_id'  => $languageId,
        ]);

        return redirect()->route('contensio.install.account');
    }

    // ─── Step 3: Admin Account ───────────────────────────────────────────────

    public function account()
    {
        if ((bool) env('CONTENSIO_INSTALLED', false)) {
            return redirect('/');
        }

        if (!session('install_website_done')) {
            return redirect()->route('contensio.install.website');
        }

        return view('contensio::install.account');
    }

    public function storeAccount(Request $request)
    {
        $request->validate([
            'name'                  => 'required|string|max:255',
            'email'                 => 'required|email|max:255',
            'password'              => 'required|string|min:8|confirmed',
        ]);

        $languageId = (int) session('install_language_id');
        $superAdminRoleId = $this->installer->seedRolesAndPermissions($languageId);

        $this->installer->createAdmin(
            name:              $request->name,
            email:             $request->email,
            password:          $request->password,
            superAdminRoleId:  $superAdminRoleId,
            languageId:        $languageId,
        );

        $this->installer->markInstalled();

        // Clear session
        session()->forget(['install_db_done', 'install_website_done', 'install_language_id']);

        return redirect()->route('contensio.install.complete');
    }

    // ─── Complete ─────────────────────────────────────────────────────────────

    public function complete()
    {
        return view('contensio::install.complete', [
            'admin_url'   => url(config('contensio.route_prefix')),
            'website_url' => url('/'),
        ]);
    }

    // ─── Helpers ─────────────────────────────────────────────────────────────

    private function isDatabaseAlreadyConfigured(): bool
    {
        // Require all MySQL fields to be non-empty before attempting connection
        if (config('database.default') === 'mysql') {
            $c = config('database.connections.mysql');
            if (empty($c['host']) || empty($c['database']) || empty($c['username'])) {
                return false;
            }
        }

        try {
            DB::connection()->getPdo();
            return true;
        } catch (\Exception) {
            return false;
        }
    }

    private function refreshDatabaseConnection(Request $request): void
    {
        config([
            'database.connections.mysql.host'     => $request->db_host,
            'database.connections.mysql.port'     => $request->db_port ?? 3306,
            'database.connections.mysql.database' => $request->db_name,
            'database.connections.mysql.username' => $request->db_username,
            'database.connections.mysql.password' => $request->db_password ?? '',
        ]);

        DB::purge('mysql');
        DB::reconnect('mysql');
    }
}
