<?php

/**
 * Contensio - The open content platform for Laravel.
 * A flexible content foundation for blogs, shops, communities,
 * and any content-driven app.
 * https://contensio.com
 *
 * Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * Contensio is operated by Host Server SRL.
 *
 * LICENSE:
 * Permissions of this strongest copyleft license are conditioned on making
 * available complete source code of licensed works and modifications, which
 * include larger works using a licensed work, under the same license.
 * Copyright and license notices must be preserved. Contributors provide an
 * express grant of patent rights. When a modified version is used to provide
 * a service over a network, the complete source code of the modified version
 * must be made available.
 *
 * @copyright   Copyright (c) 2026 Iosif Gabriel Chimilevschi
 * @license     https://www.gnu.org/licenses/agpl-3.0.txt  AGPL-3.0-or-later
 * @author      Iosif Gabriel Chimilevschi <office@contensio.com>
 *
 * DO NOT edit this file manually. All changes will be lost after software
 * update. For custom changes, use themes and plugins.
 */

namespace Contensio\Cms\Http\Controllers\Auth;

use Illuminate\Http\Request;
use Illuminate\Routing\Controller;
use Illuminate\Support\Facades\Auth;

class LoginController extends Controller
{
    public function showLogin()
    {
        if (Auth::check()) {
            return $this->redirectAfterLogin(Auth::user());
        }

        return view('cms::auth.login');
    }

    public function login(Request $request)
    {
        $credentials = $request->validate([
            'email'    => 'required|email',
            'password' => 'required',
        ]);

        // We use Auth::validate() so the password gets checked WITHOUT logging
        // the user in — because if they have 2FA enabled, we need to redirect
        // them to the 2FA challenge before completing the session.
        if (! Auth::validate($credentials)) {
            return back()->withErrors([
                'email' => 'These credentials do not match our records.',
            ])->onlyInput('email');
        }

        $user = \App\Models\User::where('email', $credentials['email'])->first();

        if (! $user->is_active) {
            return back()->withErrors([
                'email' => 'Your account has been disabled.',
            ])->onlyInput('email');
        }

        // If 2FA is enabled + confirmed, stash the user ID in the session and
        // redirect to Fortify's two-factor challenge. Fortify reads login.id /
        // login.remember to log the user in once the code is verified.
        if (
            ! is_null($user->two_factor_secret) &&
            ! is_null($user->two_factor_confirmed_at)
        ) {
            $request->session()->put([
                'login.id'       => $user->getAuthIdentifier(),
                'login.remember' => $request->boolean('remember'),
            ]);

            return redirect()->route('two-factor.login');
        }

        // No 2FA — complete the login the normal way.
        Auth::login($user, $request->boolean('remember'));
        $request->session()->regenerate();

        return $this->redirectAfterLogin($user);
    }

    public function logout(Request $request)
    {
        Auth::logout();
        $request->session()->invalidate();
        $request->session()->regenerateToken();

        return redirect()->route('cms.login');
    }

    private function redirectAfterLogin($user)
    {
        if ($user->canAccessAdmin()) {
            return redirect()->intended(route('cms.admin.dashboard'));
        }

        return redirect()->intended(route('cms.home'));
    }
}
